### ISSUE TITLE
Some notes about the initial version

### ISSUE THREAD

**Issue by tarsius** [magit/transient#1]
This is pre-alpha software, but if you concluded that it doesn't work at all yet because some commands don't do anything (they have no body), then you would be wrong. These commands don't do anything themselves, but running them while a transient command is active causes things to happen in `transient--pre-command` and `transient--post-command`.

The code is pretty tense and you will have to understand pretty much all of it to understand what is going on. I tried to arrange the code so that you can start reading at the top and if you have understood everything you have read so far, then you should also be able to understand the rest.

At this point in time `transient.el` is mostly an alternative to prefix arguments and cannot replace `magit-popup.el` yet, though that is the goal. The implementation of the core functionality that is already present is heavily inspired by how prefix arguments are implemented, in that "infix arguments" set variables whose values are later used by other commands. Like the prefix argument functionality, `transient` uses `set-transient-map` (from Emacs) but the use of that functionality is more complex here, so you might want to first fully understand how prefix arguments are implemented before you do the same for infix arguments.

----

Note that I will be amending to the initial commit for a while.

**Comment by tarsius** [comment]
Oh, if you just want to know how to use it, then see the `demo` branch.

**Comment by Silex** [comment]
Just commenting so I get updates :wink:

**Comment by alphapapa** [comment]
@tarsius I'm considering implementing a magit-popup-style UI for magit-todos.  Would you recommend basing it on magit-popup or waiting for this to mature?  Thanks for your work.

**Comment by tarsius** [comment]
Tataaaa: https://emacsair.me/2019/02/14/transient-0.1 :fireworks:

**Comment by Silex** [comment]
Amazing! Quick note: the README screenshot is a 404, also I'll get to it soonish but if there was some rough guide as to how to migrate from magit-popup to transient that'd all give us an head start :wink:
