### ISSUE TITLE
infix with predicate step on each other's foot

### ISSUE THREAD

**Issue by YorkZ** [magit/transient#101]
It's probably easier to explain by an example, So here's my code:

```
(transient-define-prefix build-popup ()
  ["Build app image"
    (app1:--image
     :if (lambda () (eq (app-type) 'app1)))
    (app2:--image
     :if (lambda () (eq (app-type) 'app2)))
    ("f" "make image" make-image)])

(transient-define-argument app1:--image ()
  :description "image type"
  :class 'transient-option
  :key "-i"
  :argument "--app1-image="
  :choices '("app1-image1" "app1-image2"))


(transient-define-argument app2:--image ()
  :description "image type"
  :class 'transient-option
  :key "-i"
  :argument "--app2-image=" 
  :choices '("app2-image1" "app2-image2"))

```

The popup menu shows up as expected, however, the options `--app1-image` and `app2-image` step on each other's foot when pressing "C-x C-s" on either one. For example:

1. Switch to `app1` (lisp function `app-type` returns `app1`)
2. Type `-i`, and then choose `app1-image1`
3. Type `C-x C-s` to save the option, and the option value is stored properly
4. Switch to `app2` (lisp function `app-type` returns `app2`)
5. Type `-i`, and then choose `app2-image1`
6. Type `C-x C-s` to save the option, and the option value is stored properly
7. Now, switch back to `app1` (lisp function `app-type` returns `app1`), the value of the option `app1-image` has been wiped out.

So what I expect is that both the options `app1-image` and `app2-image` are stored separately. I'm not sure if this is a bug of `transient`, or if it can be achieved in some other way.

**Comment by tarsius** [comment]
There was a bug which I very recently fixed. Have you updated before reporting this?

**Comment by tarsius** [comment]
Nevermind that's not it.

Try `:inapt-if` instead of `:if`. Might work.
But you should probably also look into using sub-transients.

**Comment by YorkZ** [comment]
What's the difference between `:inapt-if` and `:if`? I tried replacing the two `:if` in the above code example with `:inapt-if`, but the behavior was very weird, and was definitely what I wanted. Both `--app1-image=` and `--app2-image=` show up in the interface, and when I switched to `app1` and type `-i` followed by `app1-image1`, the interface showed `--app2-image=app1-image1`, and this exactly same string was also stored in the file `~/.emacs.d/transient/values`.

>  But you should probably also look into using sub-transients.

Could you be more specific about how to use sub-transient in my example. Please also consider that my example is a minimal example to make things simpler. In my real life code, I have a lot more suffix commands which shares between `app1` and `app2`.

**Comment by tarsius** [comment]
Are there any reasons to not just have two dedicated prefix commands, except for all the duplication?

Could I maybe see the real use-case instead? (I probably won't have time for any of this until the weekend.)

**Comment by YorkZ** [comment]
> Are there any reasons to not just have two dedicated prefix commands, except for all the duplication?

Yep, pretty much the only reason not having two dedicated prefix commands is to avoid code duplication. In fact, avoiding code duplication is pretty important for me because there will be actually five apps, meaning that if having dedicated prefix commands, I would have to have five of them which would be hardly acceptable.

> Could I maybe see the real use-case instead? (I probably won't have time for any of this until the weekend.)

I would really appreciate it, and that's probably the most effective way of accurate communication. Can I send some of my real code to you privately because I don't feel comfortable exposing too much personal info publicly.

**Comment by tarsius** [comment]
You might want to use something like this approach:

```elisp
(defvar common-parts ...)

(transient-define-prefix foo ...)
(put 'foo 'transient--layout
     (cl-mapcan (lambda (s) (transient--parse-child 'foo s))
                (cons [...]
                      common-parts)))
```

**Comment by tarsius** [comment]
I am considering this change:

```diff
(defun transient--parse-child (prefix spec)
  (cl-etypecase spec
    (symbol  (cl-mapcan (lambda (s) (transient--parse-child prefix s))
                        (symbol-value spec)))
    (vector  (when-let ((c (transient--parse-group  prefix spec))) (list c)))
    (list    (when-let ((c (transient--parse-suffix prefix spec))) (list c)))
    (string  (list spec))))
```

which would allow this:

```elisp
(setq common-parts
      '(("f" "make image" make-image)))

(transient-define-prefix build-popup ()
  ["Build app image"
   (app1:--image)
   common-parts])

(transient-define-prefix build-popup-2 ()
  ["Build app image"
   (app2:--image)
   common-parts])
```

**Comment by YorkZ** [comment]
Thank you so much @tarsius  for your help. Your "common part" idea is interesting, however, I'm having difficulty applying your model to my situation. So the following is my complete prefix command (I've transformed some names by the way):

```
(transient-define-prefix cool-app-popup ()
  "Popup console for building project options."
  [["Build"
    ([f7] "make" cool-app-build-current-app)
    ("c" "make clean" cool-app-make-clean-app)
    ("C" "make distclean" cool-app-make-distclean)
    ("d" "make deb" cool-app-make-deb)
    ("s" "make svn" cool-app-make-svn)
    ("I" "make docker-image" cool-app-build-docker-image)
    ("a" "build app" cool-app-build-app)]
   ["Build firmware image"
    (cool-app:--ubuntu-codename)
    (cool-app:--image
     :if (lambda () (eq (cool-app-type) 'cool-app)))
    (x30-platform:--image
     :if (lambda () (eq (cool-app-type) 'x30-platform)))
    "Actions"
    ("v" "build image" cool-app-build-image)]
   ["Install"
    (cool-app:--device)
    "Actions"
    ("i" "Install deb" cool-app-install-deb)
    ("e" "Install deb for current app" cool-app-install-deb-current-app)
    ("E" "efpinstall" cool-app-efpinstall)]
   ["Debugging"
    ("g" "gdb current app" cool-app-gdb-current-app)
    ("k" "run static check" cool-app-static-check)
    ("P" "make printvar-MAKE-VAR" cool-app-make-printvar)]
   ["Tagging"
    ("D" "make cdb" cool-app-make-cdb)
    ("R" "load rdm" cool-app-make-load-rdm)
    ("N" "re-index-rtags" cool-app-make-re-index-rtags)]
   ["Others"
    ("u" "Find file" cool-app-find-file)
    ("r" "Goto project root" cool-app-goto-project-root)
    ("m" "Dired all submodules" cool-app-dired-all-submodules)]])


(transient-define-argument cool-app:--ubuntu-codename ()
  "cool-app Ubuntu code name."
  :description "codename"
  :class 'transient-option
  :key "-c"
  :argument "--codename="
  :choices '("trusty" "xenial"))


(transient-define-argument cool-app:--image ()
  "cool-app firmware image type."
  :description "image type"
  :class 'transient-option
  :key "-i"
  :argument "--cool-app-image="
  :choices '("input-card" "display-card" "vip-st2110" "vip-sdi" "vip-av"
             "vip-ipg" "vip-sw"))


(transient-define-argument x30-platform:--image ()
  "x30-platform firmware image type."
  :description "image type"
  :class 'transient-option
  :key "-i"
  :argument "--x30-platform-image="
  :choices '("vip-hw" "vip-sw"))


(transient-define-argument cool-app:--device ()
  :description "target device name"
  :class 'transient-option
  :shortarg "-d"
  :argument "--device="
  :choices '("coolr2-8" "vip-sw-xenial" "vip-sw"))
```

So @tarsius could you please give me some idea as to how your model can be applied to this situation? Thanks in advance.

**Comment by tarsius** [comment]
I am afraid I don't understand this. Maybe if you could change this so that it actually behaved the way you want it to behave but with all the duplication in place that, for the time being, is necessary to make it so.

**Comment by tarsius** [comment]
Well something like this probably:

```elisp
(defvar common-parts
  '([["Build"
      ([f7] "make" cool-app-build-current-app)
      ("c" "make clean" cool-app-make-clean-app)
      ("C" "make distclean" cool-app-make-distclean)
      ("d" "make deb" cool-app-make-deb)
      ("s" "make svn" cool-app-make-svn)
      ("I" "make docker-image" cool-app-build-docker-image)
      ("a" "build app" cool-app-build-app)]
     ...]))

(transient-define-prefix cool-app-popup ()
  "Popup console for building project options."
  ["Build firmware image"
   (cool-app:--ubuntu-codename)
   (cool-app:--image)
   "Actions"
   ("v" "build image" cool-app-build-image)]
  common-parts)

(transient-define-prefix x30-platform-popup ()
  "Popup console for building project options."
  ["Build firmware image"
   (x30-platform:--image)
   "Actions"
   ("v" "build image" cool-app-build-image)]
  common-parts)
```

Yes this changes the order of the groups, but that can be addressed by splitting up `common-parts` into multiple parts that can be composed more freely.

**Comment by YorkZ** [comment]
Thanks again @tarsius, I'll give it a try.

**Comment by YorkZ** [comment]
Not sure if I understand it correctly, but I patched your code in `transient--parse-child`, and with the following code:

```
(defvar cool-app-common-make-targets nil)
(setq cool-app-common-make-targets
      '([["Build"
          ([f7] "make" cool-app-build-current-app)
          ("c" "make clean" cool-app-make-clean-app)
          ("C" "make distclean" cool-app-make-distclean)
          ("d" "make deb" cool-app-make-deb)
          ("s" "make svn" cool-app-make-svn)
          ("I" "make docker-image" cool-app-build-docker-image)
          ("a" "build app" cool-app-build-app)]
         ["Install"
          (cool-app:--device)
          "Actions"
          ("i" "Install deb" cool-app-install-deb)
          ("e" "Install deb for current app" cool-app-install-deb-current-app)
          ("E" "efpinstall" cool-app-efpinstall)]
         ["Debugging"
          ("g" "gdb current app" cool-app-gdb-current-app)
          ("k" "run static check" cool-app-static-check)
          ("P" "make printvar-MAKE-VAR" cool-app-make-printvar)]
         ["Tagging"
          ("D" "make cdb" cool-app-make-cdb)
          ("R" "load rdm" cool-app-make-load-rdm)
          ("N" "re-index-rtags" cool-app-make-re-index-rtags)]
         ["Others"
          ("u" "Find file" cool-app-find-file)
          ("r" "Goto project root" cool-app-goto-project-root)
          ("m" "Dired all submodules" cool-app-dired-all-submodules)]]))

(transient-define-prefix cool-app-popup ()
  "Popup console for building project options."
  ["Build firmware image"
   (cool-app:--ubuntu-codename)
   (cool-app:--image)
   "Actions"
   ("v" "build image" cool-app-build-image)]
  cool-app-common-make-targets)
```

The popup didn't show up at all.

What about the `class`, can `class` be used here somehow?

**Comment by tarsius** [comment]
Turns out the change to `transient--parse-child` didn't quite cut it. Try again with the `common` branch.

**Comment by YorkZ** [comment]
Hi @tarsius, sorry for responding late as I was too stressful with my job during the last few days. I didn't see a branch called `common`, so am I supposed to try this out using the latest `master`?

**Comment by tarsius** [comment]
No, there really is such a branch: https://github.com/magit/transient/tree/common.

**Comment by tarsius** [comment]
> No, there really is such a branch

Until just now. I have just merged into `master`.
