### ISSUE TITLE
Allow dynamic mode name for transient buffers

### ISSUE THREAD

**Issue by codygman** [magit/transient#120]
> Then describe the feature you would like to see in Magit and why it would be useful to you.  You might also want to describe any alternative solutions or features you've considered.

I frequently use transient buffers for voice coding. I use emacs mode specific voice commands by taking advantage of the emacs title and displaying the current mode.

Maybe the screen shot will be helpful:

![talon-dired-example-edit](https://user-images.githubusercontent.com/225847/119178010-c1f32280-ba32-11eb-841a-240ab70740d3.png)

Said the problem is the transient buffers only say `fundamental-mode` in the title and if possible I'd like them to say `transient-mode-%s`.

So far the wonderful docker.el package the transient buffer mode may read `transient-mode-docker` and for doctor compose may read `transient-mode-docker-compose`. Then my voice command `Stop` for each will be context specific.

It may not seem like a big deal to have to pretend voice commands with the name of the mode, but I'd rather err on the safe side and not stress out my current primary mode of input :slightly_smiling_face:

**Comment by tarsius** [comment]
> I use emacs mode specific voice commands by taking advantage of the emacs title and displaying the current mode.

Couldn't you just also consider the `buffer-name`?
