### ISSUE TITLE
accessibility setting for low vision in transient maps

### ISSUE THREAD

**Issue by p1llule** [magit/transient#122]
Hi, 

I noticed that using Magit while using a big font is a little difficult, see this attached example :
[Seeing only a portion of the transient map with no truncated lines](https://drop.chapril.org/download/91f1824f58303c0a/#d6tPQM3jUpHBlnOLbDXarA)

Accessing informations on a regular prefix map can be done with [prefix-map-keybinding C-h], unfortunately Magit does seem to expose such functionality ; we can access all the keybinding with [C-h m] but this is not the same command nor result.

When displaying a transient map, we can still navigate inside with scroll horizontally and vertically commands, however having to scroll-left|right to see the different columns feel a little clunky and less accessible than a regular help buffer. Also letting the user use some of the others navigation commands may help a little because the commands cited above are quite brutal.

So I believe there is two way to improve the accessibility of the magit transient maps : 

 1. Or the transient map put his columns one after another vertically when the width is not sufficient to display them horizontally
 2. Or the transient map expose a command help similar of what we can have for prefix map and the user can fallback on it.

I rather prefer 1. because it believe it will be still difficult for a new user to understand the dash options commands in a regular help buffer.

**Comment by p1llule** [comment]
ty ;)

**Comment by tarsius** [comment]
> Or the transient map put his columns one after another vertically when the width is not sufficient to display them horizontally

So then you have to scroll vertically instead. How is that better? Just one dimension to scroll in?

**Comment by tarsius** [comment]
Please give the `single-column` branch a try.

**Comment by p1llule** [comment]
> > Or the transient map put his columns one after another vertically when the width is not sufficient to display them horizontally
> 
> So then you have to scroll vertically instead. How is that better? Just one dimension to scroll in?

Yes I think one dimension is better. 

> Please give the `single-column` branch a try.

Oh I see you already merged that and this is now a custom variable named `transient-force-single-column`.

Also looking at what @tvraman uses himself for transient make me discover that there was already an option to enable navigations keys, and that works very well.

The setup I pushed now is fairly simple ; for the record if anyone is interested, it is :

```` emacs-lisp
(use-package magit
  :command magit-status
  :custom
  ;; does not create a margin
  ;; that was mangling the visual
  (magit-log-margin '(nil age magit-log-margin-width t 18)))

(use-package transient
  :after magit
  :custom
  ;; let us use navigation keys to
  ;; see the differents commands
  (transient-enable-popup-navigation t)
  ;; show columns vertically
  (transient-force-single-column t))
````
And there is this window setup that force magit (but not only) to not spawn new windows :

```` emacs-lisp
;; ** only one window at once
;; emacs poping windows is disruptive
;; we can prevent that.
;; First create a display function
;; that paid no respect for the
;; `inhibit-same-window' parameter
(defun display-buffer-strictly-same-window (buffer alist)
  "Display BUFFER in the selected window.
ALIST is an association list of action symbols and values.  See
Info node `(elisp) Buffer Display Action Alists' for details of
such alists.

This function totally ignore if ALIST has an `inhibit-same-window'.

This is an action function for buffer display, see Info
node `(elisp) Buffer Display Action Functions'.  It should be
called only by `display-buffer' or a function directly or
indirectly called by the latter."
  (unless (or (window-minibuffer-p)
	      (window-dedicated-p))
    (window--display-buffer buffer (selected-window) 'reuse alist)))

;; Then use it as the base action
;; for all calls to display-buffer
(customize-set-variable
 'display-buffer-base-action
 '((display-buffer-strictly-same-window)
   (reusable-frames . t)))
````

I think that's it, I have no more observations for accessibility settings :)
Thank you Tarsius.

**Comment by p1llule** [comment]
A minor nitpick thought, 

It seems that magit is somehow binding C-p to universal-argument in the transient map ?

````
overriding-terminal-local-map C-p
transient--transient-map C-p
transient-map C-p
````

So this is conflicting with the C-p of `transient-popup-navigation-map`

**Comment by tarsius** [comment]
Yikes, that's not intentional. Should be `C-u` as in `global-map`. Only in my *personal* configuration is `C-p` supposed to be bound to `universal-command`.

**Comment by tvraman** [comment]
p1llule ***@***.***> writes:

This is nice. Rather than calling what you have "Accessibility Settings"
which being a generic term wont make any sense to folks who see it six
months or a year from now, describe the actual user situation where this
helps, e.g. low-vision, being as accurate as possible with respect to
the type of low-vision you're talking about.

As an example, as a blind user  someone might think I would use only one
window on the screen, but I actually find multiple windows useful since
that then gives me a quick-fire way of switching amongst a pair of
displayed buffers.

>     Or the transient map put his columns one after another vertically
>     when the width is not sufficient to display them horizontally
>
>     So then you have to scroll vertically instead. How is that better?
>     Just one dimension to scroll in?
>
> Yes I think one dimension is better.
>
>     Please give the single-column branch a try.
>
> Oh I see you already merged that and this is now a custom variable
> named transient-force-single-column.
>
> Also looking at what @tvraman uses himself for transient make me
> discover that there was already an option to enable navigations keys,
> and that works very well.
>
> The setup I pushed now is fairly simple ; for the record if anyone is
> interested, it is :
>
> (use-package magit
>   :command magit-status
>   :custom
>   ;; does not create a margin
>   ;; that was mangling the visual
>   (magit-log-margin '(nil age magit-log-margin-width t 18)))
>
> (use-package transient
>   :after magit
>   :custom
>   ;; let us use navigation keys to
>   ;; see the differents commands
>   (transient-enable-popup-navigation t)
>   ;; show columns vertically
>   (transient-force-single-column t))
>
> And there is this window setup that force magit (but not only) to not
> spawn new windows :
>
> ;; ** only one window at once
> ;; emacs poping windows is disruptive
> ;; we can prevent that.
> ;; First create a display function
> ;; that paid no respect for the
> ;; `inhibit-same-window' parameter
> (defun display-buffer-strictly-same-window (buffer alist)
>   "Display BUFFER in the selected window.
> ALIST is an association list of action symbols and values.  See
> Info node `(elisp) Buffer Display Action Alists' for details of
> such alists.
>
> This function totally ignore if ALIST has an `inhibit-same-window'.
>
> This is an action function for buffer display, see Info
> node `(elisp) Buffer Display Action Functions'.  It should be
> called only by `display-buffer' or a function directly or
> indirectly called by the latter."
>   (unless (or (window-minibuffer-p)
> 	      (window-dedicated-p))
>     (window--display-buffer buffer (selected-window) 'reuse alist)))
>
> ;; Then use it as the base action
> ;; for all calls to display-buffer
> (customize-set-variable
>  'display-buffer-base-action
>  '((display-buffer-strictly-same-window)
>    (reusable-frames . t)))
>
> I think that's it, I have no more observations for accessibility
> settings :)
> Thank you Tarsius.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
