### ISSUE TITLE
Enable Layout Customization In Transient

### ISSUE THREAD

**Issue by tvraman** [magit/transient#123]
Thanks for the pointer. Looking at it, here is what I currently do in
emacspeak; this might well help the low-vision user who asked the
question. That aside, I'd still like to know how I can change the
layout --- classes transient-columns and transient-row look relevant
but I dont  know  how to use those to change all transients to behave
differently.

In the meantime,  module emacspeak-transient.el from emacspeak at
https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-transient.el#L68
enables one to suspend the transient by pressing C-z, browse the
transient  buffer at one's leisure, then hit C-c C-c to resume  the
transient. Works in that one can learn oft-used combinations, but
things I do rarely, eg forge issues etc are harder because I can never
remember what I learnt.

**Comment by tarsius** [comment]
If this is about displaying everything in a single column, then checkout #122.

Otherwise you'll have to be a lot more specific.

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:
I'll look that up.

I was thinking more of producing the transpose of what transient
currently produces, and what  you point at might well do that, so let me
go play with it.
> If this is about displaying everything in a single column, then
> checkout #122.
>
> Otherwise you'll have to be a lot more specific.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮m

**Comment by tvraman** [comment]
Now confused -- #122 is from 10 years ago and talks of something else.

Searching for column in transient.el shows me the various layout classes
but I couldn't immediately figure out how I was supposed to use them.

"T.V Raman" ***@***.***> writes:

> Jonas Bernoulli ***@***.***> writes:
> I'll look that up.
>
> I was thinking more of producing the transpose of what transient
> currently produces, and what  you point at might well do that, so let me
> go play with it.
>> If this is about displaying everything in a single column, then
>> checkout #122.
>>
>> Otherwise you'll have to be a lot more specific.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by kyleam** [comment]
> Now confused -- #122 is from 10 years ago and talks of something else.

This issue was transferred from magit/magit to magit/transient, so that's referring to <https://github.com/magit/transient/issues/122> not <https://github.com/magit/magit/issues/122>.

**Comment by tvraman** [comment]
"T.V Raman" ***@***.***> writes:

I tried posting this follow-up using forge to the transient repo issue
list but it gave me a 403 admin error.
Apologies for sending it by email:
Thanks for the pointer. Looking at it, here is what I currently do in
emacspeak; this might well help the low-vision user who asked the
question. That aside, I'd still like to know how I can change the
layout --- classes transient-columns and transient-row look relevant
but I dont  know  how to use those to change all transients to behave
differently.

In the meantime,  module emacspeak-transient.el from emacspeak at
https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-transient.el#L68
enables one to "suspend" the transient by pressing C-z, browse the
transient  buffer at one's leisure, then hit C-c C-c to resume  the
transient. Works in that one can learn oft-used combinations, but
things I do rarely, eg forge issues etc are harder because I can never
remember what I learnt.



> Now confused -- #122 is from 10 years ago and talks of something else.
>
> Searching for column in transient.el shows me the various layout classes
> but I couldn't immediately figure out how I was supposed to use them.
>
> "T.V Raman" ***@***.***> writes:
>
>> Jonas Bernoulli ***@***.***> writes:
>> I'll look that up.
>>
>> I was thinking more of producing the transpose of what transient
>> currently produces, and what  you point at might well do that, so let me
>> go play with it.
>>> If this is about displaying everything in a single column, then
>>> checkout #122.
>>>
>>> Otherwise you'll have to be a lot more specific.
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub, or unsubscribe.
>>>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
> That aside, I'd still like to know how I can change the
> layout --- classes transient-columns and transient-row look relevant
> but I dont  know  how to use those to change all transients to behave
> differently.

I think you shouldn't change the layout beyond what setting `transient-force-single-column` to `t` gives you. Doing that ensures that the moving command navigate them in a meaningful order. I assume that's what you are after.

The movement commands are not aware of the semantics of groups. If a group is displayed as a table whose first dimension is the row, then that is no problem. But for `transient-columns` it is. Here the first dimension is the column but the text based movement commands move linearly in the text, i.e. first left to right in a line (row) and only then to the next line (column). That's what causes them to be read back to you in a weird order.

I am sure you understand that and just wanted to spell it out to demonstrate that I understand it as well. I cannot imagine another rearrangement that might help you, so you have to tell me if there is any.

Note that every class can implement the `transient--insert-group` generic function. Doing that is actually the main reason why one might want to define a new class. If a third-party does that, then there is no guarantee that they respect `transient-force-single-column`, but we can worry about that when it first happens.

**Comment by tvraman** [comment]
For now I'm happy having discovered the render in one column along with
the ability to turn on navigating the transient buffer.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
