### ISSUE TITLE
Zombie transient key map

### ISSUE THREAD

**Issue by tecosaur** [magit/transient#124]
It's not very clear exactly what's going on with the situation below, so feel free to close this on that account. It's also very possible I've just done something silly.

<details>
<summary>
System info
</summary>

- Emacs: `28.0.50 ~ HEAD`
- Transient: 601ebf5
- Magit: https://github.com/magit/magit/commit/3a39338a4382de13972adb55c528a8ec68e7ab21
</details>

# Background

I'm currently trying to create a transient (for a new package called `orgdiff`) that involves setting a range of git commits. I found `magit-log-select` and have been trying to incorperate it.

I'm attempting this by defining a `transient-lisp-variable` infinix which uses a `:reader` that:
- exits the transient
- prompts for 1-2 commits via `magit-log-select`
- sets the relevant lisp variable based on the result
- calls the transient again

```lisp
   (progn (run-at-time nil nil #'transient--emergency-exit) nil)
   (magit-log-select
     (lambda (r1)
       (setq orgdiff--rev1 r1)
       (magit-log-select
         (lambda (r2)
           (setq orgdiff-git-range (substring-no-properties (concat orgdiff--rev1 ".." r2)))
           (orgdiff-transient))
         "Second revision: type %p to select commit at point, %q to use the current working state instead"
         (lambda ()
           (setq orgdiff-git-range (substring-no-properties orgdiff--rev1))
           (orgdiff-transient))))
     "First revision (o: type %p to select commit at point, %q to not compare any revisions"
     #'orgdiff-transient)
```
[ whole package (WIP): [http://ix.io/3rmm](http://ix.io/3rmm) ]

# The issue

This _almost_ seems to work, with one huge caviat: after triggering this the transient keymap _never goes away_. I can type normally, but as soon as I type a char used by the transient (i.e. `-` or one of the action keys) it's intercepted and the transient action executed. Calling `transient--emergency-exit` doesn't solve this, neither does killing the curernt buffer.

I suspect I may be doing something weird, but it seems like there could be something funky going on with transient.

**Comment by tecosaur** [comment]
I had a thought that this may be related to my use of `run-at-time`, and so I tried a bit of re-arrangement.

```lisp
  (orgdiff--define-infix
   "-r" "git-range" "Git revision"
   '(choice string boolean) nil
   (run-at-time
    nil nil
    (lambda ()
      (transient--emergency-exit)
      (magit-log-select
        (lambda (r1)
          (setq orgdiff--rev1 r1)
          (magit-log-select
            (lambda (r2)
              (setq orgdiff-git-range (substring-no-properties (concat orgdiff--rev1 ".." r2)))
              (orgdiff-transient))
            "Second revision (newer): type %p to select commit at point, %q to use the current working state instead"
            (lambda ()
              (setq orgdiff-git-range (substring-no-properties orgdiff--rev1))
              (orgdiff-transient))))
        "First revision (older): type %p to select commit at point, %q to not compare any revisions"
        #'orgdiff-transient)))
   nil))
```

I don't understand what happened, but this seems to have fixed it. As such, I'm going to treat this as a me-issue not a transient-issue and close this :slightly_smiling_face:.

Sorry for the noise.

**Comment by tarsius** [comment]
I have just pushed a major update.

Try this:

```elisp
(defclass demo-log-select-option (transient-option) ())

(cl-defmethod transient-infix-read :around ((obj demo-log-select-option))
  (cl-call-next-method obj))

(cl-defmethod transient-infix-read ((obj demo-log-select-option))
  (transient--suspend-override)
  (magit-log-select
    (lambda (rev)
      (transient--resume-override)
      (transient-infix-set obj rev))
    nil #'transient--resume-override)
  ;; Return current value so it gets "reinstated", in case we abort.
  (oref obj value))
  
(transient-define-infix demo-log-select ()
  :class 'demo-log-select-option
  :argument "--commit="
  :description "Commit")
```

**Comment by tecosaur** [comment]
Thanks @tarsius, this seems to be behaving better 🙂
