### ISSUE TITLE
Simple set argument does not work i.c.w. :transient-suffix 'transient-do-stay

### ISSUE THREAD

**Issue by dalanicolai** [magit/transient#125]
magit version: Magit v3.1.1-49-gd3a729b1, Git 2.31.1, Emacs 28.0.50, gnu/linux

As mentioned in this bug report's title, setting an argument as follows does not work with `:transient-suffix 'transient-do-stay`.
To reproduce, load the following code:

```
(transient-define-prefix  test-transient ()
  "Some Emacs magic"
  ;; :transient-suffix     'transient--do-stay
  ;; :transient-non-suffix 'transient--do-warn
  ["Arguments"
   ("-a" "Test arg" "--test-arg")]
  ["Commands"
  ("p" "print args" pa)]
  [("q" "Quit"      transient-quit-one)])

(defun pa (args)
  (interactive (list (transient-args 'test-transient)))
  (print args))
```

Then call the transient, and toggle/activate the argument and press `p` to print the argument.
Subsequently repeat after commenting out the line  `:transient-suffix     'transient--do-stay`.

The first procedure shows the argument, the second procedure shows that the argument list is empty (which I would expect it should not).

It is probably expected, but I anyway mention that defining the infix separately as follows:

(transient-define-infix test-arg ()
  :description "Test arg"
  :class 'transient-switch
  :argument "--test-arg")

 (and correspondingly modifying the prefix definition), shows the same behavior.

**Comment by tarsius** [comment]
You want to use `transient--do-call` instead.

`transient--do-stay`'s doc-string says: "Call the command **without** exporting variables and stay transient."

**Comment by dalanicolai** [comment]
Thanks for your very helpful quick reply. I have just uploaded the first, fully functional, draft of [sketch-mode](https://github.com/dalanicolai/sketch-mode). Would be great if you quickly take a minute to check it out; just to enjoy how your awesome transient package gets used/picked up.
You can simply load `sketch-mode.el` and then call `M-x sketch`. Thanks to `transient`, the rest is more or less fully self-explanatory.

**Comment by tarsius** [comment]
I played around with it a bit. It's nice but doesn't quite work for me yet. There is a mismatch between the command being named `sketch-interactively-1` but in others `sketch-interactively`. I fixed that but then using that command somehow broke a subsequent `q`. So yeah, its nice but probably doesn't fall into the "look at this fancy stuff that just works" category; more like "these edge-cases will require hours of work".

**Comment by dalanicolai** [comment]
Thanks for looking at it. I did not really expect you to spend more time on it, I really meant check it out for a minute `literally`, just to see another usage example of transient (you could e.g. refer to it for another usage example for 'developers', i.e. for how to create e.g. the `sketch-variable:colors` transient-infix class). The two `sketch-interactively` function alternatives are for different purposes, which should still get documented. Otherwise, usually, the mode starts with the `transient` which automatically binds the `sketch-interactively-1` suffix. The package provides some more options beside the transient, but that is all experimental (still searching for how to design a most usable interface).

About the mode; I just quickly wanted to sketch a very simple lens diagram, i.e. an ellipse and some straight lines. I started typing it out (using the elisp svg functions) but thought it this was a little cumbersome. So then I quickly created the option to just draw it (this was the `sketch-interactively`). However, then I wanted to be able to quickly configure some options and I figured that `transient` would provide a very nice interface for it. So then I added the transient, which required the modified interactive sketch function/transient-suffix, i.e. `sketch-interactively-1`. It really had to be defined as a transient-suffix for the event, (using `(interactive "e)`), to get passed as an argument (when defining it with `defun`, passing the event this way as an argument did not work).

Anyway, I indeed liked very much the `transient` interface, but I realized that the mode is still too simple. So I added some very primitive undo/redo functionality. But now I wanted to sketch e.g. a parabola also. I created a macro now for that also, but to make this functionality complete and user-friendly requires a lot of work. And now I think it would be nice to be able to resize objects by dragging, but that would require implementing 'nodes`. Also, indeed it is not clear how to design a clean interface for all this (that just works). So in the end it is becoming a rabbit hole. 

Anyway, still this same approach could be used to provide a nice interface for `tikz` or `asymptote` (that for a large part already make use of 'nodes`) so probably I will port this to use one of those at some point and keep this package as a nice starting point for others to extend/play with. 
Still, I thought the transient might provide another nice showcase for transient (e.g. for pointing out it can also be used for configuring elisp commands instead of shell commands).
