### ISSUE TITLE
Issue with read-minibuffer-restore-windows

### ISSUE THREAD

**Issue by manuel-uberti** [magit/transient#128]
Hi,

I am using GNU Emacs 28.0.50 (commit: `85c8a9cd0cff0e2f6d5470423731d9f1e87e2cde`) and Magit 3.2.1.0.20210806.211302, Git 2.25.1 on Ubuntu 20.04.

From `emacs -Q`:

- `(setq read-minibuffer-restore-windows nil)`
- <kbd>M-x package-initialize</kbd>
- <kbd>M-x fido-mode RET</kbd>
- <kbd>M-x icomplete-vertical-mode RET</kbd>
- <kbd>C-x g</kbd>
- I used `.emacs.d`, but pick a Git-versioned directory of your choice and make you have more than one branches
- <kbd>b b</kbd>, in my case I pick `icomplete`
 
![1](https://user-images.githubusercontent.com/8199224/128601400-c421cc72-1a6c-494d-a8c5-2e3e42bfd29a.png)

- and hit <kbd>RET</kbd>

![2](https://user-images.githubusercontent.com/8199224/128601420-1b22231b-d634-498b-831d-1fa2c7093e1b.png)

- now hit <kbd>C-n</kbd>

![3](https://user-images.githubusercontent.com/8199224/128601471-ccc6f4a8-51a9-4d15-aa13-d4417e58f7c1.png)

**Comment by tarsius** [comment]
I can reproduce it and have seen similar issue in other context unrelated to `transient`.

I don't know what to do about it and would appreciate it if you could investigate a bit yourself.

I have already tried changing the order of `minibuffer-exit-hook`. It didn't make a difference.

**Comment by tarsius** [comment]
Like https://github.com/tarsius/moody/issues/19... oh look it is you. :grinning:

**Comment by tarsius** [comment]
Thanks to @memeplex this is now fixed in Emacs 29.0.50 and we use a better kludge for older versions. See https://github.com/tarsius/moody/pull/35.

**Comment by manuel-uberti** [comment]
Lovely, thanks!
