### ISSUE TITLE
Feature/Question More Flexible :incompatible

### ISSUE THREAD

**Issue by LaurenceWarne** [magit/transient#129]
Hi, I would like to use `:incompatible` in `transient-define-prefix` and have it so that `-x` is incompatible with everything in `[-a, -b, -c]`, but everything in `[-a, -b, -c]` is compatible with one another.

Experimentally, and looking at https://github.com/magit/transient/blob/626d105ecfb44ab9e1a4bf1fccb9340d6488b631/lisp/transient.el#L2676

Only the first sublist which `-x` is present in is considered (please correct me if I'm wrong), so something like `:incompatible '(("-x" "-a") ("-x" "-b") ("-x" "-c"))` wouldn't have the effect I assumed it would looking at the [doc](https://github.com/magit/transient/blob/51e833e5152e9fdcdc1dbbf34ad2d4905bde1f69/docs/transient.org#prefix-slots) - though that's just my interpretation :slightly_smiling_face: .

I'm currently modifying the method slightly to get what I want:

```elisp
(cl-defmethod transient-infix-set :around
  ((obj my--transient-argument) value)
  "Unset incompatible infix arguments."
  (let ((arg (if (slot-boundp obj 'argument)
                 (oref obj argument)
               (oref obj argument-regexp))))
    (if-let* ((sic (and value arg transient--unset-incompatible))
              (spec (oref transient--prefix incompatible))
              (incomp-matching (cl-remove-if-not
                                (lambda (elt) (member arg elt)) spec))
              (incomp (flatten-list
                       (mapcar (lambda (e) (remove arg e)) incomp-matching))))
        (progn
          (cl-call-next-method obj value)
          (dolist (arg incomp)
            (when-let ((obj (cl-find-if (lambda (obj)
                                          (and (slot-boundp obj 'argument)
                                               (equal (oref obj argument) arg)))
                                        transient--suffixes)))
              (let ((transient--unset-incompatible nil))
                (transient-infix-set obj nil)))))
      (cl-call-next-method obj value))))
```

Do you think supporting selections like `'(("-x" "-a") ("-x" "-b") ("-x" "-c"))` is a good idea or am I going about this the wrong way :slightly_smiling_face: ?

**Comment by psionic-k** [comment]
This really should work.  I think what you're seeing is a result of #155

I hope your modification is bug fix.  Do you think it's PR ready?

**Comment by LaurenceWarne** [comment]
> This really should work. I think what you're seeing is a result of #155

Yeah, looks the same to me.

> I hope your modification is bug fix. Do you think it's PR ready?

I've been using it for a while here: https://github.com/LaurenceWarne/finito.el/blob/ae37ef3a81107b92623187443e764ce0b3d92a6f/finito-view.el#L70.  I've also created quick gist here from the issue: https://gist.github.com/LaurenceWarne/af3e48ee9f2d6b2a14bea04dd458ccf6, lgtm playing around with it - can you confirm?
