### ISSUE TITLE
Canceling transient quits magit status when both in top side window

### ISSUE THREAD

**Issue by noctuid** [magit/transient#130]
I currently display magit buffers (status, log, etc.) in a top side window. I'd like to also display transients in a top side window. Normally if I open the log from the status buffer and then use `magit-log-bury-buffer`, the side window will stay open and return to the status buffer. If I display transients in a top side window, it will instead close the side window. Similarly if I quit the transient before selecting a log command, it will close the status buffer. If it would be possible to have transient return to the previous side window contents after closing, that would be nice.

**Comment by tarsius** [comment]
> I'd like to also display transients in a top side window. 

How do you accomplish this. Show your personal code. Actually show all the existing personal code and configuration that affects how magit and transient deal with buffers and windows.

**Comment by noctuid** [comment]
Here is a minimal init.el to reproduce (using straight but can be replaced with package.el):
```elisp
;; * Straight
;; Install and load straight.el
;; https://github.com/raxod502/straight.el#getting-started
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el"
                         user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; * Config
(straight-use-package 'magit)
(require 'magit)
(global-set-key (kbd "C-x g") #'magit-status-here)

;; not actually necessary
(setq magit-display-buffer-function #'display-buffer)

(defun noct-match-magit-status-mode (buffer-or-name _action)
  (ignore-errors
    (let ((buffer (get-buffer buffer-or-name)))
      (eq (buffer-local-value 'major-mode buffer) 'magit-status-mode))))

(cl-pushnew '(noct-match-magit-status-mode
              display-buffer-in-side-window
              (side . top))
            display-buffer-alist)

(defun noct-match-magit-log-mode (buffer-or-name _action)
  (ignore-errors
    (let ((buffer (get-buffer buffer-or-name)))
      (eq (buffer-local-value 'major-mode buffer) 'magit-log-mode))))

(cl-pushnew '(noct-match-magit-log-mode
              display-buffer-in-side-window
              (side . top))
            display-buffer-alist)

(setq transient-display-buffer-action '(display-buffer-in-side-window
                                        (side . top)))
```

Open emacs in git repo. `C-x g l C-g` closes the magit status window when exiting the transient. When transient is shown in a different side window, the magit status window stays open.

`C-x g l l q` closes the top side window. Comment the `transient-display-buffer-action` setting, and it instead returns to the status buffer.

**Comment by noctuid** [comment]
It seems transient expects to be in a new window and does not work well when shown in an existing window (e.g. `display-buffer-use-some-window` will close windows). I'm using this as a workaround for now, though I may have missed some things.

```elisp
(defun transient--delete-window ()
  (when (window-live-p transient--window)
    (let ((buf (window-buffer transient--window)))
      ;; (with-demoted-errors "Error while exiting transient: %S"
      ;;   (delete-window transient--window))
      (set-window-dedicated-p transient--window nil)
      (set-window-parameter transient--window 'no-other-window nil)
      (setq window-size-fixed nil)
      (kill-buffer buf))))
```

Maybe it would make sense to have a setting to let transient know it is being displayed in an existing window and should undo changes to that window and not close it afterwards? Or maybe it could check if the window already existed?

**Comment by tarsius** [comment]
Sorry for the long delay.

I have just pushed 7c67773735dea5a0c41ad8afb69fdafb62c46c7c. With that you should be able to accomplish this without having to redefine any function. I have tested with:

```elisp
(setq magit-display-buffer-function
      (lambda (buffer)
	(display-buffer
	 buffer '(display-buffer-in-side-window
		  (side . top)))))
(setq transient-display-buffer-action
      '(display-buffer-in-side-window
	(side . top)))
```

But I recommend against doing that. This from the updated doc-string for `transient-display-buffer-action`:

> Note that the buffer that was current before the transient buffer
> is shown should remain the current buffer.  Many suffix commands
> act on the thing at point, if appropriate, and if the transient
> buffer became the current buffer, then that would change what is
> at point.  To that effect `inhibit-same-window' ensures that the
> selected window is not used to show the transient buffer.
