### ISSUE TITLE
transient-current-command & transient-current-prefix incorrect during body of :transient t suffixes

### ISSUE THREAD

**Issue by psionic-k** [magit/transient#151]
Pulled latest and restarted before submitting.

`transient-current-prefix` and `transient-current-command` set to `nil` before `:transient t` before command executes.  They seem to be correctly set back before subsequent commands.

I made a small demo.  Adding and removing `:transient t` to either command and calling the commands in either order shows that only when invoking a `:transient t` command will the two variables be set to `nil`

```elisp
(transient-define-suffix ikaruga-msg-transient-command ()
  "Show the current transient command"
  (interactive)
  (message (concat (propertize "current prefix command: " 'face 'success)
               (format "%s" transient-current-command))))

(transient-define-suffix ikaruga-msg-transient-prefix ()
  "Show the current transient prefix"
  (interactive)
  (message (concat (propertize "current prefix object: \n" 'face 'success)
                   (with-output-to-string (object-write transient-current-prefix)))))

(transient-define-prefix ikaruga-transient-toy ()
  "Self-modifying introspective transient"
  ["Introspect"
    ; add & remove :transient t to see what I mean
   ("ic" "command" ikaruga-msg-transient-command :transient t)
   ("ip" "pref" ikaruga-msg-transient-prefix :transient t)])
   
(global-set-key (kbd "M-l") 'ikaruga-transient-toy)
```

Set here (and possibly set to nil?)
https://github.com/magit/transient/blob/master/lisp/transient.el#L1962

Unset here
https://github.com/magit/transient/blob/master/lisp/transient.el#L2015-L2026

I believe that conditional block might need to be expanded around those setq statements, but still learning to read this.

### Minor side questions

The `prog1` call seems unnecessary since the `setq` will already always return nil?  
https://github.com/magit/transient/blob/master/lisp/transient.el#L2019
 
Does the magit manual debugging still apply to debugging transient?  I didn't find good entry points on my first edebug digs.

**Comment by tarsius** [comment]
This is intentional and easily worked around, but I cannot make up my mind right now whether it was a good idea to do it like this. (Probably not but I'll have to think about it some more.)

Here `t` means `transient--do-stay` (see `transient--make-predicate-map`), which does not call `transient--export`. `transient--do-call` however does call `transient--export`, so use that as the value of `:transient` instead of `t`.

**Comment by psionic-k** [comment]
Confirmed works.  Thanks!  From an API user standpoint, the intuitive behavioral expectation was that `transient-current-prefix` etc are always useful within a command body and that only `transient--prefix` would potentially be unreliable.  The naive follow-on suggestion is to interpret `:transient t` as `transient--do-call` instead of `transient--do-stay`.

Can close or leave open if it needs to be polished out of the API eventually.  I don't yet understand enough of the behaviors & implementations to suggest a path.

**Comment by tarsius** [comment]
I agree :grinning:
