### ISSUE TITLE
Setting default values for arguments with :choices 

### ISSUE THREAD

**Issue by psionic-k** [magit/transient#154]
Setting prefix `:value` seems to have no effect on arguments with `:choices`

https://github.com/magit/transient/wiki/Developer-Quick-Start-Guide#reading-arguments-into-commands

Expected the default to result in the transient starting with "--flavor=cherry" and "--topping=fruit".  Looks like something isn't supported somewhere.

**Comment by tarsius** [comment]
Tataaaa!
