### ISSUE TITLE
transient and dimmer integration 

### ISSUE THREAD

**Issue by Davidbrcz** [magit/transient#16]
Hi,

I'm sure if this is bug-report or a feature request, feel free to adapt.
I'm using [dimmer](https://github.com/gonewest818/dimmer.el) to dim the non active buffers.
With previous magit version (using magit popup), the popups were dimmed when they hadn't the focus and had full bright when selected.

RIght now, I'm using Magit 20190225.418, Git 2.17.1, Emacs 26.1, gnu/linux and for what I understand, with this new transient mechanism, the popup is display only. 
I have not been able to give it the focus (mouse click, windmove,C-x o, everything is unknown) thus it is always dimmed and it becomes hard to read.

Dimmer has a function to prevent some buffers from being dimmed if the buffer's name matches a regex (Dimmer Exclusion Regexp), but up to now, I haven't been able to make it work as I can't find the name of the popups.

Any help is appreciated !
Thanks.

David

**Comment by Davidbrcz** [comment]
Thanks, excluding this buffer works just fine.
What would be the consequences for this issue to stop relying on the lv package >

**Comment by tarsius** [comment]
The name of the buffer would change; possibly to `" *transient*"`.

**Comment by turnerse** [comment]
See [dimmer.el](https://github.com/gonewest818/dimmer.el#configuration)
"dimmer-configure-magit a convenience function for magit users to ensure transients are not dimmed."

so you can just add this to your config:

(dimmer-configure-magit)
