### ISSUE TITLE
Issues with history when a transient-infix's value is not a string

### ISSUE THREAD

**Issue by gitonthescene** [magit/transient#172]
Using `elpa/transient-20211025.1800` and building a custom infix class which stores `(oref obj value)` as a list I had issues using the history to input values.  I would get `Wrong type argument: char-or-string-p, ("happy")` error messages.

This seems to be from [this line](https://github.com/magit/transient/blob/master/lisp/transient.el#L2544).  This issue is that `value` is being cons-ed to the front of `transient--history` but `transient--history` should be just the history of what was entered by the user (i.e. strings).  I think the point was to use the history to determine the value of `initial-input` on the [next line](https://github.com/magit/transient/blob/master/lisp/transient.el#L2548).

I believe it's better to not manipulate the history directly and leave that entirely up to the `reader`.  The following patch seems to do the trick.

``` elisp
diff --git a/lisp/transient.el b/lisp/transient.el
index d0ba854..a933f35 100644
--- a/lisp/transient.el
+++ b/lisp/transient.el
@@ -2541,12 +2541,11 @@ it\", in which case it is pointless to preserve history.)"
              (history-key (or (oref obj history-key)
                               (oref obj command)))
              (transient--history (alist-get history-key transient-history))
-             (transient--history (if (or (null value)
-                                         (eq value (car transient--history)))
-                                     transient--history
-                                   (cons value transient--history)))
+             (history-head (car transient--history))
              (initial-input (and transient-read-with-initial-input
-                                 (car transient--history)))
+                                 (if (and (not (null value)) (not (eq value history-head)))
+                                     value
+                                   history-head)))
              (history (if initial-input
                           (cons 'transient--history 1)
                         'transient--history))
```

This change does mean that for non-standard `value` types that `initial-input` will **always** come from the head of `transient--history` but that suits my purposes just fine.  I don't know a way around this since this code seems to tie down the type to be only what can be found in the `reader`'s history.  You could make getting the `initial-input` a generic function, but this is not functionality I need.

I believe for other cases the behavior should remain unchanged because there is de-duping of the `transient--history` later on in the function.

Here is the implementation of my new transient option class with a toy transient which makes use of it.  If you choose the `o` option, enter a value and then choose it again and attempt to use the history, you should run into the error.

``` elisp
(require 'dash)
(require 'transient)
(defclass transient-multi-option (transient-option) ()
  "Class used for command-line argument that can take a value.")

(cl-defmethod transient-init-value ((obj transient-multi-option))
  (progn
    (oset obj value nil)
    (oset obj always-read t)))

(cl-defmethod transient-infix-value ((obj transient-option))
  "Return (concat ARGUMENT VALUE) or nil.

ARGUMENT and VALUE are the values of the respective slots of OBJ.
If VALUE is nil, then return nil.  VALUE may be the empty string,
which is not the same as nil."
  (when-let ((value (oref obj value)))
    (--> value
           (reverse it)
           (-map (lambda (x) (concat (oref obj argument) x)) it)
           (mapconcat #'identity it " "))))

(cl-defmethod transient-format-value ((obj transient-multi-option))
  (let ((value (oref obj value)))
    (propertize (or (transient-infix-value obj) (oref obj argument))
                'face (if value
                          'transient-value
                        'transient-inactive-value))))

(cl-defmethod transient-infix-set ((obj transient-multi-option) value)
  "Set the value of infix object OBJ to value."

  (let ((orig (oref obj value)))
    (if (eq value nil)
        (if (not (eq orig nil))
            (oset obj value (cdr orig)))
    (oset obj value (cons value orig)))))
  
(defun doug-interactive ()
  (interactive)
  (message (format "%s" (transient-args current-transient-command)))
  )

(require 'transient)
(transient-define-prefix test-transient ()
  "documentation"
  ["Section header"
   ("o" "Option Description" "--option=" :class transient-multi-option)
   ("r" "Action item" doug-interactive)
   ])
```

**Comment by gitonthescene** [comment]
Can you explain why it’s necessary to modify `transient--history` outside of the reader in this code or is it just a matter of principle that changes won’t be considered?  I thought I gave a pretty technical argument why I thought the code was appropriate.

Writing a new reader to support the separation of the input type (necessarily strings) and the object’s value type seems like an undue burden on the third party developer (especially given this change).  It would simply end up being a fork with this change which would have to track future changes on this large function.

I don’t think I’m likely to continue experimenting if this is the case.

Again, the problem is the modification of `transient--history` not the reader itself.  The code above conforms to the contract with those reader functions.  I would think that hand-editing the input history strays from that contract.

I think you’ve made a wonderful library here which is why I invested my time here.  I think it would be very use for the community at large and am only trying to improve it.  I’m happy to learn if I’ve misunderstood some technical aspect.

**Comment by tarsius** [comment]
Your code above does not produce any error when used with transient's `next` branch. I did not try with `master`.

**Comment by gitonthescene** [comment]
I'm seeing the same behavior from the original post on the `next` branch.
``` sh
$ git --no-pager branch
* next
$ git --no-pager log -n1
commit daa8007565ff704154c848ff2685b35a40301958 (HEAD -> next, origin/next)
Author: Psionik K <73710933+psionic-k@users.noreply.github.com>
Date:   Mon Oct 25 20:53:03 2021 +0800

    Interpret t and nil for sub-prefixes in define-transient-prefix
    
    If a sub-prefix has :transient t, it should recurse (and its suffixes will
    return).  Correspondingly, explicit :transient nil should replace.
$
```
