### ISSUE TITLE
Possible documentation (i.e. docstring) bug in `transient-define-infix`

### ISSUE THREAD

**Issue by dalanicolai** [magit/transient#175]
Again, I am not sure where/how to best inform about this issue, but after really trying/researching to understand the `transient-define-infix` I strongly suspect that there is a bug in the docstring.

Namely, at the end of the docstring, it is mentioned that:

"In rare case the above command function might not be
suitable, even if you define your own infix command class.  In
that case you have to use `transient-suffix-command` to define
the infix command and use t as the value of the `:transient'
keyword."

But I really can not make sense of this. So, in the end, I concluded/am almost sure that you probably mean `transient-define-suffix` here instead of `transient-suffix-command` (of which b.t.w. there only exists a function with a double dash in the name). I guess you can determine very quickly if the docstring is (in)correct indeed.

EDIT I've found that there exists an alias for `transient-define-suffix`, namely `define-suffix-command`, so probably you meant  to write that (instead of `transient-suffix-command`).

**Comment by tarsius** [comment]
Thanks for letting me know!

(And since this is documentation bug, this was the right place to report it. There's always a risk that some bug or missing feature is actually a user error, but I won't bit anyone's head of if they report that as an issue. At least usually I don't. ;)
