### ISSUE TITLE
Transient behaves differently when eval'ed from within emacs or from batch mode (for testing) 

### ISSUE THREAD

**Issue by publicimageltd** [magit/transient#180]
## Settting

I want to test transients in automated tests. I wrote a function which inserts keys non-interactively, simulating keyboard input, using `execute-kbd-macro`. It works fine when I call this function from within Emacs, but not if I put it in a script and call it in batch mode.

## Expected behavior

Since simulating the key sequence does work fine from within Emacs, it should also work when called in a script.

## Observed behavior

I get the message "Quit transient!", which is caused by `transient--post-command` if an error occurs. The transient seems to collapse before any of the key sequences can be read.

## Reproducible code

```emacs-lisp
(defvar return-value nil)

(defun test-transient--store-value ()
  (interactive)
  (push (transient-get-value) return-value))

(transient-define-argument test-transient--switches ()
  :description "Toggle"
  :class 'transient-switches
  :key "t"
  :argument-format "--%s"
  :argument-regexp "\\(--\\(grape\\|orange\\|cherry\\|lime\\)\\)"
  :choices '("grape" "orange" "cherry" "lime"))

(transient-define-prefix test-transient ()
  "Test"
  ["Groupname"
   (test-transient--switches)
   ("p" "store value" test-transient--store-value :transient t)
   ("q" "quit" transient-quit-all)])

(progn
  (setq return-value nil)
  (message "Calling transient")
  (funcall 'test-transient)
  (message "Inserting keys")
  (execute-kbd-macro (kbd "ttpq"))
  (message "Result:%S" return-value))
```

Output within Emacs (per `eval-buffer`):
```
Calling transient
Inserting keys
Result:(("--orange"))
```

Output outside of Emacs (using `eldev emacs --script filename`, but Eldev only loads the libraries for us):
```
Calling transient
Inserting keys
Quit transient!
Result:nil
```
## Relevance

The error occured while writing buttercup tests for a transient. It would be really useful if we could test transients automatically by simulating input. This goes in particular for testing new classes with new behavior, etc., but also for more complex UI cases.

**Comment by tarsius** [comment]
I'll soon merge some major bug fixes. Once that has happened we can check if this issue still occurs.

**Comment by tarsius** [comment]
> `(funcall 'test-transient)`

I don't know if that's enough to get it going, but you'll need to use `call-interactively`.

**Comment by publicimageltd** [comment]
Is this related to changes in `transient.el` since the first post? I am currently busy with non-Emacs things (yep! they exist!), and it will take a while. But I will eventually try and re-implement testing of transients and give feedback if it does not work. You can close this issue or leave it open until I have found time to give feedback, as you like.

BTW thanks for your very impressive engagement, with Magit and all the other conributions to the Emacs ecosystem!

**Comment by tarsius** [comment]
> Is this related to changes in `transient.el` since the first post?

No. Some important work happens in `post-command-hook` and `pre-command-hook`. If you don't use `call-interactively`, then that is bypassed.

> I am currently busy with non-Emacs things

Take your time.

> BTW thanks for your very impressive engagement, with Magit and all the other conributions to the Emacs ecosystem!

Thanks!

**Comment by tarsius** [comment]
> You can close this issue or leave it open until I have found time to give feedback, as you like.

I'll close it for now.
