### ISSUE TITLE
Default value ignores argument's case for transient-option class

### ISSUE THREAD

**Issue by stasvlasov** [magit/transient#181]
Example (Magit v3.3.0-54-g74b84b57, Git 2.34.1, Emacs 27.2, gnu/linux):

``` emacs-lisp
(transient-define-prefix test-def-value-case-sencitivity ()
  :value '("-c value")
  [("c" "Something about 'c'" "-c " :class transient-option)
   ("C" "Something about capital 'C'" "-C " :class transient-option)])

(test-def-value-case-sencitivity)
```

The above sets both `-c value` and `-C value` contrary to what I would expected that it will set only `-c value`  and the capital argument `-C` will have `nil` value.

In case of `transient-switch` class everything works as expected (e.g., it distinguishes between `-c` and `-C` flags).

Could this be a bug?

**Comment by tarsius** [comment]
Thanks for the report!
