### ISSUE TITLE
(transient--post-command): (wrong-type-argument keymapp nil)

### ISSUE THREAD

**Issue by kwist-sgr** [magit/transient#185]
1. `make emacs-Q` in the magit repository
3. `M-x magit-dispatch`
4. press `P` for push (the command doesn't matter)
5. press `-` to select any argument

```
Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
  apply(debug (error (wrong-type-argument keymapp nil)))
  transient--exit-and-debug(error (wrong-type-argument keymapp nil))
  map-keymap-internal(#f(compiled-function (key def) #<bytecode 0x1563eb4b0d91>) nil)
  transient--make-redisplay-map()
  transient--post-command()
```

```
Magit 20220107.915 [>= 3.3.0], Git 2.25.1, Emacs 27.2, gnu/linux
```

**Comment by tarsius** [comment]
Please do `M-x find-library transient`, then `M-x eval-buffer` and then these steps again. That should give a more detailed backtrace. Also if you are not sure if you have restarted Emacs since last updating `transient`, then try that first.

**Comment by kwist-sgr** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
  apply(debug (error (wrong-type-argument keymapp nil)))
  transient--exit-and-debug(error (wrong-type-argument keymapp nil))
  map-keymap-internal((closure ((submap keymap keymap (7 . transient-quit-seq) keymap (prior . transient-scroll-down) (next . transient-scroll-up) (22 . transient-scroll-up) (26 . transient-suspend) (17 . transient-quit-all) (7 . transient-quit-one) (27 keymap (22 . transient-scroll-down) (27 keymap (27 . transient-quit-all)))) (topmap keymap (kp-subtract keymap keymap (7 . transient-quit-seq) keymap (prior . transient-scroll-down) (next . transient-scroll-up) (22 . transient-scroll-up) (26 . transient-suspend) (17 . transient-quit-all) (7 . transient-quit-one) (27 keymap (22 . transient-scroll-down) (27 keymap (27 . transient-quit-all))))) Man-notify-method t) (key def) (if (and (not (eq key 27)) (listp def) (keymapp def)) (progn (define-key topmap (vconcat transient--redisplay-key (list key)) #'transient-update)))) nil)
  (let ((topmap (make-sparse-keymap)) (submap (make-sparse-keymap))) (if transient--redisplay-key (progn (define-key topmap (vconcat transient--redisplay-key) submap) (set-keymap-parent submap transient-sticky-map))) (map-keymap-internal #'(lambda (key def) (if (and (not (eq key 27)) (listp def) (keymapp def)) (progn (define-key topmap (vconcat transient--redisplay-key ...) #'transient-update)))) (if transient--redisplay-key (lookup-key transient--transient-map (vconcat transient--redisplay-key)) transient--transient-map)) topmap)
  transient--make-redisplay-map()
  (let ((old transient--redisplay-map) (new (transient--make-redisplay-map))) (if (equal old new) nil (transient--pop-keymap 'transient--redisplay-map) (setq transient--redisplay-map new) (transient--push-keymap 'transient--redisplay-map)))
  (cond ((and (eq (this-command-keys-vector) []) (= (minibuffer-depth) (1+ transient--minibuffer-depth))) (transient--suspend-override) (transient--delay-post-command)) (transient--exitp (transient--post-exit)) ((eq this-command (eieio-oref transient--prefix 'command))) (t (let ((old transient--redisplay-map) (new (transient--make-redisplay-map))) (if (equal old new) nil (transient--pop-keymap 'transient--redisplay-map) (setq transient--redisplay-map new) (transient--push-keymap 'transient--redisplay-map))) (transient--redisplay)))
  (let ((debugger #'transient--exit-and-debug)) (cond ((and (eq (this-command-keys-vector) []) (= (minibuffer-depth) (1+ transient--minibuffer-depth))) (transient--suspend-override) (transient--delay-post-command)) (transient--exitp (transient--post-exit)) ((eq this-command (eieio-oref transient--prefix 'command))) (t (let ((old transient--redisplay-map) (new (transient--make-redisplay-map))) (if (equal old new) nil (transient--pop-keymap 'transient--redisplay-map) (setq transient--redisplay-map new) (transient--push-keymap 'transient--redisplay-map))) (transient--redisplay))))
  (condition-case err (let ((debugger #'transient--exit-and-debug)) (cond ((and (eq (this-command-keys-vector) []) (= (minibuffer-depth) (1+ transient--minibuffer-depth))) (transient--suspend-override) (transient--delay-post-command)) (transient--exitp (transient--post-exit)) ((eq this-command (eieio-oref transient--prefix 'command))) (t (let ((old transient--redisplay-map) (new (transient--make-redisplay-map))) (if (equal old new) nil (transient--pop-keymap 'transient--redisplay-map) (setq transient--redisplay-map new) (transient--push-keymap 'transient--redisplay-map))) (transient--redisplay)))) ((debug error) (transient--emergency-exit) (signal (car err) (cdr err))))
  transient--post-command()
```

**Comment by tarsius** [comment]
I still cannot reproduce it; even tried with 27.2, just in case.

Sometimes when a library is modified heavily, then packages that were compiled using the old version have to be recompiled after installing the new version. Not sure what change might make that necessary here but please give it a try:

1. Uninstall `magit` and exit Emacs.
2. Start Emacs and install `magit` again.

**Comment by kwist-sgr** [comment]
Here is what I [found out](https://github.com/magit/transient/blob/master/lisp/transient.el#L1732:L1734):

| Expression/variable | Value |
|-|-|
| `transient--redisplay-key` | `(kp-subtract)` |
| `transient--transient-map` | `(keymap (26 . transient-suspend) (17 . transient-quit-all) (7 . transient-quit-one) (24 keymap (108 . transient-set-level) (116 . transient-toggle-common) (110 . transient-history-next) (112 . transient-history-prev) (11 . transient-reset) (19 . transient-save) (115 . transient-set)) (67 . magit-branch-configure) (116 . magit-push-tags) (84 . magit-push-tag) (109 . magit-push-matching) (114 . magit-push-refspecs) (111 . magit-push-other) (101 . magit-push-current) (117 . magit-push-current-to-upstream) (112 . magit-push-current-to-pushremote) (45 keymap (110 lambda nil (interactive) (let ((obj (transient-suffix-object))) (transient-infix-set obj (transient-infix-read obj))) (transient--show)) (104 lambda nil (interactive) (let ((obj (transient-suffix-object))) (transient-infix-set obj (transient-infix-read obj))) (transient--show)) (70 lambda nil (interactive) (let ((obj (transient-suffix-object))) (transient-infix-set obj (transient-infix-read obj))) (transient--show)) (102 lambda nil (interactive) (let ((obj (transient-suffix-object))) (transient-infix-set obj (transient-infix-read obj))) (transient--show))) keymap (27 keymap (14 . transient-history-next) (16 . transient-history-prev)) (8 . transient-help) (63 . transient-help) (20 . transient-show) (67108909 . negative-argument) (21 . universal-argument) keymap (prior . transient-scroll-down) (next . transient-scroll-up) (22 . transient-scroll-up) (26 . transient-suspend) (17 . transient-quit-all) (7 . transient-quit-one) (27 keymap (22 . transient-scroll-down) (27 keymap (27 . transient-quit-all))))` |
| `(vconcat transient--redisplay-key)` | `[kp-subtract]` |
| `(lookup-key transient--transient-map (vconcat transient--redisplay-key))` | `nil` |

**Comment by tarsius** [comment]
> kp-subtract

I think that is the minus key on the keypad. Did you actually press that key?

**Comment by kwist-sgr** [comment]
> I think that is the minus key on the keypad. Did you actually press that key?

Yes :) Until the last changes, it worked.
If this behavior is no longer supported, can you fix it to display a standard message `Unbound suffix ...` when pressing the keypad minus?
If this behavior is no longer supported, can you fix it?

**Comment by tarsius** [comment]
This might fix it

```diff
diff --git a/lisp/transient.el b/lisp/transient.el
index 8764d4db..90d4d295 100644
--- a/lisp/transient.el
+++ b/lisp/transient.el
@@ -1730,7 +1730,12 @@ (defun transient--make-redisplay-map ()
          (define-key topmap (vconcat transient--redisplay-key (list key))
            #'transient-update)))
      (if transient--redisplay-key
-         (lookup-key transient--transient-map (vconcat transient--redisplay-key))
+         (or (lookup-key transient--transient-map (vconcat transient--redisplay-key))
+             (and (symbolp transient--redisplay-key)
+                  (when-let ((key (get transient--redisplay-key 'ascii-character)))
+                    (setq transient--redisplay-key key)
+                    (lookup-key transient--transient-map
+                                (vconcat transient--redisplay-key)))))
        transient--transient-map))
     topmap))
```

I  cannot try because my keyboard doesn't have that key.

**Comment by tarsius** [comment]
Also try:

```diff
diff --git a/lisp/transient.el b/lisp/transient.el
index 8764d4db..59562231 100644
--- a/lisp/transient.el
+++ b/lisp/transient.el
@@ -1730,7 +1730,10 @@ (defun transient--make-redisplay-map ()
          (define-key topmap (vconcat transient--redisplay-key (list key))
            #'transient-update)))
      (if transient--redisplay-key
-         (lookup-key transient--transient-map (vconcat transient--redisplay-key))
+         (let ((key (vconcat transient--redisplay-key)))
+           (or (lookup-key transient--transient-map key)
+               (when-let ((normal (lookup-key local-function-key-map key)))
+                 (lookup-key transient--transient-map (vconcat normal)))))
        transient--transient-map))
     topmap))
```

**Comment by kwist-sgr** [comment]
The first patch didn't work. But the second one no longer falls (a transient buffer didn't close)
```
Unbound suffix: ‘<kp-subtract> f’ (Use ‘C-g’ to abort, ‘?’ for help) [nil]
```

**Comment by tarsius** [comment]
I'll have to look into this more. Maybe its possible to support alternative bindings such as this that have a binding in `local-function-key-map` with reasonable effort. For now I am leaving things as they are... remember not to press that key until I have made some changes. :/

**Comment by gahag-cw** [comment]
I just updated magit/transient and got this issue. As the only `-` in my keyboard is in the keypad, there is no workaround for me for now :/

**Comment by tarsius** [comment]
As a temporary workaround, adding something to `transient-substitute-key-function` should do the trick.

**Comment by kwist-sgr** [comment]
Thanks, Jonas!

**Comment by tarsius** [comment]
You are welcome. Sorry it took so long.
