### ISSUE TITLE
Cannot invoke `magit-branch-configure` with `b C` when installed from MELPA

### ISSUE THREAD

**Issue by peniblec** [magit/transient#187]
Hello!

I'm not sure if this one belongs in Magit's issue tracker, transient's, or if I'm just missing something.

On Emacs 29.0.50 (1d3020908b4e4ff398c3faed9321aa4932fbaad1), starting with `HOME=$(mktemp -d) emacs` to get a fresh `.emacs.d`, from a directory tracked by Git:

```
M-x package-install magit   ; NB: this installs magit *and reinstalls transient* from NonGNU ELPA.
M-x magit-status
b C RET
```

⇒ This last command brings up the `magit-branch-configure` transient, the one with e.g. the "Configure repository defaults" section including `("R" magit-pull.rebase)` and `("P" magit-remote.pushDefault)`.

Now, starting over from `HOME=$(mktemp -d) emacs`:

```
M-: (require 'package)
M-: (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
M-x package-refresh-contents
M-x package-install magit       ; NB: this reinstalls transient from MELPA.
M-x magit-status
b C RET
```

⇒ Now `b C RET` seems to bring up the `magit-branch` transient.  Invoking `M-x magit-branch-configure` still brings up the correct transient.

(This persists after restarting Emacs)

After deleting `$HOME/.emacs.d/elpa/transient*` (to ensure we use the built-in `transient.el`) and restarting Emacs (with this same temporary `$HOME`), `b C RET` brings up the `magit-branch-configure` as expected.

Let me know if I can do anything to debug this further!

**Comment by tarsius** [comment]
This fixes it, but I'll have to think that through before I commit it:

```diff
diff --git a/lisp/transient.el b/lisp/transient.el
index 356c81a4..59cbdf31 100644
--- a/lisp/transient.el
+++ b/lisp/transient.el
@@ -2140,8 +2140,9 @@ (defun transient--post-command ()
      ((and (eq (this-command-keys-vector) [])
            (= (minibuffer-depth)
               (1+ transient--minibuffer-depth)))
-      (transient--suspend-override)
-      (transient--delay-post-command))
+      (unless (eq transient--exitp 'replace)
+        (transient--suspend-override)
+        (transient--delay-post-command)))
      (transient--exitp
       (transient--post-exit))
      ((eq this-command (oref transient--prefix command)))
```

**Comment by peniblec** [comment]
> I'll have to think that through before I commit it:

This goes without saying, but still: zero rush, as far as I am concerned!

**Comment by peniblec** [comment]
Fix confirmed; thanks!
