### ISSUE TITLE
transient-lisp-variable class doesn't accept functions for `:description` slot

### ISSUE THREAD

**Issue by SreenivasVRao** [magit/transient#188]
Please explain
    (1) what behavior you expected
`:description` for a `transient-lisp-variable` should be dynamically updated if it's a function which returns a string.
The two descriptions should be the same because they are the same function in the screenshot below
    (2) what behavior you observed
![image](https://user-images.githubusercontent.com/18532038/151635122-240a0914-1f74-41df-8d78-bf828988f62b.png)
    (3) and how we can reproduce the issue.
https://pastebin.com/0E2T5BRD with `Emacs -q -l`

`Magit 0ac05f3, Git 2.30.2, Emacs 28.0.90, darwin`

**Comment by tarsius** [comment]
```elisp
;;; demo.el --- Description -*- lexical-binding: t; -*-

(setq native-comp-async-report-warnings-errors nil) ;; hacky way to quieten native-comp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'transient)
(require 'transient)
(defvar run-locally-flag nil)

(defun run-locally-flag-reader (prompt initial-input _history)
"Helper function to read the value of `amz-brief--run-locally-flag'"
  (not run-locally-flag))

(defun test()
  ""
  "Something worked")

(transient-define-argument toggle-run-locally-flag()
  ""
  :description #'test
  :class 'transient-lisp-variable
  :shortarg "l"
  :variable 'run-locally-flag
  :argument "RUN_LOCALLY"
  :reader 'run-locally-flag-reader)

(transient-define-argument configure-package ()
  "Choose the Brazil package to run a command in.
Choices are restricted to known packages in the Brazil workspace."
  :description #'test
  :class 'transient-option
  :shortarg "p"
  :argument "--package="
  :always-read t) ;; don't unset - always pick from choices


(transient-define-prefix demo ()
  "Entry point for all commands supported by Brief"
  ["Flags"
    ("l" toggle-run-locally-flag)
    ("p" configure-package)])

(demo)
```

**Comment by tarsius** [comment]
The `transient-lisp-variable` is experimental. It is already useful but I expect to extend it over time. I don't plan to work on it soon.

The code that handles this for this class is:

```elisp
(cl-defmethod transient-format-description ((obj transient-lisp-variable))
  (or (oref obj description)
      (symbol-name (oref obj variable))))
```

This makes it possible to use this class for a variable that shares the name with a function. If this did instead check if the value of the description slot is a function and then call that to get the description string, as it is done for other classes, then that this class would could not be use for any minor-modes for example.

Of course we could add a special case and not call `description` function if and only if it is the same symbol as `variable`. But there might be more complications down that line.

For now I am keeping this class as simple as possible and want to stick to that. You can however define a derived class and define the `transient-format-description` to add that special case or something else.

**Comment by tarsius** [comment]
Fixed! Thanks for the report.
