### ISSUE TITLE
New release :-)

### ISSUE THREAD

**Issue by Silex** [magit/transient#190]
Hello!

In docker.el ([#193](https://github.com/Silex/docker.el/issues/193)) our newly installed CI fails on MELPA stable (https://github.com/Silex/docker.el/actions/runs/1941613092) because we're using `transient-default-value` which was added after the most recent transient release.

I'm not sure how MELPA stable is able to build the package but that's another story :smile:

**Comment by Silex** [comment]
@tarsius: friendly ping

**Comment by Silex** [comment]
@tarsius: less friendly ping? :laughing:

**Comment by tarsius** [comment]
"Probably soon" :stuck_out_tongue:

**Comment by Silex** [comment]
Pingety ping :-)

**Comment by tarsius** [comment]
Right now I am working on some significant changes requested by Stefan Monnier.

These requests increase my anxiety. Stop it.
