### ISSUE TITLE
option to always have transient-switches return a value

### ISSUE THREAD

**Issue by Dickby** [magit/transient#201]
I try to have an transient-infix that is never empty. So it always has one switch active.
I know you achieve that functionality in magit's transients e.g. the pull transient
has it in the branch.master.rebase infix that has the switches [true|false|default:false].
But this is done by using custom classes.
Is there a way to make transient-switches classes behave that way?
It would make things a lot easier.
Thanks

**Comment by tarsius** [comment]
Might be a while until I get to that.

**Comment by Dickby** [comment]
Thanks

**Comment by tarsius** [comment]
I am currently implementing some of those little nice to have features that have accumulated. In this case, I could not come up with a case where the requested feature would be useful. I am not implementing this just yet, cause adding flexibility for its own sake does have and accumulating cost, and if the feature ends up never being used, that is a net negative.

For now at least, I am closing this, but I am still open to the idea in principal -- but I need a *concrete* example of when this would be useful.

You mentioned implementing this for `transient-switches` but I have a hunch that it might be more useful for `transient-option`.
