### ISSUE TITLE
Persist "show popup" until user exits the entire tree 

### ISSUE THREAD

**Issue by celebrimbor379** [magit/transient#202]
I have a number of commands that I execute pretty frequently and thus do not usually need to the popup buffer to open, so I set `transient-show-popup` to `0`. Then when I need to execute a command I'm less familiar with, I can hit `C-t` to show the popup buffer and browse all the different options, and this is great.

However, if I then execute a command that moves to a sub-prefix (or hit `C-g` and move back to the parent prefix), the popup is hidden again and I need to press `C-t` every time I move to a new transient in the tree. I would like to suggest that a more natural user experience would be pressing `C-t` once to open the popup buffer, and leave it open if the user navigates to another transient (i.e. doesn't leave the tree).

I was able to hack around this for my purposes by moving the cleanup of `transient--showp` from `transient--pre-exit` to `transient--stack-zap` so that it is only cleaned up when the stack is unwound, but I am pretty new to transient and am not sure if this is best way to do it:

```elisp
(advice-add 'transient--pre-exit :around (lambda (f)
                                           (let ((prev-showp-val transient--showp))
                                             (funcall f)
                                             (setq transient--showp prev-showp-val))))
(advice-add 'transient--stack-zap :after (lambda ()
					   (setq transient--showp nil)))
```
A related observation is that it might be beneficial to provide a hook that runs only when the whole tree is exited.

Thank you for all the work on transient, it is a great package!

**Comment by tarsius** [comment]
The popup is now shown until a complete exit.

> A related observation is that it might be beneficial to provide a hook that runs only when the whole tree is exited.

True, but I will probably wait for someone to report their use-case before I do so. (But I've just implemented it on the `idea` branch.)

**Comment by celebrimbor379** [comment]
Works perfectly, thank you!
