### ISSUE TITLE
error: one of my transients misplaces cursor activity

### ISSUE THREAD

**Issue by WorldsEndless** [magit/transient#207]
magit-version: Magit v3.3.0-402-gacd26dd9, Git 2.36.1, Emacs 28.1, gnu/linux

### (1) what behavior you expected

When I use a transient with these suffixes:

```lisp
:transient-non-suffix 'transient--do-quit-one
:transient-suffix 'transient--do-stay  
```

I expect to be able to continue using transient commands regardless of what buffer-switches are occurring above the transient.

### (2) what behavior you observed

After executing a buffer-switching command within my transient, such as find-file, the transient remains visible but no longer has focus and cannot be used/switched to.

### (3) and how we can reproduce the issue.

Attempt one of the following misbehaving commands:

```lisp
  ;; this is bound to <f2>
     (transient-define-prefix tsa/transient-window ()
       "Window navigation transient"
       :transient-non-suffix 'transient--do-quit-one
       :transient-suffix 'transient--do-stay  
       [["Switch"
         ("b" "buffer" switch-to-buffer) ;; FOCUS MISBEHAVIOR
         ("f" "find-file" find-file) ;; FOCUS MISBEHAVIOR
]
         ])
```

## Explanation

One of my transients has recently changed behavior, and is very bothersome. Normally I would use it to choose a file from the project and then, with the transient menu staying open after visiting the file, I can press the another transient key and do that thing. But no more.

Now, after visiting a file, it looks the same as before &#x2013; meaning, the transient stays open at the bottom of the screen &#x2013; but my cursor has now moved to the file itself and attempting to press one of the transient keys just inserts that character into the buffer, as if transient wasn't there. I then usually hav to get rid of the inaccessible transient menu by calling another transient and cancelling it immediately, after which my screen has returned to full no-transient normal. And there is no way to resume my old ideal work-flow in which I can stay in the transient, consecutively changing buffers/finding files.

Why would this one command be now causing my transient to lose focus without visibly exiting?

Code:

```lisp
;; this is bound to <f2>
   (transient-define-prefix tsa/transient-window ()
     "Window navigation transient"
     :transient-non-suffix 'transient--do-quit-one
     :transient-suffix 'transient--do-stay  
     [["Switch"
       ("b" "buffer" switch-to-buffer) ;; FOCUS MISBEHAVIOR
       ("f" "find-file" find-file) ;; FOCUS MISBEHAVIOR
       ("p" "projectile" tsa/projectile) ;; FOCUS MISBEHAVIOR
       ("g" "git-grep" consult-git-grep)
       ("F" "follow" follow-mode)
       ("a" "ace 1" transient-ace-cmd)]
       ])
```

### Suffix problems?

I have found that changing functions, or even using a completely different function in this transient, has the same problem. For instance, it's the same thing with a transient key for \`find-file\`: upon finding one, the transient menu is still visible but is not actually active or usable. This indicates that it might me my suffix settings at the top:

```lisp
:transient-non-suffix 'transient--do-quit-one
:transient-suffix 'transient--do-stay  
```

I am trying (with difficulty) to comb the documentation to see what might have changed there.

### Resources

<https://www.reddit.com/r/emacs/comments/w41f9j/comment/igzqm6r>

**Comment by tarsius** [comment]
As mentioned in that reddit thread I think the problem is that you are using an old version of transient, and I am taking a break. Never-the-less I have tried to reproduce this, but can't, which reinforce my suspicion that the problem is an outdated transient (which was known to have such bugs).

**Comment by t-e-r-m** [comment]
Could this issue be re-opened?  I have the same issue.

Please try running the following:

```lisp
(defun tmwe-locate-git-file ()
  "locate the nearest .git file upwards"
  (locate-dominating-file "." ".git"))

(defun tmwe-unquote (exp) ;; copied from doom-unquote
  "Return EXP unquoted."
  (declare (pure t) (side-effect-free t))
  (while (memq (car-safe exp) '(quote function))
    (setq exp (cadr exp)))
  exp)

(defun tmwe-dirlist-invocation ()
  (concat "fdfind "
          "-c never -t d "
          "--base-directory "
          (locate-dominating-file "." ".git")))

(defun tmwe-completing-read ()
  "Make sure you are in a vc root!"
  (completing-read "select something> "
                   (tmwe-unquote
                    (split-string
                     (shell-command-to-string (tmwe-dirlist-invocation))
                     "\n"))))

(transient-define-prefix tmwe ()
  "Transient MWE for Focus Loss"
  :transient-non-suffix 'transient--do-quit-one
  :transient-suffix 'transient--do-stay
  [[
    ("f" "find-file"
     (lambda () (interactive)
       (find-file (concat
                   (locate-dominating-file "." ".git")
                   (file-name-as-directory (tmwe-completing-read))))))
    ]])
```
This works just fine in commit `51c50d8c828b5fac2878b651e2188ad0c6f44184` (which I've been using for a very long time).

I have other functions that use `save-excursion` and `save restriction` to edit other files (opened with `find-file`) that fail similarly with commits after `51c50`.

**Comment by WorldsEndless** [comment]
announcement of Transient's major version upgrade recently prompted me to revisit this issue. It's fixed! My transient now sticks around for the process of jumping to a file and then using the same transient to navigate to an adjoining file. Just a second witness that this is solved. Thanks!
