### ISSUE TITLE
transient--describe-function is too fragile

### ISSUE THREAD

**Issue by DamienCassou** [magit/transient#208]
`transient--describe-function` is the function called when pressing <key>?</key> in a transient. Here is how `transient--describe-function` is implemented:

```
(defun transient--describe-function (fn)
  (describe-function (if (symbolp fn) fn 'transient--anonymous-infix-argument))
  (select-window (get-buffer-window (help-buffer))))
```

The first line opens the documentation for the `FN` argument and the second one makes the documentation visible. The second line relies on the fact that `(help-buffer)` is the name of just opened help buffer. 

This won't work if the user has hooks to rename help buffers automatically based on what they document. This is what [epithet](https://github.com/oantolin/epithet/) does automatically but the user might have defined similar hooks. What happens is that `(get-buffer-window (help-buffer))` returns nil which is not a proper argument to pass to `select-window`.

Is it the responsibility of transient to select the help window? I would say the responsibility of transient is only to call `describe-function` and the rest should be left to the user. As a result, I would just keep the first line.

/CC @oantolin

**Comment by Patryk27** [comment]
> The second line relies on the fact that (help-buffer) is the name of just opened help buffer.

The second line calls a function `help-buffer` that:
```
Signature
(help-buffer)

Documentation
Return the name of a buffer for inserting help.
```
... so if someone has some hooks renaming those buffers, it should either get picked by that function or the hook should get adjusted, so that it composes with that function, no? 👀

**Comment by DamienCassou** [comment]
> ... so if someone has a hook renaming that buffer, the renamed-name should either get picked by that function or the hook should get adjusted, so that it composes with help-buffer, no?

I agree it would seem logical and reasonable. Nevertheless, `help-buffer` function is supposed to return the name of *the* help buffer. If you have several ones (which is one of my goals when using epithet), this function stops making sense completely: which buffer would be returned by `help-buffer`? It can't be the *current one* because `describe-function` doesn't switch or return the new buffer. It could be the *last one* but it would feel weird to me.
