### ISSUE TITLE
Allow byte compiled elisp to define transients without loading transient.el

### ISSUE THREAD

**Issue by jakanakaevangeli** [magit/transient#211]
Looking at a simple transient command definition such as
```elisp
(require 'transient)
(transient-define-prefix hello-world ()
  "Say hello"
   [("t" "tetris" tetris)])
```
we can see that it currently macroexands into
```elisp
(progn
  (defalias 'hello-world
    (lambda nil
      (interactive)
      (transient-setup 'hello-world)))
  (put 'hello-world 'interactive-only t)
  (put 'hello-world 'function-documentation "Say hello")
  (put 'hello-world 'transient--prefix
       (transient-prefix :command 'hello-world))
  (put 'hello-world 'transient--layout
       '([1 transient-column nil
            ((1 transient-suffix
                (:key "t" :description "tetris" :command tetris)))])))
```

At a first glance, it seems that if we auto-loaded `transient-setup` and
arranged for `transient-prefix` to be called at macro expansion time, we could
make it possible to defer loading of transient.el until the first time user
executes `hello-world`. That is, we could put `(require 'transient)` inside an
`(eval-when-compile ...)` form.

My question is, is it possible, and would it work for more complex transient
prefixes as well?

Another question is, is it worth the effort? Most commonly, transient prefix
commands are auto-loaded themselves and the benefit of auto-loading
transient.el for such commands is none. On the other hand. it would be
beneficial for commands defined in the user's `.emacs.el` or for packages that
define a lot of auto-loaded non-transient commands and only a few auto-loaded
transient prefixes.

**Comment by tarsius** [comment]
I gave it a try, but it doesn't seem possible. `transient-prefix` is a class and while that can be autoloaded, once it is called as the above expansion does at load-time, the file that defines the class has to be loaded.

<details>
<summary>Init file used to verify that in an otherwise empty --init-directory.</summary>

```elisp
;; -*- lexical-binding:t -*-

(add-to-list 'load-path "~/.config/emacs/lib/transient/lisp/")
(add-to-list 'load-path "~/.config/emacs/lib/compat/")

(load "~/.config/emacs/lib/transient/lisp/transient-autoloads.el")

;; (require 'transient)

(message "A: %s" (featurep 'transient))

(transient-define-prefix hello-world ()
  "Say hello"
  [("t" "tetris" tetris)])

;; That is enough to trigger the library to be loaded:
;; (transient-prefix :command 'hello-world)

(message "B: %s" (featurep 'transient))
```

</details>
