### ISSUE TITLE
Can't decrease frame width through transient

### ISSUE THREAD

**Issue by ilupin** [magit/transient#216]
Steps to reproduce:
1. `emacs -Q -l ~/.emacs.d/elpa/transient-20220918.2101/transient.el`
2. Eval the following code:
```
(transient-define-prefix test ()
  [("w" "set width" (lambda () (interactive) (set-frame-width nil (1- (frame-width)))) :transient t)])
```
3. `M-x test` and press w ==> the frame width should be reduced, but it is not changed.

The problem disappears if `:transient t` is deleted from the code. The emacs version is `GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)`.

**Comment by tarsius** [comment]
The thin line displayed between the popup and the echo-area is the problem. To draw such a line one has to extend the last character to the edge of the window/frame.

> None of these three functions will make a frame smaller than needed
> to display all of its windows together with their scroll bars, fringes,
> margins, dividers, mode and header lines.  This contrasts with requests
> by the window manager triggered, for example, by dragging the external
> border of a frame with the mouse.

This applies to the line; it effectively sets the current width as the minimal width.

If you only need this for your own use you could `(setq transient-mode-line-format nil)`. If you use it in a package, you should temporarily set the `min-width` frame parameter around the call to `set-frame-width`.

**Comment by ilupin** [comment]
Thank you! `(setq transient-mode-line-format nil)` doesn't work for me, but setting the `min-width` frame parameter works.
