### ISSUE TITLE
Expanding to vector syntax broke my transients.

### ISSUE THREAD

**Issue by agzam** [magit/transient#219]
ea851f3bde0b769b04ad03ab1a1341c013d0ddc6 breaks my transients that I use to build the vectors imperatively, e.g., 

```
(transient-define-prefix tab-bar-transient ()
  "Layouts"
  ["Layouts\n"
   [("k" "prev" tab-bar-switch-to-prev-tab)
    ("j" "next" tab-bar-switch-to-next-tab)
    ("<" "move left" +tab-bar-tab-move-left :transient t)
    (">" "move right" +tab-bar-tab-move-right :transient t)
    ("b" "move buffer to tab" +tab-bar-move-buffer-to-tab)
    ("f" "find tab with current buffer" +tab-bar-find-buffer-in-tabs)
    ("w" "move window to new tab" tab-bar-move-window-to-tab)]]

  [:hide always ,@(seq-map
                   (lambda (n)
                     (let ((snum (number-to-string n)))
                       `(,snum ,(format "Goto: %s" n)
                         (lambda ()
                           (interactive)
                           (+tab-bar-switch-to-tab-number ,n)))))
                   (number-sequence 1 9))])
```

It breaks the second part, under `:hide` key. Basically, it assigns number keys from 1 to 9 to function calls that get called passing the selected number.

This construct and alike don't work anymore. Can you please guide me how to rewrite it so it's compatible with the new format, thank you.

**Comment by tarsius** [comment]
You should use the `:setup-children` function of the group to create dynamic children. Documented in https://magit.vc/manual/0.3.4/transient/Group-Specifications.html. Also see https://git.sr.ht/~tarsius/notmuch-transient/tree/757ee082a2228e70151468f049eee2f14ed1e8d2/item/notmuch-transient.el#L270-286,294-310 for an example.

**Comment by agzam** [comment]
I'm sorry Jonas. I've been trying to get it right, already spent over 40 minutes and I still can't figure it out. The example you pointed to is a bit convoluted. I tried examining notmuch-search-transient--setup body, it looks like it returns a list that looks like this:

```
((list 1 'transient-suffix
       (list :key "i" :description "inbox" :command 'transient:notmuch-search-transient:inbox))
 (list 1 'transient-suffix
       (list :key "f" :description "flagged" :command 'transient:notmuch-search-transient:flagged))
 (list 1 'transient-suffix
       (list :key "s" :description "sent" :command 'transient:notmuch-search-transient:sent))
 (list 1 'transient-suffix
       (list :key "d" :description "drafts" :command 'transient:notmuch-search-transient:drafts)))
```

And I have no idea why it has to be in that kind of structure.

So, I tried replicating the thing for a trivial case of just a single key. Did something like this:

```
,,, 
:setup-children tab-bar-transient--number-keys

(defun tab-bar-transient--number-keys (x)
  (list
   (list
    1
    'transient-suffix
    (list
     :key "1" :description "go to first"
     :command '+tab-bar-switch-to-tab-number))))
```

And that seems to be working, but for my case, I need to pass an argument to `+tab-bar-switch-to-tab-number` and I can't figure that out. Turning it into lambda doesn't work. Adding :argument key doesn't work either. How do I do that?

**Comment by tarsius** [comment]
Here's how I would do it:

```elisp
(transient-define-prefix tab-bar-transient ()
  [:setup-children
   (lambda (_)
     (transient-parse-suffixes
      'tab-bar-transient
      (mapcar (lambda (n)
                (list (number-to-string n)
                      (format "Goto: %s" n)
                      'tab-bar-go))
              (number-sequence 1 9))))])

(defun tab-bar-go ()
  (interactive)
  (message "Going to %s" (oref (transient-suffix-object) :key)))
```

**Comment by agzam** [comment]
Even though it took a while, I enormously appreciate and thank you from the bottom of my heart for the explanation. I can finally update transient.el to the latest, greatest version.

I really like this package, and I am very happy to see many package authors using it. Forgive me if this sounds like a complain but its API definitely not easy to grasp. It would be great to add some good examples of different transients to the documentation. 

Here's for example how I use it with a list of predefined frame layouts to quickly place Emacs frame somewhere on the screen.

```
(transient-define-prefix frame-zoom-transient ()
  "Frame Zoom"
  ["Frame Text Zoom"
   ,,,
   ;; a few groups for manipulating the frame, 
   ;; not important in the context of this GH comment
   ]
  [:hide always
   :setup-children
   (lambda (_)
     (transient-parse-suffixes
      'frame-zoom-transient
      (seq-map-indexed
       (lambda (geom idx)
         (list (number-to-string (1+ idx))
               (format "Layout %s" (1+ idx))
               (lambda ()
                 (interactive)
                 (place-frame-at-display-spot geom))
               :transient t))
       ;; list of pre-sets for different positions of Emacs frame on the
       ;; screen. Each pre-set is a list of X, Y, WIDTH, and HEIGHT.
       ;;
       ;; When a value is a decimal - it represents the discrete pixel
       ;; position on the display. Also, the numbers can be floats, in that
       ;; case - it represent the proportional value, e.g., width of 0.25
       ;; means quarter of `(display-pixel-width)'.
       '((0 0 0.332 1.0)
         (0 0 0.498 1.0)
         (0 0 0.664 1.0)
         (0 0 0.830 1.0)
         (0.166 0 0.664 1.0)
         (0.332 0 0.8 1.0)
         (0.5 0 0.5 1.0)
         (0.664 0 0.35 1.0)))))])
```

It assigns keys from 1 to N (number of layout specs) and moves the frame using `#'place-frame-at-display-spot` (my custom fn). And since there's no point of displaying every key from 1 to N, the group stays hidden.

*this explanation of course, is not meant for you @tarsius, just for posterity*

**Comment by agzam** [comment]
Just fyi, @tarsius, 0204a2432862aa187745995f1c378e6d875b35cb breaks the above snippet. I'm not sure what to change in my code to make it work again. For now, I just pined on the previous commit.
