### ISSUE TITLE
Broken example on latest version

### ISSUE THREAD

**Issue by haji-ali** [magit/transient#220]
I just updated the latest version of transient and the following example

```lisp
(transient-define-prefix transient-toys-wave ()
  "Wave at the user"

  [["More Arguments"
    ("I" "argument with inline" ("-i" "--inline-shortarg="))
    ("-f" "argument with forced class" "--forced-class " :class transient-option)]]

  ["Commands"
   ("ws" "wave some" transient-toys--wave)])
```

gives the error `(invalid-function 'transient-option)`.

I believe this was introduced by ea851f3bde0b769b04ad03ab1a1341c013d0ddc6. In particular, https://github.com/magit/transient/blob/afb7b250d4ee9669fdb82c4e40a23800f651ff96/lisp/transient.el#L1130

quotes the value of the class argument which then fails when passed as an argument to `apply`.

**Comment by tarsius** [comment]
Fixes with e88f51d6922b652b9ccb8a786c57ef3475439a94.
