### ISSUE TITLE
Multiple options with the same shortarg

### ISSUE THREAD

**Issue by haji-ali** [magit/transient#221]
I am not sure this is a "bug" per se, but it was certainly an unexpected behavior. In this example:

```lisp
(defun transient-toys--wave ()
  "Wave at the user"
  (interactive)
  (message (propertize
            (format "Waves at %s" (current-time-string))
            'face 'success)))

(transient-define-prefix transient-toys-wave ()
  "Wave at the user"

  :init-value
  (lambda (obj)
    (oset obj value (list "-otoy=A")))

  [("x" "Toy option" "-otoy"
    :class transient-option
    :always-read t)
   ("x" "Extra options" "-o"
    :class transient-option
    :always-read t)]

  ["Commands"
   ("ws" "wave some" transient-toys--wave)])

(transient-toys-wave)
```

The initial value `-otoy=A` gets rendered for both options in the prefix. I expected it to get "consumed" by the first option in the list `transient-toys--choices`.

**Comment by tarsius** [comment]
Each suffix looks for a match in the prefix's value, independent to other suffixes.

https://github.com/magit/transient/blob/ad953cc3c5b8a066d3da11a8527c035744f1385f/lisp/transient.el#L2768-L2786. But you can implement your own lookup function, which ignores certain values. You don't even need a new class to do that.

https://github.com/magit/transient/blob/ad953cc3c5b8a066d3da11a8527c035744f1385f/lisp/transient.el#L2753-L2758.
