### ISSUE TITLE
Handle minibuffer use outside of `interactive`

### ISSUE THREAD

**Issue by tarsius** [magit/transient#222]
Could this issue be re-opened?  I have the same issue.

Please try running the following:

```lisp
(defun tmwe-locate-git-file ()
  "locate the nearest .git file upwards"
  (locate-dominating-file "." ".git"))

(defun tmwe-unquote (exp) ;; copied from doom-unquote
  "Return EXP unquoted."
  (declare (pure t) (side-effect-free t))
  (while (memq (car-safe exp) '(quote function))
    (setq exp (cadr exp)))
  exp)

(defun tmwe-dirlist-invocation ()
  (concat "fdfind "
          "-c never -t d "
          "--base-directory "
          (locate-dominating-file "." ".git")))

(defun tmwe-completing-read ()
  "Make sure you are in a vc root!"
  (completing-read "select something> "
                   (tmwe-unquote
                    (split-string
                     (shell-command-to-string (tmwe-dirlist-invocation))
                     "\n"))))

(transient-define-prefix tmwe ()
  "Transient MWE for Focus Loss"
  :transient-non-suffix 'transient--do-quit-one
  :transient-suffix 'transient--do-stay
  [[
    ("f" "find-file"
     (lambda () (interactive)
       (find-file (concat
                   (locate-dominating-file "." ".git")
                   (file-name-as-directory (tmwe-completing-read))))))
    ]])
```
This works just fine in commit `51c50d8c828b5fac2878b651e2188ad0c6f44184` (which I've been using for a very long time).

I have other functions that use `save-excursion` and `save restriction` to edit other files (opened with `find-file`) that fail similarly with commits after `51c50`.

_Originally posted by @t-e-r-m in https://github.com/magit/transient/issues/207#issuecomment-1304658659_

**Comment by tarsius** [comment]
> Could this issue be re-opened?

This revealed some issues, so yes, we need an open issue to track it.

I am working on those issue in the `work` branch.

> I have the same issue.

I don't think it is the same issue. I still cannot reproduce @WorldsEndless' issue and believe that is because I already fixed it. At the same time I can reproduce your issue, have determined its cause and have a tentative fix.

----

But first, there *is* a common issue in the two examples you provided:

You both use `:transient-non-suffix 'transient--do-quit-one`. That pre-command is not intended for use with `:transient-non-suffix`. You probably should just drop that altogether. You can also use a boolean to answer the question "can non-suffixes be invoked?". The documentation concerning this to be improved (which the first commit in `work` tries to do).

(I also wonder why you both decided to use the same invalid value; is there some bad example out there?)

(The documentation concerning `:transient-suffix` also has to be improved.)

But that is not the cause of the issues you are reporting.

----

You are using the minibuffer outside of `interactive`. Move the use of the minibuffer inside `interactive` and your command works.

While doing that is the proper fix in this case, sometimes it is really necessary and appropriate to use the minibuffer inside the function body, and `transient` has to be prepared to deal with that. "Suspending" the transient state while the minibuffer is in use and then resuming it again when the minibuffer is exited, is quite tricky and sadly has to rely on circumstantial evidence.

The case where the minibuffer is used outside of `interactive` requires an additional special case, which was not implemented until now. The third commit in `work` seems to address it, but this requires additional testing.

**Comment by t-e-r-m** [comment]
Thank you for the prompt and detailed reply.

> (I also wonder why you both decided to use the same invalid value; is there some bad example out there?)

That's my mistake -- it's been a while since I wrote a transient and used the example on the previous issue as a reference.  In transients I've written before I use the following:

`  :transient-non-suffix 'transient--do-warn`

For me, the functions where this issue is present, indeed do not use the minibuffer inside `interactive`.

Thank you again for taking this up and looking forward to the fix :)

**Comment by tarsius** [comment]
804c27f1f585c05a777c288fbcfa1c16a3c0cd45 should fix this.

ec20c0b65dcc3b274c124c15b0dcca01cf91ce4c updates relevant documentation.

**Comment by tarsius** [comment]
I had to revert this (in 72d1f05cbd353fceff4eb028dff0eccc3584303a) for now because it leads to another issue, which I consider to be more severe (#229, magit/magit#4832). I am working on finding a solution that addresses both issues and is generally more robust.

/cc @WorldsEndless @precompute
