### ISSUE TITLE
Display-only data

### ISSUE THREAD

**Issue by psionic-k** [magit/transient#226]
I will implement this

For applications where setting the state directly would have no useful side effect, such as for diagnostic-only information, it would be nice to have a way to define a child that has no key binding and just displays a variable or function result

Lisp variable infixes are a decent solution.  I think we just need a brand new child class.  I haven't decided all of the implementation details.

The layout and binding logic may require a special case for such a child.

**Comment by tarsius** [comment]
I've implemented this. For now it can be found only on the `work` branch.

**Comment by psionic-k** [comment]
Thanks, guessing I need to update the showcase examples.  I'm adding myself as a watcher for this repository.

**Comment by tarsius** [comment]
Not a bad idea -- more is coming.
