### ISSUE TITLE
infix args lost after more than one minibuffer read

### ISSUE THREAD

**Issue by kyleam** [magit/transient#229]
In magit/magit#4832, @catap reported that the `--force` argument was dropped when calling `magit-push-other`.  As I mentioned [there](https://github.com/magit/magit/issues/4832#issuecomment-1368170530), it looks like `magit-push-arguments` comes up empty after the _second_ `completing-read` call.

I've isolated the issue to the falling snippet:

```elisp
(transient-define-prefix foo ()
  ["Arguments"
   ("-a" "a" "-a")]
  ["Actions"
   ("d" "foo-do" foo-do)])

(defun foo-arguments ()
  (transient-args 'foo))

(defun foo-do (args)
  (interactive
   (list (progn
           (message "args before first read: %S" (foo-arguments))
           (message "read %S" (read-string "anything: "))
           (message "args before second read: %S" (foo-arguments))
           (message "read %S" (read-string "anything else: "))
           (foo-arguments))))
  (message "args: %S" args))
```

```
args before first read: ("-a")
read "x"
args before second read: ("-a")
read "y"
args: nil
```

The problem bisects to 804c27f (Deal with commands that use the minibuffer outside of interactive, 2022-11-18, gh-222).  If I revert that commit (on top of the current master, c6cf2f2), I see the expected output:

```
args before first read: ("-a")
read "x"
args before second read: ("-a")
read "y"
args: ("-a")
```

**Comment by tarsius** [comment]
Thanks for looking into this. I can confirm your analysis. My own initial analysis revealed ... that it is complicated.

The cause for all this trouble is that `post-command-hook` does not work as advertised. I did some early experiments with *advising* the current command instead of the current approach of passing around state between different ad hoc hook functions. Initial results are promising. Might take a while though.

**Comment by kyleam** [comment]
> My own initial analysis revealed ... that it is complicated.

Bah, I was holding out hope for a simple one-liner fix.  Thank you for revisiting this.

**Comment by tarsius** [comment]
`post-command-advise` should to the trick, but I will have to test some more, going through all the cases that lead to changes to the previous implementation.

**Comment by tarsius** [comment]
I've fixed this, but at a cost. Temporarily reintroducing #222.
