### ISSUE TITLE
Broken on Emacs 28.x

### ISSUE THREAD

**Issue by mopsfelder** [magit/transient#233]
@tarsius 
Jonas, the commit https://github.com/magit/transient/commit/5a966aa857d08894961bae65d579fa79109ff2b3 seems to have broken transient on Emacs 28.x.

The change uses the `keymap-set` function, which is not available on the Emacs release 28.2, the latest as of this writing.

Doomemacs users [reported](https://github.com/doomemacs/doomemacs/issues/7078) that Doomemacs failed to startup even after a fresh install, the following error was thrown:

```
Error (doom-first-file-hook): Error running hook "global-git-commit-mode" because: (void-variable transient-base-map) Disable showing Disable logging
```

After some digging, reverting the commit https://github.com/magit/transient/commit/5a966aa857d08894961bae65d579fa79109ff2b3 solved the issue.

Do you think it is possible to revert this commit until Emacs 29 is officially released?

Cheers!

**Comment by tarsius** [comment]
I have commented at https://github.com/doomemacs/doomemacs/issues/7078#issuecomment-1434728699.

In short, Doom Emacs has to be updated to use a recent version of the `compat` package.

**Comment by mopsfelder** [comment]
Thank you, @tarsius!
