### ISSUE TITLE
`:command` gets overwritten when set to lambda function

### ISSUE THREAD

**Issue by jdtsmith** [magit/transient#234]
```elisp
(transient-define-prefix my/example ()
  ["Option:" ("-x" "Add more X" "--more-x")]
  ["Actions:"
   ("a" :command (lambda () (interactive) (message "The A action")) :description "Do A")
   ("b" :command (lambda () (interactive) (message "The B action")) :description "Do B")])

(my/example)
```

Invoking `a` yields `The B action`.  This is because the internal name `transient:my/example::command` gets repeated for both.

**Comment by tarsius** [comment]
These suffix specifications are invalid. Use this instead:

```elisp
(transient-define-prefix my/example ()
  ["Option:" ("-x" "Add more X" "--more-x")]
  ["Actions:"
   ("a" "Do A" (lambda () (interactive) (message "The A action")))
   ("b" "Do B" (lambda () (interactive) (message "The B action")))])
```

Suffix specifications have this form:

```
([LEVEL] [KEY [DESCRIPTION]] COMMAND|ARGUMENT [KEYWORD VALUE]...)
```

I.e., COMMAND or ARGUMENT must be specified before the plist that might follow.

I've just pushed a change to signal an error when a keyword is found where a command or argument is expected.

**Comment by jdtsmith** [comment]
Thanks, this will be useful.  I should have been more explicit.  The reason I reached for `:command` is because I want a function for `:description` as well, and `define-prefix` errors without a plain description here.

Should I just use a "sacrificial" description and replace it using `:description`? Ala:

```elisp
(transient-define-prefix my/example ()
  ["Option:" ("-x" "Add more X" "--more-x")]
  ["Actions:"
   ("a" "will-not-show-a" (lambda () (interactive) (message "The A action"))
    :description (lambda () (format "Do A %d" (% (random) 10))))
   ("b" "will-not-show-b" (lambda () (interactive) (message "The B action"))
    :description (lambda () (format "Do B %d" (% (random) 10))))])
```

**Comment by tarsius** [comment]
I've fixed that now.

```elisp
(transient-define-prefix example-1 ()
  [("a" (lambda () (interactive) (message "The A action")) :description (lambda () "Do A"))
   ("b" (lambda () (interactive) (message "The B action")) :description (lambda () "Do B"))])

(transient-define-prefix example-2 ()
  [("a" (lambda () "Do A") (lambda () (interactive) (message "The A action")))
   ("b" (lambda () "Do B") (lambda () (interactive) (message "The B action")))])

(list (get 'example-1 'transient--layout)
      (get 'example-2 'transient--layout))
```

**Comment by jdtsmith** [comment]
Thanks for this.  One final issue. I notice that `transient--parse-suffix` sets up _aliases_ for (some of?) the lambda functions included in suffix specifications, ala:

```elisp
(intern (format "transient:%s:%s"
                                   prefix
                                   (or (plist-get args :description)
                                       (plist-get args :key))))))
```

And then transient references those aliases.  This works well when a given `transient-define-prefix` is evaluated at _run-time_ (C-M-x style).  But these aliases do not make it through macro expansion when a file containing a transient prefix definition is compiled.  This leads to errors of the sort "transient-setup: Suffix transient:ipy-manager:imp-ret is not defined or autoloaded as a command".  

Perhaps only certain slots are truly supported as lambda functions vs. named symbols, when considering byte-compiled transients?

**Comment by tarsius** [comment]
That's now fixed too.
