### ISSUE TITLE
Setting defaults à la magit-popup's `C-t`

### ISSUE THREAD

**Issue by matthew-piziak** [magit/transient#24]
Hi! In `magit-popup` one can use `C-t` to save defaults in a popup. Is the corresponding behavior possible in Transient?

**Comment by kyleam** [comment]
Hmph, isn't `C-t` bound by default to [magit-popup-toggle-show-common-command][mp] in Magit-Popup?  Anyway, I think you're after [transient-{set,save}][ts].

[mp]: https://magit.vc/manual/magit-popup.html#Usage
[ts]: https://magit.vc/manual/transient/Saving-Values.html#Saving-Values

**Comment by matthew-piziak** [comment]
Oh huh, you're right. Don't know where I got `C-t` from.

Anyway, thanks! That's exactly what I needed. I grepped the manual for "default" but that section escaped me.
