### ISSUE TITLE
A transient with a buffer as an argument

### ISSUE THREAD

**Issue by haji-ali** [magit/transient#249]
I have the transient that takes a buffer as an argument, for example using:

```lisp
(transient-define-argument my/buffer ()
  :description "Buffer"
  :init-value (lambda (obj)
                (setf (slot-value obj 'value)   (current-buffer)))
  :class 'transient-argument)
```

This works fine. However, when the arguments are saved in `transient-history-file`, the argument is printed as (#<buffer-name>) which then produces an error upon loading the file:

```
Debugger entered--Lisp error: (invalid-read-syntax "#" 11 5)
  read(#<buffer  *temp*>)
  transient--read-file-contents("/Users/ah180/.config/emacs/.elocal/var/transient/h...")
  eval-expression((transient--read-file-contents transient-history-file) nil nil 127)
  funcall-interactively(eval-expression (transient--read-file-contents transient-history-file) nil nil 127)
  command-execute(eval-expression)
```

I believe this is a bug, unless there's a way I am missing to correctly load/save such arguments or otherwise exclude them from being saved/loaded.

**Comment by tarsius** [comment]
You can set the `unsavable` suffix slot to `t` to prevent its value from being saved as part of the prefixes value.
