### ISSUE TITLE
Make some accommodation for column alignment

### ISSUE THREAD

**Issue by hexmode** [magit/transient#25]
Following the resolution of magit/magit-popup#14 I've successfully changed the possible faces to inherit from `fixed-pitch`, but this does not resolve the problem.

As long as transient assumes that a fixed pitch is used for the default face and that (as a result) it can simply use spaces to achieve a columnar layout of the commands, this problem will persist.  

![image](https://user-images.githubusercontent.com/43581/54078443-110b6d80-4296-11e9-8600-3a091f7975bc.png)

It looks like `package-menu-mode` (*mostly*) fixes this by using the following bit:

```
	      ;; Insert a space that aligns the button properly.
	      (propertize " " 'display (list 'space :align-to column)
			  'face 'fixed-pitch)
```

![image](https://user-images.githubusercontent.com/43581/54078520-65fbb380-4297-11e9-8ca4-3109834b2962.png)

**Comment by hexmode** [comment]
It looks like [`docker.el`](https://github.com/Silex/docker.el/) does the alignment for the listing of docker images by using `tabulated-list-mode` which looks a little better than what `package-menu-mode` does.
![image](https://user-images.githubusercontent.com/43581/54078707-377fd780-429b-11e9-821c-ef2c5c472602.png)

**Comment by hexmode** [comment]
but, if neither of those is feasible, using the standard `fixed-pitch` face would work for the current layout method.

**Comment by tarsius** [comment]
I just checked the definition of the `fixed-pitch` face in my configuration. I used `customize-face` and `describe-face` and they both reported that `Font Family: Monospace`. That's not a nice way of saying that so I looked at the documentation and learned that `face-attribute` and `face-all-attributes` are the functions I was looking for. However those report that `(:family . unspecified)`. Something is weird here and I will have to investigate why I get different results here. Maybe you could do that?

Anyway I was looking at all this because I think it is quite possible that many users have customized `default` to use their preferred monospaced font *without* also customizing `fixed-pitch` to use the same font.

If we now make the `transient` faces inherit from `fixed-pitch`, then the transient buffer start using a different font than the rest of Emacs. So I think we shouldn't do it because I expect there are many more users who have done that than there are users who use a proportional font for `default`.

**Comment by hexmode** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> However those report that `(:family . unspecified)`. Something is
> weird here and I will have to investigate why I get different results
> here. Maybe you could do that?

It is a little weird.

Here is an ielm session that I just did:
```
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (face-all-attributes 'fixed-pitch)
((:family . unspecified)
 (:foundry . unspecified)
 (:width . unspecified)
 (:height . unspecified)
 (:weight . unspecified)
 (:slant . unspecified)
 (:underline . unspecified)
 (:overline . unspecified)
 (:strike-through . unspecified)
 (:box . unspecified)
 (:inverse-video . unspecified)
 (:foreground . unspecified)
 (:background . unspecified)
 (:stipple . unspecified)
 (:inherit . unspecified))

ELISP> (face-attribute 'default :family)
"Go"
ELISP> (face-attribute 'fixed-pitch :family)
"Go Mono"
ELISP> (face-all-attributes 'fixed-pitch (selected-frame))
((:family . "Go Mono")
 (:foundry . unspecified)
 (:width . unspecified)
 (:height . unspecified)
 (:weight . unspecified)
 (:slant . unspecified)
 (:underline . unspecified)
 (:overline . unspecified)
 (:strike-through . unspecified)
 (:box . unspecified)
 (:inverse-video . unspecified)
 (:foreground . unspecified)
 (:background . unspecified)
 (:stipple . unspecified)
 (:inherit . unspecified))

ELISP> (face-all-attributes 'default (selected-frame))
((:family . "Go")
 (:foundry . "    ")
 (:width . normal)
 (:height . 203)
 (:weight . normal)
 (:slant . normal)
 (:underline)
 (:overline)
 (:strike-through)
 (:box)
 (:inverse-video)
 (:foreground . "gray80")
 (:background . "#181a26")
 (:stipple)
 (:inherit))

ELISP> (face-all-attributes 'default)
((:family . unspecified)
 (:foundry . unspecified)
 (:width . unspecified)
 (:height . 200)
 (:weight . unspecified)
 (:slant . unspecified)
 (:underline . unspecified)
 (:overline . unspecified)
 (:strike-through . unspecified)
 (:box . unspecified)
 (:inverse-video . unspecified)
 (:foreground . unspecified)
 (:background . unspecified)
 (:stipple . unspecified)
 (:inherit . unspecified))

ELISP> 
```

I'm wasn't sure why `face-all-attributes` did not specify "Go Mono" till
I saw that it can take another argument with a specific frame in it.

A little more clarity comes when we see that the `font-all-attributes`
provides the themed/customized face when you specify a frame.  Without
the fame, only `:height 200` is given.  That is there because I changed
it with `M-: (set-face-attribute 'default nil :height 200) RET` outside
of the customization system.

Without more research, I'm going to guess that the "unframed" face is
some sort of platonic ideal and that any theming or customization is
applied only after it is determined if the frame can handle the fonts.

Opening a new frame in a terminal window using emacsclient bears this
out somewhat because in the terminal window, the same ielm session
shows:
```
ELISP> (face-all-attributes 'default (selected-frame))
((:family . "default")
 (:foundry . "default")
 (:width . normal)
 (:height . 1)
 (:weight . normal)
 (:slant . normal)
 (:underline)
 (:overline)
 (:strike-through)
 (:box)
 (:inverse-video)
 (:foreground . "gray80")
 (:background . "#181a26")
 (:stipple)
 (:inherit))
```

(I say "somewhat" because
`(face-all-attributes 'fixed-pitch (selected-frame))` in the terminal
window shows :family is set to "Go Mono". So my theory doesn't work
completely.)

> Anyway I was looking at all this because I think it is quite possible
> that many users have customized `default` to use their preferred
> monospaced font *without* also customizing `fixed-pitch` to use the
> same font.

Agreed.

> If we now make the `transient` faces inherit from `fixed-pitch`, then
> the transient buffer start using a different font than the rest of
> Emacs.

Is there a hook that transient runs?

For example, with magit-popup, I can add
`(lambda () (buffer-face-set 'fixed-pitch))` to magit-popup-mode-hook so
that things are formatted correctly.

I've done this for several mode types that assume a fixed-pitch font:

```
(defvar mah/fixed-width-modes
'("prog" "org-agenda" "shell" "term" "diff" "dired" "calendar"
  "ssh-tunnels" "magit-popup" "help" "magit-log" "apache" "sql"
  "picture" "ibuffer" "calc-keypad" "proced" "yaml" "makefile"
  "makefile-gmake"))
(dolist (mode mah/fixed-width-modes)
  (add-hook (intern (concat mode "-mode-hook"))
            (lambda () (buffer-face-set 'fixed-pitch))))
```

**Comment by tarsius** [comment]
> Without more research, I'm going to guess that the "unframed" face is some sort of platonic ideal and that any theming or customization is applied only after it is determined if the frame can handle the fonts.

Thanks for the analysis but this is still just speculation and not enough for me to start inheriting from `fixed-pitch`. But you are not arguing for that anyway:

> Is there a hook that transient runs? For example, with magit-popup, I can add `(lambda () (buffer-face-set 'fixed-pitch))` to magit-popup-mode-hook so that things are formatted correctly.

Not yet, I still have to think about what hooks make sense. This issues serves as a datapoint as far as that work goes.

For now an after advice on `transient-setup` should probably do the trick.

**Comment by tarsius** [comment]
Once you have something that works, please add it to https://github.com/magit/transient/wiki/Tips-and-Tricks.

**Comment by hexmode** [comment]
Here is what I have:
``` lisp
(defun mah/set-buffer-fixed (&optional buf)
  "Set the current buffer to use fixed pitch."
  (buffer-face-set 'fixed-pitch))
(defmacro with-window-buffer (window &rest body)
  "Execute the forms in BODY with the buffer associated with WINDOW temporarily current.
WINDOW must be a window.  The value returned is the value of the
last form in BODY.  See also `with-temp-buffer'."
  (declare (indent 1) (debug t))
  `(with-current-buffer (window-buffer ,window)
     ,@body))
(advice-add 'transient-setup :after
            (lambda (x)
              (with-window-buffer  transient--window
                (mah/set-buffer-fixed))))
```

**Comment by tarsius** [comment]
Ah, `Restrict editing to users in teams with push access only` was enabled. Could you please add this now, so that it is attributed to you.

**Comment by Gira-X** [comment]
> It looks like `package-menu-mode` (_mostly_) fixes this by using the following bit:
> 
> ```
> 	      ;; Insert a space that aligns the button properly.
> 	      (propertize " " 'display (list 'space :align-to column)
> 			  'face 'fixed-pitch)
> ```

One can actually advice this into the current transient code rather easily:

```emacs-lisp
(cl-defmethod dima-transient--insert-group ((group transient-columns))
  "Patches:
- use `propertize' with a space to align the columns for variable width fonts"
  (let* ((columns
          (mapcar
           (lambda (column)
             (transient--maybe-pad-keys column group)
             (let ((rows (mapcar #'transient-format (oref column suffixes))))
               (when-let ((desc (transient-format-description column)))
                 (push desc rows))
               rows))
           (oref group suffixes)))
         (rs (apply #'max (mapcar #'length columns)))
         (cs (length columns))
         (cw (mapcar (lambda (col) (apply #'max (mapcar #'length col)))
                     columns))
         (cc (transient--seq-reductions-from (apply-partially #'+) cw 0)))
    (if transient-force-single-column
        (dotimes (c cs)
          (dotimes (r rs)
            (when-let ((cell (nth r (nth c columns))))
              (unless (equal cell "")
                (insert cell ?\n))))
          (unless (= c (1- cs))
            (insert ?\n)))
      (dotimes (r rs)
        (dotimes (c cs)
          (insert (propertize " " 'display
                              (list 'space :align-to
                                    (nth c cc))))
          (when-let ((cell (nth r (nth c columns))))
            (insert cell))
          (when (= c (1- cs))
          (insert ?\n)))))))
          
(advice-add #'transient--insert-group :override
              #'dima-transient--insert-group)
```

Without the advice and a variable width font:

![image](https://user-images.githubusercontent.com/15002298/141690506-534527a9-d306-465b-bef6-1c762fced755.png)

With the advice (which should work with all fonts I guess, but I have only tested this for me):

![image](https://user-images.githubusercontent.com/15002298/141690513-9f6e2b7a-9fd0-41b2-8d5d-85e0bddb3a52.png)

**Comment by Gira-X** [comment]
Well, the advice above was not the greatest idea as the transients end up not displaying the `:description` title. 

This is cleaner and more consistent to how transient implements its classes/groups and the `:description` works correctly:

```emacs-lisp
(defclass dima-transient-columns (transient-group) ())

(cl-defmethod transient--insert-group ((group dima-transient-columns))
  "Patches:
- use `propertize' with a space to align the columns for variable width fonts"
  (let* ((columns
          (mapcar
           (lambda (column)
             (transient--maybe-pad-keys column group)
             (let ((rows (mapcar #'transient-format (oref column suffixes))))
               (when-let ((desc (transient-format-description column)))
                 (push desc rows))
               rows))
           (oref group suffixes)))
         (rs (apply #'max (mapcar #'length columns)))
         (cs (length columns))
         (cw (mapcar (lambda (col) (apply #'max (mapcar #'length col)))
                     columns))
         (cc (transient--seq-reductions-from (apply-partially #'+) cw 0)))
    (if transient-force-single-column
        (dotimes (c cs)
          (dotimes (r rs)
            (when-let ((cell (nth r (nth c columns))))
              (unless (equal cell "")
                (insert cell ?\n))))
          (unless (= c (1- cs))
            (insert ?\n)))
      (dotimes (r rs)
        (dotimes (c cs)
          (insert (propertize " " 'display
                              (list 'space :align-to
                                    (nth c cc))))
          (when-let ((cell (nth r (nth c columns))))
            (insert cell))
          (when (= c (1- cs))
            (insert ?\n)))))))

(transient-define-prefix dima-transient-permissions ()
  [:class dima-transient-columns
   ["Actions"
    ("a" dima-add-permission :description "Add"))
```

**Comment by tarsius** [comment]
Also see the current version of this function...

**Comment by Gira-X** [comment]
Hah, I see!  Thanks for pointing that out. Sorry, I had an outdated transient :(

**Comment by tarsius** [comment]
Currently this has to be set per instance. A variable to always support use of a proportional font is on the table.

However looking at the above I think it looks really bad when the keys use a proportional font. Have you consider using a monospaced face for those?

**Comment by Gira-X** [comment]
Now that you point it out, yeah it does look bad.

This is how it looks like when `transient-key` is set to a monospace font which is a nice improvement indeed. Thanks for the suggestion!

![image](https://user-images.githubusercontent.com/15002298/141832235-0c57d8bc-eb9c-4e31-80eb-0c8193f5dfb8.png)

**Comment by tarsius** [comment]
Am I correct in assuming that you use a variable-pitch font across pretty much all of emacs and that you have done this by setting the font of the `default` face?

**Comment by tarsius** [comment]
There's something in the `variable-pitch` branch, but it probably will be a while until I finish that.
