### ISSUE TITLE
Transient And Emacspeak

### ISSUE THREAD

**Issue by tvraman** [magit/transient#255]
Description: A while ago you helped me put together a solution for
browsing the ephemeral  transient window from emacspeak; code is here:
https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-transient.el#L1
and user docs are at
https://tvraman.github.io/emacspeak/manual/emacspeak_002dtransient.html
That interaction broke with the latest transient/magit update today,
and now I get "unbound suffix" when I try to suspend the transient;
cursor navigation does not speak the current entry any more.

Could you point me at the relevant changes in transient so I can debug?

**Comment by tarsius** [comment]
> Could you point me at the relevant changes in transient so I can debug?

This is a likely candidate
https://github.com/magit/transient/commit/226db67b3680acbeb74cb0403e1a302917054174

Just a guess, but I would try without the `funcall-interactively` in `emacspeak-transient-next-section` and `emacspeak-transient-previous-section`.

**Comment by tvraman** [comment]
Hi Jonas,

Thanks for the quick reply.

I did as you suggested but it didn't make a difference code update
pushed to github.

Here is the diff between the old and new behavior:

Earlier (Good)

Magit Status Buffer:

1. Press 'l' to bring up the log pop-up.
Available options (all of them) are spoken in my right ear (because
#'message is adviced to do so).

2. At the same time, an auditory icon plays to indicate something
   opened.

   3. The selected choice is spoken on the primary audio channel.
      4. If the options are too many and it's something new that the
         user needs to learn,pressing C-z suspends the transient.
         

      After: upgrade

(3) no longer happens.
(4) also does not happen on C-z

Pressing C-h c while transient is acting non-deterministically gives
me the behavior I used to get with transient-suspend.

I added an explicit call to speak the selection in my next/previous
function but it didn't appear to get called.

Jonas Bernoulli writes:
 > > Could you point me at the relevant changes in transient so I can debug?
 > 
 > This is a likely candidate
 > https://github.com/magit/transient/commit/226db67b3680acbeb74cb0403e1a302917054174
 > 
 > Just a guess, but I would try without the `funcall-interactively` in `emacspeak-transient-next-section` and `emacspeak-transient-previous-section`.
 > 
 > 
 > -- 
 > Reply to this email directly or view it on GitHub:
 > https://github.com/magit/transient/issues/255#issuecomment-1699555686
 > You are receiving this because you authored the thread.
 > 
 > Message ID: ***@***.***>
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
I tried reproducing the issue but obviously I don't have all the software that is required for emacspeak to actually work. So I commented out `(require 'emacspeak-preamble)` in `emacspeak-transient.el` and kept commenting out things until the byte-compiler stopped complaining. I replaced the code that I think is supposed to make some sound to instead use `message`.

I am unsure what to do about `(ems-interactive-p)`. I could find a definition, which simply raises an error, but I could not find the definition that is actually supposed to be used. So I just replaced that with `(called-interactively-p 'any)`.

Then I tried to reproduce the error, but everything worked as expected. I did not get an "unbound suffix" as you mentioned in your initial report (please provide a backtrace), and 3 and 4 from your follow up also work for me.

I have pushed the commented version I used to reproduce to the `transient-255` branch of https://github.com/emacsmirror/emacspeak. Maybe you could try to reproduce the issue with that. If you can't, you can then undo my edits until you can reproduce again.

**Comment by tvraman** [comment]
Apologies for the trouble debugging Jonas!

Let me propose some simpler things to try at your end independent of
emacspeak.

If you could show me how to produce a message when the user presses
up/down arrow when a transient is active to move through the choices,
and have that message show the current choice, I'll be able to reverse
engineer what I need from there.

We both have a situation here where the other's package is hard to
debug -- not a criticism -- but for me, transient is hard because of the
cursor motion happening in a buffer other than the current one, my not
being able to see the screen, and transient taking over the keyboard. I
did have debug on error turned on; there are no errors; the expected
speech just doesn't happen.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
As a first step, could you tell me the transient magic  for getting my
emacspeak keys working in transient? You had helped in the past but
that code apparently fails to have the desired effect.

So now, when a transient is active, pressing C-e l
(emacspeak-speak-line) and C-e m (emacspeak-speak-mode-line)
both produce the following in the *Messages* buffer:
Turning on magit-auto-revert-mode...done
Unbound suffix: ‘C-e l’ (Use ‘C-g’ to abort, ‘?’ for help) [emacspeak-speak-line]
Unbound suffix: ‘C-e m’ (Use ‘C-g’ to abort, ‘?’ for help) [emacspeak-speak-mode-line]

**Comment by tarsius** [comment]
You need to add entries for these commands in the special keymap `transient-predicate-map`. You already do that for other commands in `emacspeak-transient-setup`. I.e., add:

    (define-key transient-predicate-map [emacspeak-speak-line] 'transient--do-stay)
    (define-key transient-predicate-map [emacspeak-speak-mode-line] 'transient--do-stay)

**Comment by tvraman** [comment]
Ah those were not needed in the past. Will try that will help me debug
better.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
Added your suggestion 

(define-key transient-predicate-map [emacspeak-speak-line] 'transient--do-stay)
(define-key transient-predicate-map [emacspeak-speak-mode-line]
'transient--do-stay)

And that does work to the extent that I can use those commands, but
given that focus is not in the buffer showing the transient, it
doesn't help much --- other than demystefy  transient for me to an
extent. Still unable to hear the current choice as I arrow navigate
-- sigh!

**Comment by tvraman** [comment]
Got it talking again! Needs more polish but it talks -- see
emacspeak-transient.el on github

**Comment by tarsius** [comment]
Currently there is an influx of requests to help with or to work on things other than what I was planning to work on. As a result I am a bit slow to respond.

Your implementation still seems to rely a lot on copying the text in the transient buffer into a separate buffer, suspending transient, doing things in the separate buffer as you usually would, and finally resuming the transient.

I think that is a misguided approach, which complicates matters.

Instead I propose, that you temporarily select the transient buffer, when things have to be spoken. I have suggested that before and can see that you are using this approach in your advice to transient-backward-button and transient-forward-button. I would recommend discarding emacspeak-transient-mode (or maybe only keeping it as a debugging tool of last resorts) and to instead embrace the "whenever something has to be spoken, temporarily select the transient buffer" approach.

I think that boils down to replacing

    (something-that-speaks)

with

    (with-selected-window transient--window
      (something-that-speaks))

You can do that by advising the appropriate transient commands and functions. In some cases you may prefer to add new commands. The basic approach would be the same then, use with-selected-window before speaking, but additionally you have to tell transient about those commands, which is done by adding an entry to transient-predicate-map, as I suggested above.

**Comment by tvraman** [comment]
I'll keep it short; the copy text to a separate buffer hack likely needs
to go, but I only use that to debug at present; in the normal course of
things I never need to do that --- and right now I can use magit with
transient without resorting to suspending it.

And thank you again for magit and all you do -- 
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
Adding a brief note here so  we remember.
The breakage that happened with Emacspeak in the latest transient
release explained:
1. Before the latest release, the emacspeak advice on transient--show
   only played an auditory icon; it depended on advice on #'message to
   speak the current item as one navigated with cursor keys. In the
   newest transient, the message is likely the list of all choices --
   the fix was to add a (dtk-stop 'all) and a (emacspeak-speak-line)
   to the advice on transient--show -- now everything works as
   desired.
