### ISSUE TITLE
Feature Request: Allow adding hidden commands to transients

### ISSUE THREAD

**Issue by jojojames** [magit/transient#26]
Thanks for the package!

This would be pretty cool to have to allow transient to be used as a generic command launcher.

**Comment by tarsius** [comment]
> This would be pretty cool to have to allow transient to be used as a generic command launcher.

Please explain in more detail what you mean by "generic command launcher" and how hidden commands help making that possible.

It is already possible to have hidden *groups* of commands. See info node *Group Specifications*.

**Comment by jojojames** [comment]
> Please explain in more detail what you mean by "generic command launcher" and how hidden commands help making that possible.

Hydra is best what comes to mind, adding various potentially unrelated commands to a single hydra using it as a 'command launcher'. In hydra, any single command can be kept hidden (I guess because there's no concept of a group within a hydra).

> It is already possible to have hidden groups of commands. See info node Group Specifications.

I think it'd be desirable to hide commands within specific groups too.

For example:

This is a hydra I have.

```
(defhydra hydra-space (:color blue :hint nil :idle .2)
  "

   Space: %s`default-directory

   Find           Manage         ^^^^Do               Mode
   ------------------------------------------------------------------------------
   _f_ File       _w_ Window      _s_ Search           _m_ Mode
   _b_ Buffer     _g_ Git         _R_ Refactor         _d_ Debug
   _r_ Recent     _p_ Project     _v_ Edit Init.el     _e_ Eval
   _n_ Sidebar    _y_ System      _o_ Org              _t_ Test
   _SPC_ Any      _U_ Undo        _u_ Universal Arg..  _=_ Format

   "
  ("u" universal-argument)
  ("-" split-window-below)
  ("|" split-window-right)
  ("\\" split-window-right)
  ("h" evil-window-left)
  ("l" evil-window-right)
  ("k" evil-window-up)
  ("j" evil-window-down)
  ("." evil-next-buffer)
  (">" evil-prev-buffer :color red)
  ("," evil-prev-buffer)
  ("<" evil-prev-buffer :color red)
  ("<backspace>" delete-window)
  ("DEL" delete-window) ;; For terminals.
  ("v" (lambda () (interactive) (find-file "~/.emacs.d/init.el")))
  ("x" kill-buffer)
  ("c" matcha-evil-mc/body)
  ("RET" quickrun)
  (";" counsel-M-x)
  (":" eval-expression)
  ("'" eval-expression)
  ("S" j|save-all-buffers)
  ("=" matcha-run-format-command)
  ("d" matcha-run-debug-command)
  ("m" matcha-run-mode-command)
  ("e" matcha-run-eval-command)
  ("t" matcha-run-test-command))
```
I may want a transient that defines a 'window' section that groups:

```
  ("-" split-window-below)
  ("|" split-window-right)
  ("\\" split-window-right)
  ("h" evil-window-left)
  ("l" evil-window-right)
  ("k" evil-window-up)
  ("j" evil-window-down)
```

I think it's extra noise to have h/j/k/l in the hint since I know it by heart and may just want - and |/\ grouped.

I think hydra is very good for this but the tedium of writing the hydra hint explicitly makes me think transient can be a good replacement over it. e.g

```
(define-transient-command space-transient (branch)
  "asdfasf"
  :man-page "git-branch"
  [["Find"
    ("f" "File" j|find-file-dwim)
    ("b" "Buffer" j|buffers-dwim)
    ("r" "Recent" j|recentf-dwim)
    ("n" "Sidebar" dired-sidebar-toggle-sidebar)
    ("SPC" "In Project" j|search)]
   ["Manage"
    ("w" "Window" hydra-window/body)
    ("g" "Git" matcha-magit/body)
    ("p" "Project" matcha-projectile/body)
    ("y" "System" hydra-system/body)
    ("U" "Undo Tree" undo-tree-visualize)]
   ["Do"
    ("s" "Search" hydra-search/body)
    ("R" "Refactor" matcha-run-refactor-command)
    ;; ("v" "Edit Config" (lambda () (interactive) (find-file "~/.emacs.d/init.el")))
    ("o" "Org" hydra-org-space/body)
    ;; ("u" universal-argument) ;; WANT TO HIDE THIS!
    ]
   ["Mode"
    ("m" "Mode" matcha-run-mode-command)
    ("d" "Debug" matcha-run-debug-command)
    ("e" "Eval" matcha-run-eval-command)
    ("t" "Test" matcha-run-test-command)
    ("=" "Format" matcha-run-format-command)
    ]])
```

**Comment by tarsius** [comment]
I am not using Transient to do that sort of thing yet. Expect some improvements once I do.

> I think it'd be desirable to hide commands within specific groups too.

Not sure about that because it would be much more noisy, i.e. every one of those suffixes would end with `... :hide t)`. Putting all of them into an always hidden group is less noisy: `[:hide (lambda () t) ...]`.

> `;; ("u" universal-argument) ;; WANT TO HIDE THIS!`

What are you trying to do here. `universal-argument` is already available in all transients. It affects the next invoked command. You cannot use `universal-command` as a suffix that exits the transient, and have the prefix argument be used by the next command that is invoked from outside the transient.

**Comment by jojojames** [comment]
> I am not using Transient to do that sort of thing yet. Expect some improvements once I do.

Thanks. Sounds good with me.

> Not sure about that because it would be much more noisy, i.e. every one of those suffixes would end with ... :hide t). Putting all of them into an always hidden group is less noisy: [:hide (lambda () t) ...].

Yeah, I can agree there are tradeoffs both ways. :hide in every suffix wouldn't be too offensive to me since I'm coming from hydra.

> What are you trying to do here? universal-argument is already available in all transients. It affects the next invoked command. You cannot use universal-command as a suffix that exits the transient, and have the prefix argument be used by the next command that is invoked from outside the transient. (Well maybe you can but if so, then that would prevent passing prefix commands to infix and suffix commands.)

I just picked a random command to put there. Its functionality in the original hydra was to provide the universal-argument to the next command (I've unbound the default keybind for universal-argument).

**Comment by tarsius** [comment]
So where does that leave us? I assume using an always-hidden group is good enough for now, right?

**Comment by jojojames** [comment]
I'll play around with it a bit more to see if the always-hidden group will work for me. Otherwise, I think we're good for now. Thanks!
