### ISSUE TITLE
After updating transient-0.4.3 to transient-0.5.2 emacs-28.1 does not start.

### ISSUE THREAD

**Issue by soilc** [magit/transient#268]
I use transient-0.4.3:

Status: Installed in ‘transient-0.4.3/’,
shadowing a built-in package.
Version: 0.4.3
Commit: 8cf1238181d57504e68f42fa0d4ef66784b197a9
Summary: Transient commands
Requires: emacs-25.1, compat-29.1.4.1
Required by: rg-20231202.1023
Website: (https://github.com/magit/transient)
Keywords: extensions 
Maintainer: Jonas Bernoulli <jonas@bernoul.li>
Author: Jonas Bernoulli <jonas@bernoul.li>
Other versions: 0.5.2 (elpa), 20231205.1848 (melpa), 0.5.2.0.20231205.184858 (elpa-devel), builtin.

After updating transient-0.4.3  to transient-0.5.2 emacs-28.1 does not start. What could be the reason?

**Comment by tarsius** [comment]
What do you mean by "does not start". It seems highly unlikely that having transient installed -- or any package for that matter -- would prevent emacs from "starting" in the literal sense, so I am guessing, you mean something else.

**Comment by soilc** [comment]
A couple of days ago I decided to update the packages (there were 12 in total) using the standard procedure in the list-packages buffer: `U` and then `x`. After this, the package update process occurs without any error messages.
But if I close emacs and then try to start it again (runemacs.exe) nothing happens - emacs does not start. By elimination, I found that this behavior occurs specifically when updating the transient-0.4.3 package to transient-0.5.2. Because of this I am now forced to work with the old version transient-0.4.3.
Yes, it's surprising, but emacs does not start after updating the transient package.

**Comment by tarsius** [comment]
A package cannot prevent Emacs from starting, and if it does, then that is a bug in Emacs. Of course the details depend on whether the Emacs process immediately dies or just "hangs forever", with or without a window ever appearing.

I doubt that you found the real cause of whatever issue you are having. Maybe installing another Transient version does make a difference, but then I would assume that that is somewhat coincidental.

I can just give you some generic advice at this point. Uninstall transient, rg, magit and any other package that depends on transient. Exit Emacs. Restart Emacs. Reinstall these packages.

**Comment by soilc** [comment]
Yes, all this looks very strange. I've been using rg for a long time and this is not the first time I've updated this package and its dependencies. Everything always happened without any problems.
I took your advice and removed rg, transient. Then I reinstalled rg. In this case, transient was installed automatically as a dependency. Everything went well. But after I closed emacs it doesn't start anymore. The most amazing thing is that when I then delete the transient-0.5.2 folder in the `\.emacs.d\elpa\` directory, emacs starts again. Adding the transient-0.4.3 folder to `\.emacs.d\elpa\` does not prevent emacs from starting.

**Comment by tarsius** [comment]
There's not much I can do to help.

Try bisecting the issue. Instead of installing with `package.el`, clone the repository, put it on `load-path` and compile with `make clean lisp`. Then use `git bisect` to find out with which commit causes the issue.
