### ISSUE TITLE
with default transient-display-buffer-action,  help might not be displayed if *Help* in display-buffer-alist

### ISSUE THREAD

**Issue by rdiaz02** [magit/transient#271]
What I expected
===============

After starting a transient, tressing `C-h` and typing a key would show the help.

What actually happens
=====================

When the display of Help is controlled by `display-buffer-alist` and set to be `display-buffer-in-side-window` at the bottom, no help is displayed, unless the default setting for `transient-display-buffer-action` is changed.

How to reproduce
=================

Start `emacs -Q` and evaluate this code

```
(package-initialize)

(use-package transient)

(defun funA()
  "Say A"
  (interactive)
  (message "A"))

(defun funB()
  "Say B"
  (interactive)
  (message "B"))

(transient-define-prefix dummy-transient ()
  "Dummy transient"
  :transient-non-suffix 'transient--do-quit-one
  ["Commands"
   [("a" "A" funA)
    ("b" "B" funB)
    ("q" "Quit" transient-quit-one)]])

(global-set-key (kbd "C-c p") 'dummy-transient)

(setq display-buffer-alist '(
			     ("\\*Help\\*"
			      (display-buffer-in-side-window
			       display-buffer-same-window
			       display-buffer-pop-up-window)
			      (side . bottom)
			      (slot . -1))))

;; The default:  https://magit.vc/manual/transient/Configuration.html#index-transient_002ddisplay_002dbuffer_002daction
(setq transient-display-buffer-action
      '((display-buffer-in-side-window
	 (side . bottom)
	 (inhibit-same-window . t)
	 (window-parameters (no-other-window . t)))))
```

Now, `C-c p`  and then `C-h`. Hit, for example, `a`. The transient buffer disappears, and no help is shown.

Specific issues 
=============

1. Should the manual, in https://magit.vc/manual/transient/Configuration.html, under https://magit.vc/manual/transient/Configuration.html#index-transient_002ddisplay_002dbuffer_002daction mention that this setting can interfere if the display of Help is controlled with `display-buffer-alist` with `display-buffer-in-side-window`, `(side . bottom)`? At least to me, this was not obvious initially.

2. Is it possible to allow Help to be displayed honoring the settings in `display-buffer-alist`?

Attempts at doing 2.
------------------------------

A. I thought that the Help buffer could have been shown in a window next to (to the right of) the Transient window by using `slot`. For example, I tried setting `(slot . -10)` in `transient-display-buffer-action`  (as I set the `slot` for Help to -1), but this did not work.  (I routinely do this with, say, Help and Messages and compilation and Helm, and can display all at the bottom, with `display-buffer-in-side-window`, by using different values of `slot`).

Now I think the above cannot work because the side window that is created by transient is hidden when we `C-h`. I've tried forcing the transient window to not disappear when I `C-h`, but I do not know how to do it. Changing `no-other-window` to `nil` did not prevent this.

Alternatively, I can circumvent the problem in a couple of ways:

B. Have `transient-display-buffer-action`'s side window be, for example, `(side . top)`  (but I do not like that at all: I am used to expecting all my Magit and transient stuff in a particular place).

C. Instead of `display-buffer-in-side-window` use, for example, `display-buffer-below-selected` (or ` display-buffer-at-bottom`). But with these options, a *Messages* window is shown below (or above) the `Transient` buffer, and it does not disappear when we exit transient. If we change the settings for `transient-display-buffer-action`:

```
(setq transient-display-buffer-action
      '((display-buffer-below-selected)))
```

This works. But window height is not restored, a window with the *Messages* buffer is shown below the Transient window, and this new Messages window remains after exiting Transient.

So neither B. nor C. are really solutions to the original issue.

## Edit: versions
- transient, 20240101.2225
- Emacs, 29.1.90 (custom built, in Debian)

**Comment by tarsius** [comment]
Thanks for the report.

I would still like to figure out why the request to make the window dedicated is being ignored, but don't have the motivation to do that right now. So instead I am opting for being more careful when trying to kill the transient buffer.

**Comment by rdiaz02** [comment]
Thanks a lot. Works perfectly now.
