### ISSUE TITLE
Messages shown when toggling minor modes are not shown when a transient prefix is being used

### ISSUE THREAD

**Issue by rdrg109** [magit/transient#272]
# what behavior you expected

Messages that are shown when enabling or disabling minor modes are shown in the minibuffer when a transient prefix is being used.

# what behavior you observed

Messages that are shown when enabling and disabling minor modes are not shown when a transient prefix is being used.

It is worth mentioning that when transient calls a function that explicitly calls `message`, the message is shown in the minibuffer, so I believe the issue is with those messages that are shown when toggling minor modes.

# and how we can reproduce the issue.

I've defined the following simple functions to help me explain this bug report.

```emacs-lisp
(defun my/a ()
  (interactive)
  (message "You called my/a."))

(defun my/b ()
  (interactive)
  (message "You called my/b."))
```

I've defined an hydra and a transient prefix (see code block below). Both `my/hydra-1/body` and `my/transient-1` call the same functions (I call `my/hydra-1/body` because the macro `defhydra` creates multiple commands, among them a command with suffix `/body` which is the actual interactive function). The message shown by the functions `my/a` and `my/b` are shown when using either of them.

```emacs-lisp
(defhydra my/hydra-1 ()
  ""
  ("a" my/a)
  ("b" my/b))

(transient-define-prefix my/transient-1 ()
  :transient-suffix 'transient--do-stay
  :transient-non-suffix 'transient--do-warn
  [("a" "Call my/a" my/a)
   ("b" "Call my/b" my/b)])
```

Now, I've defined an hydra and a transient prefix for tofggling modes that I commonly use.

When calling `my/hydra-2/body`, the message area shows the messages stating whether the minor mode has been enabled or disabled (e.g. "Display-Line-Numbers mode enabled in current buffer", "Electric-Quote mode enabled", "Outline minor mode enabled in current buffer", "Highlight-Indentation mode enabled in current buffer"). However, the function `my/transient-2` doesn’t show such messages. I believe that the expected behavior is that such messages are shown by `my/transient-2`.

```emacs-lisp
(defhydra my/hydra-2 ()
  "This is the docstring."
  ("l" display-line-numbers-mode)
  ("e" electric-quote-mode)
  ("o" outline-minor-mode)
  ("h" highlight-indentation-mode))

(transient-define-prefix my/transient-2 ()
  :transient-suffix 'transient--do-stay
  :transient-non-suffix 'transient--do-warn
  [("l" "display-line-numbers-mode" display-line-numbers-mode)
   ("e" "electric-quote-mode" electric-quote-mode)
   ("o" "outline-minor-mode" outline-minor-mode)
   ("h" "highlight-indentation-mode" highlight-indentation-mode)])
```

# M-x magit-version

Magit 3.3.0-7.dda332b, Transient 0.5.3, Git 2.41.0, Emacs 29.1, gnu/linux

**Comment by tarsius** [comment]
Mode toggling commands defined with `define-minor-mode` use `(called-interactively-p 'any)` to decide whether to display that message. Unfortunately `called-interactively-p` is not reliable. For example, it does not return the right value when the command is advised. Unfortunately Transient has no choice but to temporarily advice the current command, to work around another Emacs defect. (`post-command-hook` isn't actually guaranteed to be called after the command, but we absolutely need that. So we have to use an advice instead.)

From `called-interactively-p`'s docstring:

```
This function is very brittle, it may fail to return the intended result when
the code is debugged, advised, or instrumented in some form.  Some macros and
special forms (such as `condition-case') may also sometimes wrap their bodies
in a `lambda', so any call to `called-interactively-p' from those bodies will
indicate whether that lambda (rather than the surrounding function) was called
interactively.

Instead of using this function, it is cleaner and more reliable to give your
function an extra optional argument whose `interactive' spec specifies
non-nil unconditionally (\"p\" is a good way to do this), or via
\(not (or executing-kbd-macro noninteractive)).

The only known proper use of `interactive' for KIND is in deciding
whether to display a helpful message, or how to display it.  If you're
thinking of using it for any other purpose, it is quite likely that
you're making a mistake.  Think: what do you want to do when the
command is called from a keyboard macro?
```

So I don't think anything can be done about this. The good news is that the worst that should ever happen, is that some message isn't shown. (The other bad news being that not everyone knows about this, so `called-interactively-p` is also being used for more important things.)

Actually, you could open a bug on debbugs and suggest they replace `called-interactively-p` with `(not (or executing-kbd-macro noninteractive))` in `define-minor-mode`.
