### ISSUE TITLE
C-z no longer invokes transient-suspend

### ISSUE THREAD

**Issue by tvraman** [magit/transient#276]
I no longer seem to be able to invoke transient-suspend; something I do when learning a new transient menu so I can review the keys using speech. I see transient-suspend being bound in transient-base-map and lookup-key tells me it's there, but C- doesn't do what it used to with respect to suspending the transient. This is under Emacs 30

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:

Everything you say is correct.

The one place where I still would like to ppause the transient and
examine the choices  is to review the keys because:

1. TTS is ambiguous C vs Z
2. Lower vs upper case -- and always saying "capital" gets annoying
3. I discovered that pressing '?' twice gives me the behavior I want re
   examining the cache I keep -- so I'll just update the docs at my end.
   > C-z still invokes transient-suspend. When you suspend a transient
> menu, that does not only suspend the transient keymaps, it also stops
> displaying the transient buffer. I am pretty sure it always worked
> like that.
>
> Looking at past issues you opened, it doesn't seem like you were
> "suspending" transients in order to inspect them (expect maybe in the
> very beginning, when things didn't work properly yet).
>
> Nowadays you can move through the buffer using up and down. No prior
> setup required for basic support. transient-enable-popup-navigation
> must be non-nil, but that's the default now. You should also enable
> transient-force-single-column, to avoid some actions being cycled in a
> surprising order. I think we have already established all that in the
> past.
>
> Currently up and down skip over section heading, they just jump
> between buttons. That's something that could be improved, if you tell
> me it would be useful to you. Might take a while for me to get to it
> though, as I am rather busy with other things.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

--

**Comment by tarsius** [comment]
> 1. TTS is ambiguous C vs Z

I don't understand that at all.

> 2. Lower vs upper case -- and always saying "capital" gets annoying

Here I am also not sure what you are getting at.

> 3. I discovered that pressing '?' twice gives me the behavior I want re
>    examining the cache I keep -- so I'll just update the docs at my end.

For most of magit's menus doing that shows you the manpage for the respective git command. If that's what you want, I must have completely misunderstood what you are trying to do.

I thought you wanted to move through the menu to learn what commands and arguments are available and what keys you have to press to invoke them. Leaning about the underlying git command by jumping to its manpage is of course related, but it does not tell you what subset of commands is actually available in magit's menu, and while the key binding for an argument usually matches the arguments "name" (i.e., that you would have to type in a terminal), there are exceptions to that rule.

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:

Jonas -- Sorry for the confusion I apparently caused, I'll explain below
and close the issue.

1. Using emacspeak and per our prior discussion a few months ago, the
   menus all talk correctly, no issue.
2. TTS==Text To Speech.
3. So navigating the menus, I hear "c <cmd>" and similar.
4. When encountering a new transient -- most recently journalctl mode,
   it's not always obvious if the speech synthesizer said "c" or "z" --
   letter synthesis in isolation ie with no context is ambiguous.
5. Normally if I hit the above  as a blind user, I'd eview the text,
   that is not possible with the transient menus.
6. The work-around is to browse the cached transient menu  (you saw that
   hack in the past), and I used to get at that via C-z.
7. Now that doesn't seem to do it, but hitting ? once gives the man
   page, and the second "?" magically displays the cache I built
8. The above is a kluge which I am ure will break in the future.

   

>     1 TTS is ambiguous C vs Z
>
> I don't understand that at all.
>
>     2 Lower vs upper case -- and always saying "capital" gets annoying
>
> Here I am also not sure what you are getting at.
>
>     3 I discovered that pressing '?' twice gives me the behavior I
>       want re
>       examining the cache I keep -- so I'll just update the docs at my
>       end.
>
> For most of magit's menus doing that shows you the manpage for the
> respective git command. If that's what you want, I must have
> completely misunderstood what you are trying to do.
>
> I thought you wanted to move through the menu to learn what commands
> and arguments are available and what keys you have to press to invoke
> them. Leaning about the underlying git command by jumping to its
> manpage is of course related, but it does not tell you what subset of
> commands is actually available in magit's menu, and while the key
> binding for an argument usually matches the arguments "name" (i.e.,
> that you would have to type in a terminal), there are exceptions to
> that rule.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

--
