### ISSUE TITLE
Regression in transient-define-prefix without static items

### ISSUE THREAD

**Issue by jmpunkt** [magit/transient#277]
## Expecting

Using `transient-define-prefix` with `:setup-children` should not fail if there are no static items.

## Observing

Starting with Transient (0.5.3, rev 72cf67d7e047a4f82e0e18bd016c7826bf2efde0) it is not possible to use `:setup-children` without any static item. Opening a menu which only contains dynamic items results the in following backtrace.

```
Debugger entered--Lisp error: (invalid-slot-name "#<transient-suffix transient-suffix-146f9ee>" pad-keys)
  transient--exit-and-debug(error (invalid-slot-name "#<transient-suffix transient-suffix-146f9ee>" pad-keys))
  signal(invalid-slot-name ("#<transient-suffix transient-suffix-146f9ee>" pad-keys))
  slot-missing(#<transient-suffix transient-suffix-146f9ee> pad-keys oref)
  eieio-oref(#<transient-suffix transient-suffix-146f9ee> pad-keys)
  transient--maybe-pad-keys(#<transient-suffix transient-suffix-146f9ee> #<transient-columns transient-columns-87d0e9>)
  #f(compiled-function (column) #<bytecode -0xfac99e96764454d>)(#<transient-suffix transient-suffix-146f9ee>)
  mapcar(#f(compiled-function (column) #<bytecode -0xfac99e96764454d>) (#<transient-suffix transient-suffix-146f9ee>))
  #f(compiled-function (group) #<bytecode -0x181327d2777c6a26>)(#<transient-columns transient-columns-87d0e9>)
  apply(#f(compiled-function (group) #<bytecode -0x181327d2777c6a26>) #<transient-columns transient-columns-87d0e9>)
  #f(compiled-function (&rest args) #<bytecode -0x1fd26c5fce8b7bce>)(#<transient-columns transient-columns-87d0e9>)
  #f(compiled-function (cl--cnm group) #<bytecode 0x88629a175cda410>)(#f(compiled-function (&rest args) #<bytecode -0x1fd26c5fce8b7bce>) #<transient-columns transient-columns-87d0e9>)
  apply(#f(compiled-function (cl--cnm group) #<bytecode 0x88629a175cda410>) #f(compiled-function (&rest args) #<bytecode -0x1fd26c5fce8b7bce>) #<transient-columns transient-columns-87d0e9>)
  #f(compiled-function (group) "Insert GROUP's description, if any." #<bytecode 0x1222508b7247048a>)(#<transient-columns transient-columns-87d0e9>)
  apply(#f(compiled-function (group) "Insert GROUP's description, if any." #<bytecode 0x1222508b7247048a>) #<transient-columns transient-columns-87d0e9> nil)
  transient--insert-group(#<transient-columns transient-columns-87d0e9>)
  transient--insert-groups()
  transient--show()
  transient--redisplay()
  transient-setup(test-menu2)
  test-menu2()
  funcall-interactively(test-menu2)
  command-execute(test-menu2 record)
  execute-extended-command(nil "test-menu2" "test-menu2")
  funcall-interactively(execute-extended-command nil "test-menu2" "test-menu2")
  command-execute(execute-extended-command)
```

Transient (0.5.2, built-in) works fine with Emacs (29.2 and 30 rev 1687adcb5c93b490e2e7edcd14615af295e791ed).

## Reproduce

```elisp
(transient-define-prefix test-menu ()
  "test-menu"
  ["Menu"
   :setup-children
   (lambda (_)
     (list
      (transient-parse-suffix
       transient--prefix
       '("a" "a-desc" (lambda () (interactive) (message "a"))))))])

(transient-define-prefix test-menu2 ()
  "test-menu"
  ["Menu"
   :setup-children
   (lambda (_)
     (list (transient-parse-suffix
            transient--prefix
            '("a" "a-desc" (lambda () (interactive) (message "a"))))))
   ("b" "b-desc" (lambda () (interactive) (message "b")))])
```

Running `test-menu` will fail with the previously mentioned error message. Now if we put any additional static item into the menu (like `test-menu2`), then it works as intended.

## Note

The Biome package (https://github.com/SqrtMinusOne/biome/blob/bc4f229c74c725a4981b4a5eab21674ac5097116/biome-query.el#L1019) relies on this behavior.

**Comment by tarsius** [comment]
Thanks for the report!

> Starting with Transient (0.5.3, rev https://github.com/magit/transient/commit/72cf67d7e047a4f82e0e18bd016c7826bf2efde0)

How did you come to that conclusion? I bisected it to 0ab20d065df79d808124f08fece99b84784cc187, which comes after 0.5.3.

---

This was a change in undefined behavior. That change was unintentional, so I reverted it. However the real issues was that it was not documented that one should also specify `:class` when using `:setup-children`. See beecdc85799231338314bd20292f71fc8cd687e8 for details.

Additionally I noticed that you pass the value of `transient--prefix` as PREFIX. That is wrong because a symbol is expected and `transient--prefix` is an object. See 03e752d977cb2ed33930914425e108d60237443d.

Finally, I would suggest using `transient-parse-suffixes` instead of `transient-parse-suffix` several times. See `notmuch-search-menu` in the `notmuch-transient` package for an example.

**Comment by jmpunkt** [comment]
Thanks for the fast fix and detailed feedback.

> How did you come to that conclusion? I bisected it to 0ab20d065df79d808124f08fece99b84784cc187, which comes after 0.5.3.

I tested the built-in version which worked. The Elpa package (0.5.3), installed in a clean Emacs instance (emacs -Q), did not work. I concluded the change was introduced in 0.5.3.
