### ISSUE TITLE
Empty transient

### ISSUE THREAD

**Issue by theldoria** [magit/transient#28]
I recently had the problem that my magit log transient was completely empty. The reason was that I had set the transient level to 0 while playing with transient for the first time.

Now, after a week or two of working with another computer, I completely forgot and wondered why the logarithmic transient seemed dysfunctional.

With `? ` doesn't help, because I don't have a `man` under Windows (even the first `` doesn't seem to do anything).

I couldn't remember the level set command either.

So it would probably be a good idea to have it:
- and an indication that the level is 0 and how to change the level if there is nothing in the transient.
- Do you have a quick help (or is it supposed to show something?)?

**Comment by tarsius** [comment]
I just don't update very often. Packages from Github are updated about once every ten days and others less often. But feel free to ask me to pull when you need an update.

I fixed the urls.
