### ISSUE TITLE
emoji--define-transient: Wrong number of arguments: #<subr transient--expand-define-args>, 1

### ISSUE THREAD

**Issue by joostkremers** [magit/transient#288]
I'm using Emacs 29.3, with transient installed from Melpa as a dependency of magit. That version of transient seems to be incompatible with `emoji-insert`, though.

The reason, I suspect, given the error message in the subject line, is that the signature of `transient--expand-define-args` has changed. The version coming with Emacs 29.3 has:

```
(defun transient--expand-define-args (args &optional arglist)
  ...
```

While the version installed from Melpa has:

```
(defun transient--expand-define-args (args arglist form &optional nobody)
  ...
```

Recipe to reproduce:

```
$ emacs -Q -L .emacs.d/elpa/seq-2.24 -L .emacs.d/elpa/compat-29.1.4.5 -L .emacs.d/elpa/transient-20240618.1413/
```

Then in Emacs:

```
M-: (require 'transient) RET
C-x 8 e e
```

**Comment by tarsius** [comment]
> The reason, I suspect, given the error message in the subject line, is that the signature of `transient--expand-define-args` has changed.

I thought about this when I made the change and, apparently incorrectly, concluded that it doesn't matter. This function is only used at macro expansion time, and the implementations of the macros and this function should be coming from the same version of the package and thus agree on the function signature. But this could be a problem if the code is not compiled, and maybe even if it is. I'll probably have to make these arguments optional again.

**Comment by tarsius** [comment]
`emoji.el` from 29.3 lacks commit [af94369f90a5d3ad44dcc80d205665ccb2d41995](https://github.com/emacsmirror/emacs/commit/af94369f90a5d3ad44dcc80d205665ccb2d41995) and thus still calls the *internal* `transient--expand-define-args` directly.

**Comment by joostkremers** [comment]
Just got the update and `emoji-insert` is working again. Thanks!
