### ISSUE TITLE
init fails with latest update

### ISSUE THREAD

**Issue by dasoju** [magit/transient#294]
hi
emacs init fails with the following error
Symbol's function definition is void: static-if

i see its erroring out due to following in the transient package
transient.el:(static-if (>= emacs-major-version 30) ;transient--wrap-command

Not sure where static-if is defined, I am using emacs 29.1 (mitsuharu version)

**Comment by tarsius** [comment]
`static-if` is new in Emacs 30. For released versions of Emacs it is available in the `compat` package, version 30.0.0.0. `transient` depends on that version of `compat`.

When you updated `transient`, your package manager should also have updated `compat`.

Maybe it did, and all you have to do is to restart Emacs.

Maybe it didn't, and you have to manually update.

(What package manager are you using?)
