### ISSUE TITLE
transient--stack is always nil in 0.7.3

### ISSUE THREAD

**Issue by kickingvegas** [magit/transient#296]
# Description

The variable `transient--stack` is used by casual-lib to track if the menu has a parent menu. This logic seems to broken in the 0.7.3 release where I am finding its value always to be nil, regardless of how much nesting of menus is done.

The usage of `transient--stack` in `casual-lib` is here: <https://github.com/kickingvegas/casual-lib/blob/a7b4a576f01fa227aaff074e0ef2778cdd06fc5d/lisp/casual-lib.el#L123>

### Environment

Emacs 29.4

### Steps to Reproduce

1.  With the Casual Dired package, invoke the menu `casual-dired-tmenu`.
2.  Press “,” to invoke the settings menu.

### Expected Result

At the bottom navigation, one should see the label “‹Back” next to the binding “C-g”.

### Actual Result

At the bottom navigation, the label “Dismiss” is shown instead.

**Comment by kickingvegas** [comment]
Related to guidance provided here https://github.com/magit/transient/discussions/290

**Comment by tarsius** [comment]
Currently `casual-lib--quit-one-suffix-label` is evaluated once, when `casual-lib-quit-one` is being defined. Fix it like so:

```diff
@@ -139,7 +139,7 @@ (transient-define-suffix casual-lib-quit-one ()
   :transient nil
   :key "C-g"
   :if-not #'casual-lib-hide-navigation-p
-  :description (casual-lib--quit-one-suffix-label)
+  :description (lambda () (casual-lib--quit-one-suffix-label))
   (interactive)
   (transient-quit-one))
```

**Comment by kickingvegas** [comment]
Thanks for the fix on my side! Will implement.
