### ISSUE TITLE
setting levels from elisp code

### ISSUE THREAD

**Issue by wbolster** [magit/transient#31]
hi,

first of all, thanks for working on this fancy library!

that said, i'm wondering what the right way to set custom levels for some transient commands from elisp code, in particular from my `init.el` file.

i see there's a `transient-levels` variable which looks like this:

```
((magit-log
  (transient:magit-log:--first-parent . 1)
  (transient:magit-log:--no-merges . 1)))
```

but i'm not sure how to modify it.

i see transient uses an additional config file that is used when levels are changed interactively, but i very much prefer to keep all my configuration in one place instead.

i tried to find this in the manual and even in the source code, but couldn't find the answer, hence this issue.

thanks in advance!

**Comment by tarsius** [comment]
> i'm wondering what the right way to set custom levels for some transient commands from elisp code

Something like this should work:

```lisp
(setf (alist-get 'transient:magit-log:--first-parent
                 (alist-get 'magit-log transient-levels))
      1)
```

> i see transient uses an additional config file that is used when levels are changed interactively, but i very much prefer to keep all my configuration in one place instead.

That is not possible to not use a separate file.

I recommend my `no-littering` package to keep this package and others from littering `~/.emacs.d`.

**Comment by wbolster** [comment]
thanks, i use `no-littering` but i still don't like that _config_ (not state!) is outside my `init.el`.

would this something that would warrant better first-class api support in  `transient.el`, e.g. a helper that does what you suggested?

**Comment by wbolster** [comment]
e.g. something like this:

```
  (defun transient-set-suffix-level (command suffix level)
    (setf
     (alist-get
      (intern (format "transient:%S:%s" command suffix))
      (alist-get command transient-levels))
     level))
```

(not sure i use the correct  terminology, i'm new to `transient.el`)

**Comment by wbolster** [comment]
e.g. something like this:

```
  (defun transient-set-suffix-level (command suffix level)
    (setf
     (alist-get
      (intern (format "transient:%S:%s" command suffix))
      (alist-get command transient-levels))
     level))
```

which can be called like this:

```
  (transient-set-suffix-level 'magit-log "--first-parent" 3)
```

(not sure i use the correct  terminology, i'm new to `transient.el`)

**Comment by tarsius** [comment]
Probably not. If you manipulate the levels using code, then you partially lose the ability to do it interactively, i.e. interactive changes remain in effect for the current Emacs session, but might be overwritten when the init file is loaded. For levels this might not matter that much, but for values this would be very confusing (and once this is supported for levels the request for doing the same for values is only a matter of time). For that reason I do not want to make it easy for users to customize these things using code. It would result in a support burden.

**Comment by wbolster** [comment]
so do i understand correctly that you would suggest to put `.../etc/transient/*` under version control instead, as the arguably) ‘better’ alternative? or is there another approach i overlooked?

**Comment by tarsius** [comment]
Yes, I would recommend doing that. I don't think there is another approach.
