### ISSUE TITLE
if-derived slot doesn't work with lists

### ISSUE THREAD

**Issue by Thaodan** [magit/transient#314]
# What behavior you expected
  Using the `if-derived` selector works similarly as `(derived-mode-p)`
# What behavior you observed
  Selector does not match at all when using it with a table such as `:if-derived '(text-mode prog-mode)`
# How we can reproduce the issue
  Have an object that use the selector such as I have [here](https://github.com/Thaodan/emacs.d/blob/master/init.org#transient). 
  Add `:if-derived '(prog-mode text-mode)` to the text suffix.

**Comment by tarsius** [comment]
Once you drop the quote it works.

**Comment by Thaodan** [comment]
Can you explain why? Not exactly getting the syntax here.

**Comment by tarsius** [comment]
We are inside a vector so nothing has to be quoted.

**Comment by Thaodan** [comment]
Thanks for explaining

**Comment by tarsius** [comment]
Of course there is some custom parsing going on, else embedded lambda would not get compiled and `,` would not work in some places, but for the most part you can just treat this like any other vector. After all, the lambda would also work if we failed to compile them, and the `,` trick is discouraged and might be removed in the future.

**Comment by Thaodan** [comment]
Are you referring to the use of , to call a macro in one of my
transients?
I figured it would be the best way to avoid writing a lambda manually in
each item or writing a function for each item for such as simple
transient.

**Comment by tarsius** [comment]
Yes, but I wasn't trying to say you stop using that now, just that you might have to make adjustments eventually. (Probably you won't.)

But there are alternative approaches. You could define a new suffix class, see `forge--topic-set-state-command` for an example. In this case all the suffixes that use it are defined using `transient-define-suffix`. That's a bit verbose, but for a package used by others, it is appropriate.

**Comment by Thaodan** [comment]
Jonas Bernoulli ***@***.***> writes:

> Yes, but I wasn't trying to say you stop using that now, just that you
> might have to make adjustments eventually. (Probably you won't.)

No problem, I didn't understand it that way. I just try to highlight how
it makes it very easy to define such as small but no less useful
transients.

> But there are alternative approaches. You could define a new suffix
> class, see `forge--topic-set-state-command` for an example. In this
> case all the suffixes that use it are defined using
> `transient-define-suffix`. That's a bit verbose, but for a package
> used by others, it is appropriate.

Thanks I will look at these. However for defining transients for small
custom menus inside init.el it does sound like an overkill.

**Comment by tarsius** [comment]
Yeah, its useful in such cases. Not recommended for packages but for private tools okay. (I think I used it *once* in one of my packages but have since removed that.)

It's also not like preserving this feature complicates the implementation.  That's the code in full:

```lisp
(pcase key
  ...
  ((guard (eq (car-safe val) '\,))
   (use key (cadr val)))
  ...)
```

:grinning: 

The problem is more with the documentation (it calls the whole "nothing has to be quoted inside these vectors" into question -- case in point, your initial inquiry).

And it can lead to me having to justify why unquoting is only available in the value of a keyword, but not as a "positional argument" earlier in the suffix specification. (More or less something along the lines "it would be harder/noisier to support it there as well, and it isn't actually necessary".)

**Comment by Thaodan** [comment]
Jonas Bernoulli ***@***.***> writes:

> Yeah, its useful in such cases. Not recommended for packages but for private tools okay. (I think I used it *once* in one of my packages but have since removed that.)
>

It's very useful to expand transient with macros to expand it on the fly
for such definitions such as toggles. I guess a way to avoid macros
would be to define classes for these sorts of things in advance so they
could be done without macros.

> It's also not like preserving this feature complicates the implementation.  That's the code in full:
>
> ```lisp
> (pcase key
>   ...
>   ((guard (eq (car-safe val) '\,))
>    (use key (cadr val)))
>   ...)
> ```
>
> :grinning:

That looks very simple.

>
> The problem is more with the documentation (it calls the whole "nothing has to be quoted inside these vectors" into question -- case in point, your initial inquiry).
> And it can lead to me having to justify why unquoting is only available in the value of a keyword, but not as a "positional argument" earlier in the suffix specification. (More or less something along the lines "it would be harder/noisier to support it there as well, and it isn't actually necessary".)

To be honest in my case I didn't read the manual careful enough. I
glanced over it a little bit while trying to see if Transient wasn't an
overkill compared to Hydra but didn't read it carefully except a few sections.

But in general the whole rules regarding quoting and forming lists in Lisp is
something to get used to.
In other languages the syntax would be the same no matter the context.

That I could only call a function while using the keyword instead of
positional arguments was actually quite easy to understand.

Further the whole declarative syntax of Transient is easier to read
compared to Hydras.

Just looking at lets say Magit at first makes it look very complicated
but it doesn't have to be for simpler use-cases.
The Transient showcase was quite good for learning more simpler
examples.
It would be very useful inside the transient manual.
