### ISSUE TITLE
Can't see help command in magit: traced to -reductions-from

### ISSUE THREAD

**Issue by ZenAnnard** [magit/transient#32]
When I try to show the help commands in magit, I see the following error:
`Symbol’s function definition is void: -reductions-from`

Using ag in my ~/.emacs.d/elpa folder I see the following:

```
transient-20190319.1928/transient.el
2388:         (cc (-reductions-from (apply-partially #'+ 3) 0 cw)))

dash-20190320.1406/dash.el
287:(defun -reductions-from (fn init list)
300:See also: `-reductions-from', `-reductions-r', `-reduce-r'"
301:  (and list (-reductions-from fn (car list) (cdr list))))
2741:                             "-reductions-from"
```

In transient it is this line: https://github.com/magit/transient/blob/9e30038d2d69e4ad0f3333777137af52e4771442/lisp/transient.el#L2388

Is there a missing 'require'?

**Comment by tarsius** [comment]
`-reductions-from` is defined in `dash`, which `transient` dies require. Check if `load-path-shadow-find` reports that you have multiple versions of `dash` installed.

**Comment by ZenAnnard** [comment]
Maybe I should add I'm using spacemacs.

So with `list-load-path-shadows` (your command I couldn't find) I discovered there were several dash versions. So I removed all of them, added `dash` as a layer in my `.spacemacs` file and restarted emacs. Now it works. Thank you!
