### ISSUE TITLE
Scope does not always reset after exiting Transient menu

### ISSUE THREAD

**Issue by aurtzy** [magit/transient#323]
## Info

System: Guix System

Emacs version: GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)

Magit version: Magit 4.1.1, Transient 0.7.7, Forge 0.4.4, Git 2.46.0, Emacs 29.4, gnu/linux

Tested on `emacs -Q`.

## Expectation

For Transient scope to always be nil when initializing a new Transient prefix menu (no parents).

I'm working on a package that integrates with `project.el`, and have a function that goes through various methods to get the root directory of the "current project", with the scope being one of the places that are searched.  This function cannot be used as-is for Transient setup in prefixes, however, because it will find that the scope is still set in certain cases and use it even when it is no longer relevant.

The function searches in the following order: an override directory without prompting if set, then scope, then the {default-}directory and prompting if allowed+needed.

One use case:
1. User opens the Transient menu in a project.  The function falls back to `default-directory` since scope is not set and no override is used.  Expect root directory to be a parent of `default-directory`.
2. User executes a suffix to find a file.
3. When the user opens the menu again, the expectation is the menu displays the root directory of the project of the current buffer's `default-directory`; this does not always seem to be the case, however.

Have I misunderstood something about Transient scope?  Is there something else I could use that would better fit this use case?

## Steps to reproduce

After evaluating the definition below:
1. Execute the prefix command, opening a Transient menu.  Note that scope value is nil on initial menu open.
2. Press "f" to execute the "Find a file" suffix, exiting the menu and getting prompted.
3. Execute prefix command again after the prompt is closed by quitting or opening a file.  Notice that the scope value is unexpectedly non-nil.

This appears to happen specifically when the exiting suffix has a prompt.  The result is expected (nil scope on subsequent open) when pressing "d".

```emacs-lisp
(transient-define-prefix test-prefix ()
  ["Test commands"
   ("f" "Find a file" find-file)
   ("d" "Dired" (lambda () (interactive) (dired ".")))]
  (interactive)
  (message "Scope value: %s" (and (transient-prefix-object) (transient-scope)))
  (transient-setup
   'test-prefix nil nil
   :scope "A scope value"))
```

## Workaround

I'm currently getting around this with a `force-init?` argument in my scope setup function that ignores the current scope.  It works, but I only apply it my top-level prefix - I can't apply this to its sub-prefixes, else they wouldn't respect the current project values in the scope (and I can only get away with the former since it's not likely to be a sub-prefix).

**Comment by tarsius** [comment]
This is a bug in Transient. I have pushed a fix to the `fix-323` branch, but it is bed time now and I have to think about it more.
