### ISSUE TITLE
3 letter binding results in wrong description being used

### ISSUE THREAD

**Issue by brabalan** [magit/transient#324]
Following the advice from #284, I defined the following function and transient (the actual one is much longer):
```emacs-lisp
(defun my-kc ()
  (interactive)
  (insert (oref (transient-suffix-object) description)))

(transient-define-prefix my-test () "test"
  [("aa" "A" my-kc)
   ("bbb" "B" my-kc)
   ])
```

Everything works well for bindings up to 2 letters, but as soon as I use a 3 letters bindings (as in `bbb`), the description from the first binding is used instead (here "A").

To reproduce:
- invoke `my-test`
- type `bbb`
- notice that "A" is inserted instead of "B"

I have updated transient to the current git version, using this in my elpaca config (I restarted emacs to make sure it was taken into account):
```emacs-lisp
(use-package transient :ensure (:fetcher github :repo "magit/transient" :wait t))
```

**Comment by tarsius** [comment]
This is a bug in Transient. I have pushed a fix to the `fix-324` branch, but I don't fully understand why that is necessary yet and have to attend to other emergencies now.
