### ISSUE TITLE
Cannot bind `scroll-up-command`: `BUG: Cannot determine suffix object`

### ISSUE THREAD

**Issue by joostkremers** [magit/transient#325]
I have a transient that binds `scroll-up-command` as a suffix. It was working fine until two days ago, but since commit d9ced84 it produces the error in the subject line.

This is what the backtrace buffer says:

```
Debugger entered--Lisp error: (error "BUG: Cannot determine suffix object")
  transient--exit-and-debug(error (error "BUG: Cannot determine suffix object"))
  error("BUG: Cannot determine suffix object")
  transient-suffix-object(transient-scroll-up)
  transient--make-transient-map()
  transient--init-keymaps()
  transient--init-transient(jk-move-transient nil nil)
  #f(compiled-function () #<bytecode -0xa92d4bd2c556ace>)()
  transient--env-apply(#f(compiled-function () #<bytecode -0xa92d4bd2c556ace>) #<transient-prefix transient-prefix-19139f430230>)
  transient-setup(jk-move-transient)
  jk-move-transient()
  funcall-interactively(jk-move-transient)
  command-execute(jk-move-transient)
```

This is the transient in question:

```
(transient-define-prefix jk-move-transient ()
  :transient-non-suffix #'transient--do-leave
  [[" Scroll"
    ("SPC" "" scroll-up-command           :transient t)
    ("C-v" "" scroll-up-command           :transient t)
    ("<backspace>" "" scroll-down-command :transient t)
    ("M-v" "" scroll-down-command         :transient t)
    ("<up>" "" scroll-up-line             :transient t)
    ("<down>" "" scroll-down-line         :transient t)
    ("<left>" "" scroll-right             :transient t)
    ("<right>" "" scroll-left             :transient t)]

   ["   Move"
    :pad-keys t
    ("g" "Top of buffer" beginning-of-buffer)
    ("M-g" "End of buffer" end-of-buffer)
    ("l" "Goto line" consult-goto-line)
    ("m" "Goto mark" consult-mark)
    ("o" "Outline" consult-outline)
    ("z" "Avy line" avy-goto-line)]

   ["   Register"
    ("b" "Point to register" point-to-register :transient t)
    ("j" "Jump to register" jump-to-register)]])
(bind-key "M-g" #'jk-move-transient)
```

If I comment out the two bindings for `scroll-up-command`, the transient starts working again. I have no idea why `scroll-up-command` has this effect, especially since `scroll-down-command` works fine...

**Comment by tarsius** [comment]
This is a regression introduced in 1b7f9be7b9fbc8acb5d71f028b19e1f78d9dd090.  I hesitated to do that (especially so shortly before a release), but I figured that if the dropped fallback behavior actually served a purpose, someone would run into it and report it.  I am glad that happened so quickly.

This issue triggered in this case because you added two bindings for a command **and** one of those bindings happens to conflict with a built-in binding (`C-v` is bound to `transient-scroll-up` in `transient-base-map`).

I've fixed the regression so now you won't get the above error anymore.  But `C-v` either won't to what you expect it to do or, if you `(setq transient-detect-key-conflicts t)`, you will get an error about the conflict.

**Comment by joostkremers** [comment]
Thanks for the quick reply and fix!

> This is a regression introduced in [1b7f9be](https://github.com/magit/transient/commit/1b7f9be7b9fbc8acb5d71f028b19e1f78d9dd090).

Yes, for some reason I copied the wrong commit hash...

> I've fixed the regression so now you won't get the above error anymore. But `C-v` either won't to what you expect it to do or, if you `(setq transient-detect-key-conflicts t)`, you will get an error about the conflict.

I applied the patch, and `C-v` seems to work fine. It scrolls the buffer like I expect.

Anyway, I don't really use that part of the transient, so if I end up having to remove those bindings, it's no big loss.

**Comment by tarsius** [comment]
> I applied the patch, and `C-v` seems to work fine. It scrolls the buffer like I expect.

Ah, right. It's the other way around; your binding wins because it is in the most local keymap. I.e., instead you lose the ability to scroll the *transient window* using `C-v` (which is okay if you don't care about and don't distribute this menu for others to use).
