### ISSUE TITLE
Minibuffer is unable to resize if transient-display-buffer-action sends the buffer to a left/right side-window

### ISSUE THREAD

**Issue by pestctrl** [magit/transient#328]
I have the following in my init.el: 
```
(setq transient-display-buffer-action
        '(display-buffer-in-side-window
          ;; Display in left side-window
          (side . left)
          (dedicated . t)
          (inhibit-same-window . t)
          (window-parameters (no-other-window . t))))
```
Whenever I do this, the minibuffer is stuck being 1 character tall. After setting the above variable, I can define the following transient: 
```
(defun cmake-read-generator (prompt &optional initial-input history)
  (format "\"%s\""
          (completing-read
           "Hello\nworld: "
           '("Ninja"
             "Unix Makefiles")
           nil nil initial-input history)))

(transient-define-argument cmake:-G ()
  :description "Generator"
  :class 'transient-option
  :key "-G"
  :argument "-G "
  :reader #'cmake-read-generator)

(transient-define-prefix cmake-transient ()
  "Test Transient Title"
  ["Arguments"
   (cmake:-G)]
  ["Actions"
   ("a" "Action a" test-function)])
```
And the minibuffer prompt will be cut off, because there's a newline in the prompt. 

That by itself wouldn't bother me too much, but in addition to that, the way vertico renders candidates by default is useless now because the minibuffer can't seem to resize.

Is this a problem with transient? Or could it be a problem with Emacs itself?

**Comment by tarsius** [comment]
Updating Transient to a version that includes https://github.com/magit/transient/commit/5478d4e6a73daa6bf0dcaad6cf4767ee4a1589ec should fix that (also see https://github.com/minad/vertico/issues/532).

**Comment by pestctrl** [comment]
Thank you! Sorry for the noise.
