### ISSUE TITLE
Possible regression in transient-scope when called without arguments

### ISSUE THREAD

**Issue by aurtzy** [magit/transient#329]
## Problem

The behavior of `transient-scope` when called without arguments in a suffix command appears to have changed in commit 4de5812992ef93fcd80ef1d12a6e1db7f7cd315d.

## Expected behavior

For `transient-scope` to return the scope from the current prefix when called without arguments.

I see that it's been noted in the changelog it's discouraged for suffix commands (and I was looking forward to using the argument for some design improvements when I saw it today anyways), but it wasn't clear to me if the change being breaking was intentional so I thought this report might be warranted.

## Reproduction steps

After evaluating the snippet below, open the menu with `M-x test-prefix` and invoke the one suffix, with the following results:

On parent commit 7e50a8fa8ee71f9ada1e9065ba7b1a079c9f3ba8, the message prints:

> SCOPE: A scope value

On commit 4de5812992ef93fcd80ef1d12a6e1db7f7cd315d, the message prints:

> SCOPE: nil

```emacs-lisp
(transient-define-prefix test-prefix ()
  ["Test commands"
   ("s" "Test scope" test-function)]
  (interactive)
  (transient-setup
   'test-prefix nil nil
   :scope "A scope value"))

(transient-define-suffix test-function ()
  (interactive)
  (message "SCOPE: %s" (transient-scope)))
```

## Additional info

Bug report from my project: <https://github.com/aurtzy/disproject/issues/2>

**Comment by tarsius** [comment]
Yes, the previous fix wasn't complete.

You probably should call this function with an argument regardless. Consider what would happen if a user added one of your suffix commands to some random other prefix menu, which happens to also have a scope. Maybe that could not possibly work in your case, or maybe it would, provided you called this function with the appropriate command.

**Comment by tarsius** [comment]
I'm gonna tweak this some more later today.
