### ISSUE TITLE
Vertico candidates don't expand with `nil` `transient-hide-during-minibuffer-read` 

### ISSUE THREAD

**Issue by josephmturner** [magit/transient#330]
Adapted from https://github.com/minad/vertico/issues/532#issuecomment-2489870371  . Tested on Emacs 29.4 in a clean `--init-directory`:

``` elisp
(require 'vertico)
;; Don't use the built-in version.
;; (require 'transient)
(vertico-mode +1)
;; Checked out at `fixed` branch.
(load "/home/joseph/.local/src/transient.el/lisp/transient.el")

(transient-define-suffix transient-test-read-minibuffer ()
  :transient t
  (interactive)
  (completing-read "Prompt: " '(a b c d)))

(transient-define-prefix foo ()
  "Test"
  ;; :refresh-suffixes t
  ["Hyperdrive peer graph"
   ("r" "Read" transient-test-read-minibuffer)
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")
   (:info "take up vertical space")]
  (interactive)
  (transient-setup 'foo))
```

With `transient-hide-during-minibuffer-read` set to `nil`, I press `r`, then select any candidate. Then I press `r` again, and this time vertico does not expand and I do not see any candidates (like in the original bug report for https://github.com/minad/vertico/issues/532 ).

**Comment by tarsius** [comment]
I should mention it here too; try the `minisize` branch.

**Comment by josephmturner** [comment]
> I should mention it here too; try the `minisize` branch.

I tested these options for `transient-show-during-minibuffer-read` with the above test:

- `nil`: works as expected, the menu disappears while completing
- `t`: does a reasonable thing, but doesn't quite match the docs (which says `"When t, keep showing the menu, but allow for the menu window to be resized."`): the window does not resize, and the completion candidates appear to be overlaid on top of the menu.
- `fixed`: does not work as expected: completion candidates do not appear.
- `20`: does not work as expected (docs say the menu should be hidden if there are less than 20 lines available): behaves like `t`
- `-20`: does not work as expected (docs say the menu should be resized if less than 20 lines): behaves like `nil`.

I also tested with fewer (3) `:info` lines, and all values of `transient-show-during-minibuffer-read` keep the menu open except `nil`, which is expected.

**Comment by josephmturner** [comment]
At some, we might consider adding a `:show-during-minibuffer-read` slot to `transient-prefix`.  For now, my feeling is that we should wait until the design is stable.

**Comment by tarsius** [comment]
> does not work as expected

(As far as I can tell based on my own tests and your report,) it does work as expected, but apparently the documentation needs to be much more explicit.

**Comment by josephmturner** [comment]
> * `fixed`: completion candidates do not appear.

Is this expected?

**Comment by tarsius** [comment]
> > * `fixed`: completion candidates do not appear.
> 
> Is this expected?

It is expected that, depending on other settings, it may be impossible to display completion candidates when the size of the menu is fixed. Always fixing the size is the theoretically ideal behavior, and the whole reason I've added alternatives is that in practice it may not work -- if this always succeeded, all the alternatives wouldn't be needed.

**Comment by josephmturner** [comment]
Just tested again with your latest force-push to `minisize` branch (b72d2b4), and with `fixed`, completion candidates still do not appear.  Is that expected?

I think this change to the docstring makes it consistent with the behavior: https://github.com/josephmturner/transient/commit/7e689a7a5e6b2960ce2c15ba1baf3b84c993a3e4

**Comment by josephmturner** [comment]
> > > * `fixed`: completion candidates do not appear.
> > 
> > 
> > Is this expected?
> 
> It is expected that, depending on other settings, it may be impossible to display completion candidates when the size of the menu is fixed. Always fixing the size is the theoretically ideal behavior, and the whole reason I've added alternatives is that in practice it may not work -- if this always succeeded, all the alternatives wouldn't be needed.

Got it!  Okay, that sounds good to me.  I wrote my previous message before I saw yours.

I think my suggestion to change the docstring is still relevant though.

**Comment by tarsius** [comment]
> > > > * `fixed`: completion candidates do not appear.
> > > 
> > > 
> > > Is this expected?
> > 
> > 
> > It is expected that, depending on other settings, it may be impossible to display completion candidates when the size of the menu is fixed. Always fixing the size is the theoretically ideal behavior, and the whole reason I've added alternatives is that in practice it may not work -- if this always succeeded, all the alternatives wouldn't be needed.
> 
> Got it! Okay, that sounds good to me.

Uhm actually, I was already trying to make `fixup` fall back to the `t` behavior iff the menu window uses the full height of the frame. Now it works.
