### ISSUE TITLE
Transient window doesn't come back  if display-action is set wrong

### ISSUE THREAD

**Issue by Thaodan** [magit/transient#338]
# Description
I noticed since the recent update the transient window disappears when
selecting a infix which asks for input. 

After this change the window which would reappear after the input has been given but could not come back if `transient-display-action`
is set wrong (I don't know what exactly causes this).
This results in the transient window to not appear again and in `Error while exiting transient: (error "Attempt to delete minibuffer or sole ordinary window")` 
if `pop-up-frames` is enabled.

With the transient currently shipped in Emacs 31.0.50, transient version 0.7.2.2 this problem doesn't happen I assume 
as the window which transient uses now disappears.

I don't know exactly what's the best title for this issue, please feel free to rename the bug.

# Steps to reproduce
1.1 Emacs -Q (append all the load-paths your packages here).
   E.g. in my case:
   ```sh
   emacs -Q --init-directory=$PWD/tmp \
         -L ~/.local/etc/emacs/lib/transient/lisp \
         -L ~/.local/etc/emacs/lib/magit/lisp \
         -L ~/.local/etc/emacs/lib/dash \
         -L ~/.local/etc/emacs/lib/compat \
         -L ~/.local/etc/emacs/lib/with-editor/lisp
   ```

1.2. Set transient-display-buffer-action.
```emacs-lisp
(setq transient-display-buffer-action '(display-buffer-below-selected))
```
1.3. Press M-x `magit-status` RET.
1.4. Press l -G <word> RET
1.5. Result below, transient window doesn't reappears

2.1 `(setq pop-up-frames t)`
2.2 Repeat step step 1.3-1.4.

# Backtrace

Backtrace of issue 2:

```
Debugger entered--Lisp error: (error "Attempt to delete minibuffer or sole ordinary window")
  transient--exit-and-debug(error (error "Attempt to delete minibuffer or sole ordinary window"))
  error("Attempt to delete minibuffer or sole ordinary window")
  delete-window(#<window 15 on magit: emacs>)
  transient--delete-window()
  transient--pre-exit()
  transient--pre-command()
```

# Version information
- Magit version: v4.1.3-6-g92eb641f
- Bad Transient version: 0.7.9 00fabc76eb3dc75f742d8d2720c44e25e5772e8f
- Good Transient version: 0.7.2.2 
- Emacs version: GNU Emacs 31.0.50 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2)

**Comment by tarsius** [comment]
Variant 1:

Try this instead:

```elisp
(setq transient-display-buffer-action
      '(display-buffer-below-selected
        (dedicated . t)
        (inhibit-same-window . t)))
```

The default uses these action alist entries because they prevent issues. If you run into issues after dropping them, try whether bringing these entries back makes the issues go away.

I got different behavior from what you described, and am guessing the exact behavior depends on frame proportions. Restoring to the above configuration, fixed things for me.

Variant 2:

Do you *want* the transient window to appear in a new frame, or is (setq pop-up-frames t)` just for other things?

I'll have to investigate some more how to prevent issues when using this configuration (adding `(inhibit-switch-frame .t)` didn't do the trick).

Meanwhile, you can probably go back to the old behavior using `(setq transient-show-during-minibuffer-read t)`.

**Comment by tarsius** [comment]
> Bad Transient version: 0.7.9

Also first update to the newest release, 0.8.1.

**Comment by Thaodan** [comment]
Jonas Bernoulli ***@***.***> writes:

> Variant 1:
>
> Try this instead:
>
> ```elisp
> (setq transient-display-buffer-action
>       '(display-buffer-below-selected
>         (dedicated . t)
>         (inhibit-same-window . t)))
> ```

Yeah with the default setting or this one the issue did not came up.


> The default uses these action alist entries because they prevent
> issues. If you run into issues after dropping them, try whether
> bringing these entries back makes the issues go away.
>
> I got different behavior from what you described, and am guessing the
> exact behavior depends on frame proportions. Restoring to the above
> configuration, fixed things for me.

Different behavior i.e. did the window before you seleted the infix form also
disappear when you selected the infix or did it stay?

> Variant 2:
>
> Do you *want* the transient window to appear in a new frame, or is
> (setq pop-up-frames t)` just for other things?

Just for other things as transient windows usually belong to window
below.


> I'll have to investigate some more how to prevent issues when using this configuration (adding `(inhibit-switch-frame .t)` didn't do the trick).

Is it maybe the window dedicated flag?

> Meanwhile, you can probably go back to the old behavior using `(setq transient-show-during-minibuffer-read t)`.

What was the reason for the change? Thanks for pointing it out.

**Comment by Thaodan** [comment]
> > Bad Transient version: 0.7.9
> 
> Also first update to the newest release, 0.8.1.

I update now, will see how it goes. The last git commit I had in my submodule was d64b73efbc0615eaa58f15f8a0438a2c010f5682.

**Comment by tarsius** [comment]
I edited my response above two minutes after posting it. Look at it using the web interface. It now contains the configuration you should use.

**Comment by Thaodan** [comment]
I saw that but said that the default also worked for me. Anyway thanks.

**Comment by Thaodan** [comment]
Thanks
