### ISSUE TITLE
Conflict between Magit transient commands and some display-buffer settings

### ISSUE THREAD

**Issue by prosoitos** [magit/transient#34]
Thank you for Magit!!!

I used it for several years without any problem. I have not used it for the past 3 months and cannot get it to work anymore. I suspect the problem is the change from magit-popup to transient commands and it may have to do with the fact that I use EXWM.

---

**My problem:** when I try to commit (pressing `c`), what used to be a popup window now is a window without command line. Pressing `c` again gets me to the magit commit message buffer as it should, but with the error message:

```elisp
Error in pre-command-hook (transient--pre-command): (error "Attempt to delete minibuffer or sole ordinary window")
```
In the magit commit message buffer, some letters work fine, but others (for instance `e`) call functions instead of typing text.

From there on, everything is total havoc which is why I am not providing a debug log or other information: cancelling the commit and killing all the magit buffers does not restore things and keys don't work or do unexpected actions in any Emacs buffer, making it really hard to collect information about what has gone wrong. Everything in Emacs at that point is pretty much dysfunctional and the only way out I have found is to restart Emacs.

I use EXWM and I wonder whether there could be something going on there (some window issue during the transient mode which breaks the normal functioning of Magit).

I would appreciate any help or advice on this. Providing more information might be difficult as I explained, but I will try to answer questions as best I can.

Thank you!!!

---

**System info:**

Magit: magit-20190325.1516 (latest from Melpa)
Magit-popup: magit-popup-20190223.2234 (latest from Melpa)
All dependencies: latest from Melpa
Emacs: 26.1-3
OS: 5.0.4-arch1-1-ARCH

**Comment by ultrachrisp** [comment]
I had similar issues after the magit update, but after reading @akheron & @cjk, disabling 'popwin' on my ~display-buffer~, magit started working as expected again. Thanks for the solution!

**Comment by prosoitos** [comment]
*(Apologies for my very late reply)*

> Does this only happen for the committing transient/popup or for others too?

I haven't tried doing anything else with Magit, so I don't know. Things are so hard to manage when this happens and since a full reboot is needed to get out of the issue, I haven't played with Magit. I would guess that this would happen in any transient/popup, but that is only a guess. If you would like me to test something in particular however, let me know and I will do so.

I read @akheron and @cjk's comments, but I don't think that it is a display buffer setting that is messing up Magit for me. The only such settings I have are:

```elisp
(setq display-buffer-alist (quote (("magit-diff.*\\|\\*R\\|\\*helm.*\\*"
      (display-buffer-reuse-window display-buffer-pop-up-window)))))

(setq display-buffer-base-action (quote (display-buffer-same-window)))
```
Removing them did not fix the issue.

I do not have any popwin settings for Magit.

I managed to get a little more info in case it helps (some keybindings don't work at all anymore after the issue starts, but others still do).

As previously mentioned, here is the error message that gets displayed in the minibuffer when I press the first `c` to commit:
```elisp
Error in pre-command-hook (transient--pre-command): (error "Attempt to delete minibuffer or sole ordinary window")
```
and these are the magit messages:

```elisp
  1 git … commit --
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Canceled by user
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.

128 .git/ git … commit --amend --no-edit --
fatal: this operation must be run in a work tree
```

So it seems that maybe there is something up with emacsclient?

Whatever the cause of the problem, it seems that I remain in transient mode so that many key bindings trigger actions instead of typing. And the only way to get out of this transient mode that I have found is a full reboot.

**Comment by prosoitos** [comment]
Ah! Removing `(setq display-buffer-function 'popwin:display-buffer)` actually solved my issue, even though I had no popwin settings at all for Magit...

**Comment by tarsius** [comment]
> Ah! Removing `(setq display-buffer-function 'popwin:display-buffer)` actually does solve my issue, even though I have no popwin settings at all for Magit...

Well it seems that `popwin` is taken by surprise by what `transient` is doing and does something that it shouldn't be doing in response. It also isn't maintained anymore, so this might never be addressed.

**Comment by prosoitos** [comment]
Oh, so I guess there is nothing you can do on the Magit side, right? Mmmm... Bummer... :slightly_frowning_face:

**Comment by prosoitos** [comment]
There are a few windows behaviour I could set with popwin and that I am not able to reproduce with `display-buffer-alist`. But I can confirm that setting the ones I can do not affect Magit. So it is indeed something that popwin does. And the `display-buffer-alist` does otherwise not seem to conflict with Magit. I guess I will have to accept to have a few windows behave differently than I wish.

Thanks again.
