### ISSUE TITLE
Modifying layout based on group

### ISSUE THREAD

**Issue by dajva** [magit/transient#36]
Thanks for this package.
I am implementing a transient frontend for my package [rg.el]( https://github.com/dajva/rg.el) and have the following scenario.

I want to define a transient for the package supported commands but would also like to support adding custom commands to the transient from a macro that defines these custom commands.

The problem I have is that all the `transient-insert-suffix` like commands needs a location in form of another suffix. That works fine if you know the layout (i.e. doing manual customizations in emacs init file) but makes it hard for my scenario where I essentially just want to append or prepend a suffix to a group without caring about the suffixes already there. The solutions I have come up with are either complex and sensitive to breakage, depending on `transient` internals or add unwanted complexity to the API:s I want to expose.

Is this possible to achive in some way with the current API:s that I have missed?

If not, would you consider adding/accepting prs for such API:s? I can also see that adding new groups could be a useful feature, if you for instance want to keep your own modifications to a transient separately under a "Custom" sub section.

**Comment by tarsius** [comment]
> just want to append or prepend a suffix to a group without caring about the suffixes already there
> I can also see that adding new groups could be a useful feature,

I plan to implement those features eventually, but don't know when I will get to it. Feel free to take a stab at it yourself.

**Comment by dajva** [comment]
Thanks a lot. I'll try this out.
