### ISSUE TITLE
Access "parent" transient arguments

### ISSUE THREAD

**Issue by Silex** [magit/transient#48]
Hello,

I have transients like this:

``` elisp
(define-transient-command docker-compose-up ()
  "Popup for \"docker-compose up\"."
  :man-page "docker-compose up"
  ["Arguments"
   ("-b" "Build" "--build")
   ("-t" "Timeout" "--timeout " read-string)]
  ["Actions"
   ("U" "Up" docker-compose--one)
   ("A" "All services" docker-compose--all)])

(define-transient-command docker-compose ()
  "Popup for docker-compose."
  :man-page "docker-compose"
  ["Arguments"
   ("-a" "No ANSI" "--no-ansi")
   ("-h" "Host" "--host " read-string)
   ("-p" "Project name" "--project-name " read-string)
   ("-v" "Verbose" "--verbose")]
  ["Docker-compose"
   ("U" "Up"         docker-compose-up)
   ("W" "Down"       docker-compose-down)])
```

Basically, one transient can be configured with some arguments, then it calls another transient which does something.

In the second transient, how do I access the first transient arguments? I thought `(transient-args 'docker-compose)` would work but it always return nil (I can only access the second transient arguments).

Does that mean I have to write some `docker-compose-save-arguments-then-call-docker-compose-up` function or is there another way? If yes I'll just generate those using metaprogramming, but I thought I'd ask before complicating things :-)

Also, I can't define suffix as inline-lambdas correct? (it has to be a symbol of a function to call)

**Comment by tarsius** [comment]
> In the second transient, how do I access the first transient arguments? I thought `(transient-args 'docker-compose)` would work but it always return nil (I can only access the second transient arguments).

`transient-args` returns the arguments of the "current" transient. Passing a `transient` as the argument means "provided the current transient is X, else return nil". So yes, you have to somehow remember the "outer" arguments and pass them along.

> Also, I can't define suffix as inline-lambdas correct? (it has to be a symbol of a function to call)

I don't remember of the top of my head. Just try if it works.

**Comment by Silex** [comment]
> > In the second transient, how do I access the first transient arguments? I thought `(transient-args 'docker-compose)` would work but it always return nil (I can only access the second transient arguments).
> 
> `transient-args` returns the arguments of the "current" transient. Passing a `transient` as the argument means "provided the current transient is X, else return nil". So yes, you have to somehow remember the "outer" arguments and pass them along.

Alright, thanks.

> > Also, I can't define suffix as inline-lambdas correct? (it has to be a symbol of a function to call)
> 
> I don't remember of the top of my head. Just try if it works.

Oh, yeah I tried and it doesn't work, sorry I forgot to mention it. This limitation actually forces me to write cleaner code so don't bother "fixing" it :-)
