### ISSUE TITLE
Cannot `transient-append-suffix` on empty section

### ISSUE THREAD

**Issue by Silex** [magit/transient#49]
Hello,

I cannot call `transient-append-suffix` on an empty section. Using `(transient-append-suffix 'docker-compose '(1 -1) suffix)))` only works if the section already contains a suffix.

Here is my current workaround (adding a dummy one then removing it):

``` elisp
(define-transient-command docker-compose ()
  "Popup for docker-compose."
  :man-page "docker-compose"
  :value docker-compose-arguments
  ["Arguments"
   ("-a" "No ANSI" "--no-ansi")
   ("-c" "Compatibility" "--compatibility")
   ("-d" "Project directory" "--project-directory " docker-compose-read-directory)
   ("-f" "Compose file" "--file " docker-compose-read-compose-file)
   ("-h" "Host" "--host " read-string)
   ("-l" "Log level" "--log-level " docker-compose-read-log-level)
   ("-p" "Project name" "--project-name " read-string)
   ("-v" "Verbose" "--verbose")]
  ["Docker-compose"
   ("X" "DELME" "-x")])

(let ((params '(("B" "Build"      docker-compose-build)
                ("C" "Create"     docker-compose-create)
                ("D" "Remove"     docker-compose-rm)
                ("E" "Exec"       docker-compose-exec)
                ("F" "Pull"       docker-compose-pull)
                ("L" "Logs"       docker-compose-logs)
                ("O" "Stop"       docker-compose-stop)
                ("P" "Push"       docker-compose-push)
                ("R" "Run"        docker-compose-run)
                ("S" "Start"      docker-compose-start)
                ("T" "Restart"    docker-compose-restart)
                ("U" "Up"         docker-compose-up)
                ("V" "Config"     docker-compose-config)
                ("W" "Down"       docker-compose-down))))
  (--each params
    (let* ((method (-last-item it))
           (name (intern (format "%s-save" method)))
           (suffix (-replace-last method name it)))
      (defalias name
        (lambda ()
          (interactive)
          (setq docker-compose-arguments (transient-args 'docker-compose))
          (funcall method)))
      (transient-append-suffix 'docker-compose '(1 -1) suffix)))
  (transient-remove-suffix 'docker-compose '(1 0)))
```

For now that works but I guess there should be a better way.

Adding the whole section using `(1)` as LOC could work but I'd require me to use `-each` to generate the saver methods then use `-map` to produce the suffixes (instead of doing it in one go like above).

**EDIT**: discovered I can simply call `(transient-set)` instead of saving the current popup value to a variable, then later get the value with... hum... why isn't there something like `(transient-get-value 'docker-compose)`

**EDIT2**: okay, I guess I need to extract the first one from `transient-history`

**Comment by Silex** [comment]
Just to be clear, here's what does not work:

``` ruby
(define-transient-command docker-compose ()
  "Popup for docker-compose."
  :man-page "docker-compose"
  ["Arguments"
   ("-a" "No ANSI" "--no-ansi")
   ("-v" "Verbose" "--verbose")]
  ["Docker-compose"])

(transient-append-suffix 'docker-compose '(1 -1) '("W" "Down"       docker-compose-down))
```

**Comment by Silex** [comment]
Finally did it another way, so I'll close this as it's not a blocker. Feel free to reopen if you want to enhance the documentation about it.

**Comment by meedstrom** [comment]
How did you do it @Silex?

**Comment by meedstrom** [comment]
Ah, I found a trick.  Add a placeholder that's always disabled.  Then the coordinates `(0 0)` points to it and you can append stuff after it.

```
(transient-define-prefix org-node-series-dispatch ()
  ["Series"
   ("|" "Invisible" "Placeholder" :if ignore)])
```

**Comment by Silex** [comment]
To be honest I don't remember. Maybe grep the history of docker.el to find out.

**Comment by tarsius** [comment]
You shouldn't begin with an empty section and then add add suffixes "from the outside". Instead specify a function for the `:setup-children` slot of the group. There's an example in https://magit.vc/manual/transient/Group-Specifications.html. Other examples can be found in https://github.com/tarsius/notmuch-transient.

**Comment by meedstrom** [comment]
Ah, thanks for the tip.
