### ISSUE TITLE
Completely stuck, Emacs stops accepting *all* input and says "Unbound suffix"

### ISSUE THREAD

**Issue by skangas** [magit/transient#50]
I ran into a pretty nasty bug in transient-mode.  I'm just getting "Unbound suffix: '<f10>' (Use 'C-g' to abort, '?' for help)" no matter what I tried.

Not sure exactly what happened or how to reproduce it, but the symptom is that *all* keybindings were disabled.  I believe I tried bringing up magit-dispatch and then pressed C-g or C-[ at an extremely inopportune time because something was temporarily lagging.  (I'm investigating slowdowns in my configuration due to some unknown package which motivates this behaviour.)

Here are some things I tried: Clicking the mouse, right clicking, mouse wheel, dragging mouse, all that in other windows, pressing C-g, q, ?, and literally any other keybinding I could dream up, clicking the mode line and that didn't work either (<mode-line> <mouse-3> is unbound).  tool-bar-mode and menu-bar-mode are disabled so I can't try that.

I'll see if I can attach GDB to the process and get a Lisp level backtrace for you tomorrow.  Emacs is still running, so if you have anything you want me to try, post quick and I might be able to do it before I have to kill this Emacs process.

Anyways, it would be good if there was a fire escape for situations like this. Two suggestions:
1. Transient mode should just go away and reset itself after X seconds of inactivity (by default high, say 120 seconds or something)?
2. C-g and/or q should always work.  Maybe they should and something just broke, but here we are.

This is on version 0.1.0 from melpa-stable, not sure if this would be fixed by just upgrading.  If so, please release a new version of the package. (BTW, it would be good with a new release of magit too soon, for us poor schmucks using melpa-stable.)

PS. Thanks for all your good work on Magit. It's one of the killer apps of Emacs.

**Comment by skangas** [comment]
I had difficulties attaching gdb to emacs due to some gdb bug.  So I unfortunately can't provide a backtrace, sorry.

Thinking about it a bit more, there seems to simply be an `unwind-protect' missing somewhere.

**Comment by tarsius** [comment]
> Thinking about it a bit more, there seems to simply be an `unwind-protect' missing somewhere.

Yes probably. And if memory serves right I added one or two of those since the last release.

> So I unfortunately can't provide a backtrace, sorry.

As far as Emacs is concerned everything is working to specification. There won't be a backtrace. Transient put Emacs in an inconsistent state and there is no way back. Except if there is a second frame. I believe selecting another frame with the mouse should get you out of the lock.

> please release a new version of the package. 

Like for Magit, the plan to create a release in August. In this case very early August, maybe even a few days earlier.

**Comment by skangas** [comment]
> > Thinking about it a bit more, there seems to simply be an `unwind-protect' missing somewhere.
> 
> Yes probably. And if memory serves right I added one or two of those since the last release.

Perhaps this can be closed then.

I'll report back if I encounter this again and have anything useful to add.

Thanks,
Stefan Kangas

**Comment by tarsius** [comment]
Yeah, it might be fixed already and if not, then I would need exact steps to reproduce.
