### ISSUE TITLE
Argument defaults ?

### ISSUE THREAD

**Issue by olymk2** [magit/transient#52]
I have not found a way to set a default value for a parameter, for example say i have --num parameter when the transient opens for the first time I would like to give it that value of 10 but still allow the user to override it and have a different value in the future.

For me I want to have a default and allow it to be overridden from dir local so when opening a project on a new machine the dialog will have required param pre filled.

I have asked in a few places and I don't seem to be the only one who would like this feature.

https://www.reddit.com/r/emacs/comments/ciyqib/how_to_set_transient_infix_params_default_values/

And in the comments of this gist.
https://gist.github.com/abrochard/dd610fc4673593b7cbce7a0176d897de

Is there an existing way to do this and if not could it be added or is this considered outside of the scope of transient ?

**Comment by tarsius** [comment]
Pass e.g `:value ("--foo" "--bar=val")` to `define-transient-command`.

That's indeed not documented and yesterday I started working on https://magit.vc/manual/transient/Prefix-Slots.html were it should be documented. I'll probably also have it in a few other places.

**Comment by tarsius** [comment]
Also the more detailed commend at https://www.reddit.com/r/emacs/comments/ciyqib/how_to_set_transient_infix_params_default_values.

I'll try to finish the documentation about this soon.

**Comment by olymk2** [comment]
awesome thanks for explaining that I will give it a try :)

**Comment by dalanicolai** [comment]
For people looking for it, another simple example has been posted [here](https://emacs.stackexchange.com/a/66462/26163). It shows how to implement the extra step that is mentioned in the reddit article, but without an example.
