### ISSUE TITLE
Ability for user to save settings

### ISSUE THREAD

**Issue by kquick** [magit/transient#54]
In the older magit-popup mode, the user's settings (e.g. =S gpg key signing) could be saved and automatically applied to all future uses of the popup via the `C-c C-c` operation.

I have not been able to discover a way to do this in the new `transient`-based implementation.  I would be happy to contribute a documentation pull request someone could indicate whether this is supported in transient, and if so, how.

**Comment by kyleam** [comment]
Have a look at https://magit.vc/manual/transient/Saving-Values.html#Saving-Values

**Comment by kquick** [comment]
Thanks, @kyleam , this is exactly what I was looking for, *and* documented no-less.  Somehow I didn't manage to find this previously.  Maybe this issue will help lead folks to this in the future.  I'm going to do a little looking around to see if there are other places this could be referenced (e.g. the magit `commit` page) before I close this; suggestions are welcome.

**Comment by kquick** [comment]
Please feel free to assign this to me (I don't have that privilege).

**Comment by tarsius** [comment]
> (e.g. the magit `commit` page)

The commit popup is only one of many of Magit's transient popups. If we added a link to the committing documentation, then it would only be logical to add the same link to the documentation about each one of these transients. I don't want to do that.

**Comment by kquick** [comment]
Fair enough.  Maybe a FAQ entry on changes from magit-popup to transient that could collect some hints like this for people making that transition?

**Comment by tarsius** [comment]
Adding something to https://github.com/magit/magit/wiki/FAQ might help a handful of users. Feel free to add something there. I doubt it's gonna make much of a difference (did you check that before opening this issue), but who knows?

**Comment by kquick** [comment]
I was not even aware of that link.  I *did* check this FAQ and didn't find anything: https://magit.vc/manual/magit/FAQ.html#FAQ
