### ISSUE TITLE
Request: Defer package loading when calling transient

### ISSUE THREAD

**Issue by jojojames** [magit/transient#61]
Hi!

I have a big transient I use that contains commands to various packages. When I start the transient for the first time, it seemingly runs?/requires? the packages the command is autoloaded in. For example,

```
(define-transient-command matcha-me-space ()
  "Space"
  [["Find"
    ("n" "Sidebar" dired-sidebar-toggle-sidebar)]]
  (interactive)
  (let ((transient-show-popup -.2))
    (transient-setup 'matcha-me-space)))
```

Loads/requires dired-sidebar which also loads its requires and so on causing a heavy initial delay when running the transient.

Thanks for reading!

**Comment by tarsius** [comment]
This happens in `transient--init-suffix`, which is called by `transient-setup` which is used to "Setup the transient specified by NAME. ...". The reason that the autoloaded library has to be loaded is the suffix command may have been defined with `define-transient-suffix`. In that case an object with additional settings is associated with the command and if that is so, then we need to use that during transient setup.
