### ISSUE TITLE
multi-value doesn't function

### ISSUE THREAD

**Issue by jdtsmith** [magit/transient#65]
A multi-choice option can be made as follows:

```elisp
(defconst ads-pub-choices '("ApJ" "AJ" "MNRAS"))
(define-infix-argument ads-publications ()
  :key "p"
  :class transient-option
  :description "Publications"
  :argument "pub="
  :multi-value t
  :reader nil
  :choices ads-pub-choices)
```

There are two issues:

1. You must specify `:reader nil` or `read-string` is incorrectly used as the reader, even when `:multi-value` is set.  The reader should default to `completing-read-multiple` with `:multi-value`.
2. The value returned by `completing-read-multiple` is a list of strings. This causes an error, as transient doesn't collapse this string.  Not clear what separator should be used, but probably ",".

**Comment by tarsius** [comment]
1. I don't think that's correct.

2. I have taught `transient-format-value` about `transient-option`s with multiple values. This wasn't handled properly because I never used multiple values with `transient-option`, only with the `magit--git-variable:choices` class, which implements its own `transient-format-value`.

**Comment by jdtsmith** [comment]
Thanks.  On 1., sorry I meant to refer to an "in-inline" multi-value infix, ala

```elisp
("x" "X-Ray" "xray=" :reader nil :multi-value t :choices '("X1" "X2" "X3"))
```

  `transient--parse-suffix` doesn't know anything about `:multi-value`, so without `:reader nil`, it falls to:

```lisp
(t
                  (setq class 'transient-option)
                  (setq args (plist-put args :reader 'read-string)
```

A related issue is that `:choices` isn't correctly parsed by the parsing macro (and could maybe take a symbol to be evaluated too).

Thanks again.
