### ISSUE TITLE
Support proportional variable-width fonts

### ISSUE THREAD

**Issue by MicahElliott** [magit/transient#67]
Magit generally looks great with a mix of proportional and monospace fonts, with a proportional as Emacs' _default_ font.  But...

I'm not finding any customize-able _faces_ in magit or transient that apply to the transient popups.  Since the layout is tabular, proportional fonts are going to be misaligned.  If there were a hook for transient (which I'm not aware of), an approach like [this](https://emacs.stackexchange.com/a/3044/11025) would work.

<img width="298" alt="Screen Shot 2019-12-05 at 4 10 49 PM" src="https://user-images.githubusercontent.com/159047/70284910-9b77f380-177a-11ea-86bb-0e39522a1ebf.png">

I've seen proportional fonts look OK with other tabular views when columns are done with tabs.  So the fix for this is to either put the cols into tabs, or support using a face specifically for this transient.

**Comment by tarsius** [comment]
Duplicate of #25.
Checkout the new `transient-force-fixed-pitch` option.
