### ISSUE TITLE
magit-am transient-values are not restored correctly

### ISSUE THREAD

**Issue by duianto** [magit/transient#68]
#### Description :octocat:
The Apply patches `w` (`magit-am`) transient arguments that have been saved with 
`C-x C-s`, don't seem to be restored correctly.

`--3way` is the only active argument after restarting Emacs.
Even if `--3way` was disabled, it still gets restored.

It might be limited to the `magit-am` arguments, because for example the
Show Refs `y` (`magit-refs`) transient arguments are restored correctly.

#### Reproduction guide :beetle:
- From a `magit-status` buffer visiting a repository.
- Press: `w`
The `--3way` argument is enabled by default.
- Disable it by pressing: `-3`
- Press `-b` to add `--keep-non-patch`.
- Save the settings: `C-x C-s`
- Close the transient popup `C-g`

- Press: `y` to open the `magit-refs` buffer.
- Press: `y` to show the `magit-refs` arguments and actions.
- Press: `-m` to add `--merged` (Merged to HEAD)
- Save: `C-x C-s`
- Close the transient popup `C-g`
The transient values seem to be stored correctly: `C-h v transient-values RET`
>transient-values is a variable defined in ‘transient.el’.
Its value is
((magit-am "--keep-non-patch")
 (magit-show-refs "--merged"))
- Close Emacs `C-x C-c`
- Start Emacs
- Open the `magit-status` buffer with the same repository.
- Open the Apply patches transient `w`

*Observed behaviour:* :eyes: :broken_heart:
The `-3` (`--3way`) argument is unexpectedly the only enabled argument.
Close the apply patches transient popup `C-g`.

Open the show refs transient popup: `yy`
It shows the previously save argument as expected: `-m` (`--merged`).

The `C-h v transient-values` remain unchanged:
>transient-values is a variable defined in ‘transient.el’.
Its value is
((magit-am "--keep-non-patch")
 (magit-show-refs "--merged"))

*Expected behaviour:* :heart: :smile:
The `w` (`magit-am`) transient popup should restore the last saved settings, like the `yy` (`magit-refs`) transient popup does.

#### Notes :notebook:
I also noticed that when all arguments are disabled. Then the magit commands remain in the `transient-values` variable.
>transient-values is a variable defined in ‘transient.el’.
Its value is ((magit-am) (magit-show-refs))

Maybe they should be cleared when they don't have any arguments.

#### System Info :computer:
Transient 0.1.0 (transient-20200102.2204)
Magit 20200102.2204, Git 2.24.0.windows.2, Emacs 26.3, windows-nt
Emacs 26.3
Windows 1903

**Comment by tarsius** [comment]
> I also noticed that when all arguments are disabled. Then the magit commands remain in the `transient-values` variable. [...] Maybe they should be cleared when they don't have any arguments.

No. Using no argument instead of the non-nil default arguments can also be a useful setting.

**Comment by tarsius** [comment]
I understand the issue and it shouldn't be too hard to fix, but it might involve a backward incompatible change, so I'll have to think about it a bit.

**Comment by tarsius** [comment]
Thanks for the report. That really needed fixing.

**Comment by tarsius** [comment]
The fix in f0a7a97 gets fixed here, which then gets fixed in 5c0f901. Sight.
