### ISSUE TITLE
:if-non-nil argument is not handled

### ISSUE THREAD

**Issue by conao3** [magit/transient#72]
Hi!
I found the command list can accept `:if` keyword, but `:if-non-nil` keyword is not handled.
```emacs-lisp
(defun transient-dwim-message-a () (interactive) (message "add-a"))
(defun transient-dwim-message-b () (interactive) (message "add-b"))

(define-transient-command transient-a1 ()
  ["Commands"
   ("a" "Add-a" transient-dwim-message-a)
   ("b" "Add-b" transient-dwim-message-b :if (lambda () nil))])

(define-transient-command transient-a2 ()
  ["Commands"
   ("a" "Add-a" transient-dwim-message-a)
   ("b" "Add-b" transient-dwim-message-b :if (lambda () t))])

(define-transient-command transient-b1 ()
  ["Commands"
   ("a" "Add-a" transient-dwim-message-a)
   ("b" "Add-b" transient-dwim-message-b :if-non-nil nil)])

(define-transient-command transient-b2 ()
  ["Commands"
   ("a" "Add-a" transient-dwim-message-a)
   ("b" "Add-b" transient-dwim-message-b :if-non-nil t)])
```
1. `transient-a1` shows `Add-a`
2. `transient-a2` shows `Add-a` and `Add-b`
3. `transient-b1` shows `Add-a` and `Add-b`
4. `transient-b2` shows `Add-a` and `Add-b`

But the result of 3 maybe wrong.

**Comment by tarsius** [comment]
That's an insignificant edge-case. The argument to `:if-non-nil` and `:if-nil` must be a variable. While `t` and `nil` are treated as variables to an extend, their value is always the same -- `t` for `t` and `nil` for `nil`.

Therefore it makes no sense to use `t` and `nil` as arguments to `:if-non-nil` and `:if-nil`, the value would always be the same. Any it therefore also does not matter that the value for `:if-non-nil nil` is always *wrong*.

Try this instead:

```emacs-lisp
(setq my-variable nil)

(define-transient-command transient-b1 ()
  ["Commands"
   ("a" "Add-a" transient-dwim-message-a)
   ("b" "Add-b" transient-dwim-message-b :if-non-nil my-variable)])
```

**Comment by conao3** [comment]
OK, thanks!
