### ISSUE TITLE
Specify no exit transient popup per suffix commands

### ISSUE THREAD

**Issue by conao3** [magit/transient#75]
Hi!
I read https://magit.vc/manual/transient/Comparison-With-Other-Packages.html#Hydra and specify `:transient-suffix     'transient--do-stay` to no exit transient popup.

>Transient supports that too, but for now this feature is not a focus and the interface is a bit more complicated. A very basic example using the current interface:
```emacs-lisp
(define-transient-command outline-navigate ()
  :transient-suffix     'transient--do-stay
  :transient-non-suffix 'transient--do-warn
  [("p" "next visible heading" outline-previous-visible-heading)
   ("n" "next visible heading" outline-next-visible-heading)])
```

Yes, you think this feature is an option, but could I specify no exit transient popup per suffix command?

**Comment by tarsius** [comment]
You can use the `:transient` **suffix** property for that. That can be either a boolean as seen in e.g. `magit-diff-refresh` or explicitly one of the `transient--do-*` pre-commands.

You might also want to look at `transient--make-predicate-map` to see how the predicate is determined.

**Comment by WorldsEndless** [comment]
I'm still trying to master Transient terminology, and I'm trying to import a hydra that uses this very feature. On the per-suffix thing, you mention using the transient suffix property. Where can I find an example of what this looks like?

**Comment by tarsius** [comment]
Something like

```elisp
("p" "next visible heading" outline-previous-visible-heading :transient t)
```

I.e. you take an existing suffix specification and add `:transient VALUE` at the end of it.
