### ISSUE TITLE
Add boilerplate functions such as -init-value or -infix-set for transient-variable

### ISSUE THREAD

**Issue by ThibautVerron** [magit/transient#76]
(I suspect it would help a lot with https://github.com/magit/transient/issues/51 too)

Hi,

While playing around with transient to write a simple dispatcher setting and using some variables (ala org-export), I ran into pretty much the same difficulties as the ones described in the other issue. The kubernetes example is nice but only addresses infixes changing command line switches and options, and the `org-ql` written by Alphapapa helped too.

In the end, I ended up taking code from org-ql-view and magit-transient, replacing the variable classes by my own and everything worked fine.

So I wonder if part of the difference in difficulty between switches and variables is that for switches, there is boilerplate available, while for variables there isn't.

Would it make sense to add to transient an implementation of `transient-infix-set`, `transient-init-value`, `transient-format-description`, `transient-format-value` for the class `transient-variable?

**Comment by tarsius** [comment]
> So I wonder if part of the difference in difficulty between switches and variables is that for switches, there is boilerplate available, while for variables there isn't.

Why don't the libraries qualify that you mention one paragraph up?

> Would it make sense to add to transient an implementation of

Yes and "variable" should probably mean "elisp variable". `transient-variable` should probably remain abstract and a new `transient-elisp-class` should be added.

I'll do this once I also have the time to use that class in a package of my own. I expect that if I just implemented this without also using it in more than one or two examples, then I would end making bad decisions and having to make breaking changes later on.

**Comment by ThibautVerron** [comment]
> Why don't the libraries qualify that you mention one paragraph up?

For pretty much the same reason it's more useful to have transient as a separate library than have the users extract appropriate code from magit.

My point is that with this simple boilerplate, having an infix prompting for a value and setting a variable to that value is just a matter of defining the variable, and that in most cases, the boilerplate doesn't need to do anything package-specific. Just like command line switches and options work out of the box, elisp variables could too.

Defining elisp switches and mutually-exclusive values should be possible too.

For the sake of the anecdote, the difference in usability is such that I was almost considering using switches and parsing the string arguments into elisp variables in the suffix.

> I'll do this once I also have the time to use that class in a package of my own. I expect that if I just implemented this without also using it in more than one or two examples, then I would end making bad decisions and having to make breaking changes later on.

Okay. Maybe @alphapapa and other early users have some valuable input on the matter too.

**Comment by tarsius** [comment]
I've implemented a `transient-lisp-variable` class a while ago. Let me know if it doesn't work as you would have expected. It is marked as experimental and we can still make changes without feeling guilty about it. :grin:

**Comment by alphapapa** [comment]
@ThibautVerron Sorry, I didn't notice your tagging my username.

I'll put the new class on my to-do list for `org-ql` and see if I can use it, but I probably won't work on that for a while.

Thanks.
