### ISSUE TITLE
Transient commands taking over git commit messages

### ISSUE THREAD

**Issue by jcai849** [magit/transient#77]
Keystrokes for git commit messages are being diverted to transient commands instead. Additionally, the transient popups aren't disappearing after quitting or C-g. It was working fine up until I updated yesterday, with no updates performed before then for just under a year.

I have reinstalled magit, along it's transient and git-commit dependencies. 
Compilation yields the following:
```
Compiling file /home/user/.emacs.d/elpa/transient-20200226.1612/transient.el at Wed Mar 25 22:21:10 2020
Entering directory ‘/home/user/.emacs.d/elpa/transient-20200226.1612/’
transient.el:1626:1:Error: Wrong number of arguments: (2 . 3), 4
```
Running on the following system:
> GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-09, modified by Debian

**Comment by tarsius** [comment]
> I have reinstalled magit, along it's transient and git-commit dependencies.

Did you restart Emacs in between uninstalling and reinstalling?

> transient.el:1626:1:Error: Wrong number of arguments: (2 . 3), 4

Did you try getting a backtrace using `M-x toggle-debug-on-error`? (Not sure if that would have an effect here.)

**Comment by npostavs** [comment]
> > transient.el:1626:1:Error: Wrong number of arguments: (2 . 3), 4
> 
> Did you try getting a backtrace using `M-x toggle-debug-on-error`? (Not sure if that would have an effect here.)

Might need to `(setq byte-compile-debug t)` as well.

**Comment by jcai849** [comment]
I have now reinstalled it with a restart between. This time transient and magit appear to not have compiled, but with-editor and git-commit have; I'm not sure what determines that. I don't think that's a problem though.

When I run magit, the transient window pops up as normal if I press h for help, but if I C-g it remains, and if I switch buffers, say to *scratch*, the keystrokes entered in *scratch* get sent to transient as though I were still in the magit buffer. When I do press C-g after h, this shows in the echo area:

> Error in pre-command-hook (transient--pre-command): (wrong-number-of-arguments (2 . 3) 4)

There is no associated backtrace for that with debug-on-error toggled on.

However, *Backtrace* gives me the linked  output if I enter anything in the other buffer as described ([backtrace.txt](https://github.com/magit/transient/files/4383855/backtrace.txt)) . When I wrote the backtrace file out, it was located in the git-commit elpa folder, perhaps it stems from there?

**Comment by tarsius** [comment]
Please help us narrow the issue down by trying to reproduce it without your personal configuration by starting from `emacs -Q ...`. The manual [documents](https://magit.vc/manual/magit/Debugging-Tools.html) the tools that we provide to make that easier.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>
