### ISSUE TITLE
feature request: configurable directory for cache data

### ISSUE THREAD

**Issue by Trevoke** [magit/transient#79]
Right now everything goes into `~/.emacs.d/transient/` - I'd like to be able to choose where that `transient` directory is.

More specifically, what I actually want is to not have to add `~/.emacs.d/transient/` to my `.gitignore` file :)

Thank you for all the hard work. Your contributions to the emacs ecosystem are amazing and appreciated!

**Comment by tarsius** [comment]
You are looking for the variables `transient-{levels,values,history}-file`.

**Comment by Trevoke** [comment]
I am not looking for those variables. I found them. I assumed, because the
code links them underneath a common directory, that there's a desire for
them to move together. if not, they may as well be `transient-history.el`
instead of `transient/history.el`.

Did I misunderstand the intent behind the code?

**Comment by tarsius** [comment]
I suppose some users would want that, but others (including myself) don't and then an additional option for the directory would complicate matters.

**Comment by Trevoke** [comment]
That certainly makes sense. Why does the source code put a directory in
there in the first place? Why not let this choice entirely in the hands of
users, then?

**Comment by tarsius** [comment]
Because it infuriates me when an application uses multiple configuration and/or data files that are located *directly* in `$HOME` (or here `~/.emacs.d`) instead of having the decency to *either* at least use a dedicated directory to put all of its crap into or (and this is better) use the appropriate xdg directories.

There is nothing official like xdg for Emacs, so I am going with the former approach. (However I also maintain the `no-littering` package which does the proper thing. But sadly that isn't official.)

**Comment by iambumblehead** [comment]
current emacs now supports $XDG_CONFIG_HOME and after moving emacs config files to use $XDG_CONFIG_HOME there is an error when closing emacs
```
Error (file-error creating directory ... /home/bumble/.config/emacs/transient) continue: y or no?
```
I tried creating the transient directory, next it tries to open a history.el file. I added the transient/history.el but emacs has some problem opening that.

**Comment by tarsius** [comment]
> current emacs now supports $XDG_CONFIG_HOME and after moving emacs config files to use $XDG_CONFIG_HOME there is an error when closing emacs

I've been using that for months now, without any issues like this.

It sounds like you might have moved the directory while emacs was running. Does go back to working as expected after restarting emacs?

> I tried creating the transient directory, next it tries to open a history.el file.

I am not sure what I am expected to take away from that.

> I added the transient/history.el but emacs has some problem opening that.

How does that problem manifest?

**Comment by iambumblehead** [comment]
I'm sorry for commenting here everything is working now. I used unfamiliar tools to generate locations at XDG_CONFIG_HOME and those locations were problematic for emacs. After reverting those changes by those toos, emacs is working fine again. Thanks for replying to me.
