### ISSUE TITLE
Can't `C-h k`

### ISSUE THREAD

**Issue by DamienCassou** [magit/transient#8]
After a transient popup opens, I would like to press <key>C-h k</key> (or similar) and then a suffix key to find out what command will be executed.

**Comment by dakra** [comment]
Pressing `C-h` or `?` followed by the suffix key shows the help function for the command.

**Comment by tarsius** [comment]
... and pressing `q` in the help buffer brings you back to the transient.

**Comment by DamienCassou** [comment]
Thank you and sorry for the noise.
