### ISSUE TITLE
Option to disable suffix and infix commands instead of hiding them

### ISSUE THREAD

**Issue by zhaojiangbin** [magit/transient#80]
This is a feature request.

For suffix and infix commands that their predicates (`:if` etc.) are returning `nil`, I think it's better to have them disabled (i.e. grayed out). Hiding these commands hurts discoverability which to me is one of the biggest benefit of transient.

**Comment by tarsius** [comment]
I disagree. I randomly looked at a few such suffixes; in all cases it would not have made any sense to do what you suggest. Please provide examples where this would be an improvement.

**Comment by zhaojiangbin** [comment]
Imagine that there is a transient that has a suffix command calling `eval-region`. This suffix can have a predicate slot such as `:if region-active-p`. While it can be debated whether this  predicate makes sense for this suffix command, I hope it is showing my intent.

Now because the suffix command is hidden by the UI most of time, the transient users might not even know the existence of it. This is what I mean by "hiding these commands hurts discoverability".

If the command is instead disabled (i.e. grayed out) in the UI, it should be immediately obvious to the users about the command.

I should have made clear that I hope I will be able to use both "disable" and "hide" in same transient because they are for different purposes. Ideally a suffix/infix can even have predicates for both "hide" and "disable" at the same time.

I am thinking that in addition to the existing predicate slots that determine to hide or not, a new set of predicate slots can determine to disable or not, such as `:disable-if-not`. Therefore, in the above example, the suffix command can do:

```
("e" "eval region" eval-region
  :if (lambda () (eq major-mode 'elisp-mode))
  :disable-if-not region-active-p)
```

Hope this is convincing to you. :)

**Comment by tarsius** [comment]
You can find a draft in the `inapt` branch. I had to go with that name because "disabled" already means something else. It still needs more testing (please help with that) and documentation.

**Comment by tarsius** [comment]
You can find a draft in the `inapt` branch. I had to go with that name because "disabled" already means something else. It still needs more testing (please help with that) and documentation.

**Comment by zhaojiangbin** [comment]
Awesome. I will give it a try some time later this week.

**Comment by zhaojiangbin** [comment]
I had a quick run of it with my transient. Replaced a few `:if` with `:inapt-if-not`. All work exactly as I expect. I love the warning of the "inapt" function name in the echo message. Thanks for great work!
