### ISSUE TITLE
Transient sometimes gets "stuck"

### ISSUE THREAD

**Issue by zenspider** [magit/transient#86]
I don't have a clean repro on this, but it has caused me to back out of recent magit+fam several times... but I'm trying to bite the bullet so I can keep recent. I _think_ this is transient. Basically, any of the sub-commands off of magit-status use transient, right?

OK. So, here's a basic description:

1. Pull up magit status.
2. Hit 'b' or some other subcommand that has a sub-menu.
3. C-g does _nothing_. Nor can I get a minibuffer (does transient take over the minibuffer??) or see any key sequence I'm halfway into... nothing.
4. The only way I've found to get unstuck is to start to use something from that transient window and then C-g from that (eg  'm' to rename branch and then C-g from that).

Again, it isn't consistent so I don't have a good clean repro. But I'll keep poking to try to get one. Hopefully this description is enough for someone else to be able to chime in.

**Comment by zenspider** [comment]
For the record, I don't have any of the `display-buffer-*` vars set to anything. I do have popwin installed, but I don't seem to have it activated... Still poking.

**Comment by zenspider** [comment]
I still don't know what/how this situation was happening. I tried to delete `~/.emacs.d/transient/history.el` to no avail... but maybe I had on old version previously and it wasn't right? I dunno.

**Comment by tarsius** [comment]
There have been bugs like this before. Closing because this doesn't happen for you anymore and there isn't much to go on anyway. Please reopen if it starts happening again.
