### ISSUE TITLE
How to get transient to respect my frame splits?

### ISSUE THREAD

**Issue by zenspider** [magit/transient#87]
The older magit used magit-popup. I'm biased. I preferred it. I work in a full screen split down the middle and the old magit-popup respected my frame splits. It would pop its subcommand menus into the same window that magit was in. I believe this is how most people expect things like subcommands to work. They should behave as if they are _part of_ magit.

Now? Transient pops up across my **entire frame**. I've rerun with `-q` to verify that it isn't something in my aging emacs setup. I really don't like this and I've reverted package updates several times to avoid it, but I'm trying to get more up-to-date and work through the troubles.

I've poked at the `transient` group in customize and didn't find anything obvious... is there something I can tweak to determine how transient wants to display?

Relatedish, is there some way to display the minibuffer? I don't get messages or see my keystrokes when transient is active and it would at least help with understanding what's going on in #86.

**Comment by kyleam** [comment]
> I've poked at the `transient` group in customize and didn't find anything obvious... is there something I can tweak to determine how transient wants to display?

Try configuring `transient-display-buffer-action`.  I think the `(display-buffer-below-selected)` value that is mentioned in its docstring does what you want.

**Comment by zenspider** [comment]
@kyleam I was just trying to find your emacs.d repo... the site you had it hosted in is no longer and your archived repo here points to that (as do your comments in other issues here)...

**Comment by zenspider** [comment]
Customizing with:
```
'(transient-display-buffer-action (quote (display-buffer-below-selected)))
```
and adding:

```
(transient-bind-q-to-quit)
```

to my magit-mode hook has brought a fair amount of sanity back to my git interactions. 

Closing.

**Comment by kyleam** [comment]
> @kyleam I was just trying to find your emacs.d repo...

Sorry for leaving the archived repo with a dead link.  I've updated it now.
