### ISSUE TITLE
How to read infix-arguments correctly

### ISSUE THREAD

**Issue by karthink** [magit/transient#88]
I'm trying to write a wrapper around `ffmpeg`:

```
(define-infix-argument ffmpeg-dispatch:-i ()
  :description "Source stream"
  :class 'transient-option
  :shortarg "-i"
  :argument "-i"
  :prompt "Input file: "
  :reader 'ffmpeg-read-file-name
  )

(defun ffmpeg-read-file-name (prompt initial-input history)
  (read-file-name prompt nil nil t initial-input))
```

This runs fine but the argument doesn't add a space between `-i` and the chosen file, so I get something like: `-i/home/user/file.mp4` instead of `-i /home/user/file.mp4`.

----
I modeled `ffmpeg-dispatch:-i` after `magit:--`:
```
(define-infix-argument magit:-- ()
  :description "Limit to files"
  :class 'transient-files
  :key "--"
  :argument "--"
  :prompt "Limit to file(s): "
  :reader 'magit-read-files
  :multi-value t)
```

**Comment by tarsius** [comment]
You'll have to define your own class, deriving from `transient-option`, and implement `transient-infix-value`. Looking at the implementation for `transient-option` it should be obvious what has to be changed. Additionally you will likely have to `flatten-list` on the value returned by `transient-args`.

**Comment by karthink** [comment]
Thanks. I should be able to pass the result of `transient-args` directly into a call to `apply`, correct?

For anyone else trying to figure out how to prescribe custom behavior for `define-infix-command` or `define-infix-argument`, here's what I did:

```
(defclass ffmpeg-option (transient-option) ()
  "Class used for command-line argument that can take a value.")

(cl-defmethod transient-infix-value ((obj ffmpeg-option))
  (when-let ((value (oref obj value)))
    (concat (oref obj argument) " " value)))

(cl-defmethod transient-format-value ((obj ffmpeg-option))
    (let ((value (oref obj value)))
      (propertize (concat (oref obj argument) (when value " ") value)
                  'face (if value
                            'transient-value
                          'transient-inactive-value))))
```
Then I set the `:class` in the definition of `ffmpeg-dispatch:-i` above to `ffmpeg-option`.
