### ISSUE TITLE
"..." added to history.el causing error on `kill-emacs`

### ISSUE THREAD

**Issue by RJTK** [magit/transient#90]
I am pretty new to any emacs development so I'm not entirely sure if this is a helpful bug report, but I was unable to exit emacs due to an error `wrong type argument listp \.\.\.` on `C-c C-x`.  I was able to track this down to the function `transient-save-history` and was resulting from `...` being added to the list in the `transient/history.el` file.  The contents of this file were exactly

```
((magit-branch nil)
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat"))
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-log
  ("-n256" "--graph" "--decorate"))
 (magit-pull nil)
 (magit-push nil)
 (magit-remote
  ("-f"))
 (magit-revert
  ("--edit"))
   ...) <------------- Error caused by this
```

My emacs version is `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-05-24`

**Comment by tarsius** [comment]
Are you using a recent `transient` snapshot? I vaguely remember having fixed this issue months ago.

**Comment by RJTK** [comment]
It seems I had a quite old version (2019-02), at least now I know more about keeping packages up to date.  This can probably be closed, thank you for your work on magit.
