### ISSUE TITLE
Add --no-edit to commit transient

### ISSUE THREAD

**Issue by Bridouz** [magit/transient#95]
Hi there,

First I would like to thank you all for bringing magit and transient to emacs. A pleasure to use.

I'm not really knowledged in lisp and do not know how to add new arguments to the commit transient.

I have a git hook which populate the  commit message when `--no-edit` is used. I would like to keep using it alonside magit.

How do you add `--no-edit` to the commit transient.

Sorry to bother and thanks a lot.

If It's possible and I understand the answer I will try to propose a draft on the subject for the wiki.

**Comment by tarsius** [comment]
```elisp
(transient-insert-suffix 'magit-commit "-n"
  '("-N" "Don't edit message" "--no-edit"))
```
