### ISSUE TITLE
Can I disable an argument from a prefix from saving?

### ISSUE THREAD

**Issue by JRigotti** [magit/transient#96]
First and foremost, thanks for such an amazing tool! I would like to report what I understand is an issue.

If I create the following transient:

```lisp
(transient-define-prefix test-file-argument ()
  :value (lambda ()
           (list "-b" (concat "--file=" (buffer-file-name))))
  ["Info"
   ("-f" "File" "--file=")
   ("-b" "Bool" "-b")]
  ["Actions"
   ("v" "Magit version" magit-version)])
```

After I call it with `M-x test-file-argument` the "Bool" argument comes toggled on and the file argument comes correctly with current buffer file name.

However, if I want to change `-b` argument and want to save the value for the next time with `C-x C-s`. Now the default `--file=` value behavior will disappear since its value will fix in the value when the transient was saved.

Is there way that I can disabled the storing of the value of a specific argument?

**Comment by tarsius** [comment]
It might be possible to do that by defining your own prefix class and the `transient-save-value` method. Could be fiddly.

I am on vacation and won't be around to deal with more advanced request such as this.

**Comment by tarsius** [comment]
You can now do this:

```elisp
(transient-define-prefix test-file-argument ()
  ["Info"
   ("-f" "File" "--file="
    :init-value (lambda (obj) (oset obj value buffer-file-name))
    :unsavable t)
   ("-b" "Bool" "-b")]
  ["Actions"
   ("v" "Magit version" magit-version)])
```
