### ISSUE TITLE
Dynamic file path for transient argument

### ISSUE THREAD

**Issue by Nathan-Furnal** [magit/transient#97]
Hi, I'm trying to setup a tool to interact with a CLI. One of the arguments of the CLI is a file path (for a data file) and it can be anything, wherever the user stored said data.

I'm trying to setup an argument where the user can look for the file as if they where using `find-file`, but I can't get it working.

```elisp
(transient-define-argument stan-transient:--input ()
  :description "Input data file"
  :class 'transient-option
  :shortarg "i"
  :prompt "Data file path: "
  :argument "data file=")
```

My understanding is that I should use the `:reader` but I can't get that to work with `find-file`.

I'd like for this argument to be mandatory, without file there's no using the CLI I'm working with, can I just ``:allow-empty nil`` ? 

Thanks for the help and the package

**Comment by kyleam** [comment]
> My understanding is that I should use the `:reader` but I can't get that to work with `find-file`.

I'm just a fellow user, but that's my understanding too.  A reader like

```elisp
(defun stan-read-input-file (prompt _initial-input _history)
  (expand-file-name (read-file-name prompt nil nil t)))
```

should work.

> I'd like for this argument to be mandatory, without file there's no using the CLI I'm working with, can I just `:allow-empty nil` ?

I don't think that's relevant for forcing users to specify something, just for preventing them from specifying an empty string for the value.  If you want to treat it as mandatory, I wonder if it'd be better to drop the transient option and make the action always read the file in its interactive form.  (`magit-diff-paths` provides an example of something like that.)


p.s. Stan is great :)  Is the tool you're working on published anywhere yet?

**Comment by Nathan-Furnal** [comment]
I found the answer in another question! But I'm not sure it's the best way to go about it. 
```elisp
(defun read-file-name-transient-wrapper (prompt initial-input history)
  "Wrapper function to insert PROMPT in a transient friendly way.
Similarly takes INITIAL-INPUT and HISTORY arguments to the same effect.
Thanks to https://github.com/magit/transient/issues/88"
  (read-file-name prompt nil nil t initial-input))

(transient-define-argument stan-transient:--input ()
  :description "Input data file"
  :class 'transient-option
  :allow-empty nil
  :shortarg "i"
  :reader 'read-file-name-transient-wrapper
  :prompt "Data file path: "
  :argument "data file=")
```

I've been working for a couple days on a Stan transient, especially with the most used options. 

I'm trying to dynamically get the relevant paths and let the users just run models. 
My problem now is that i have to send the arguments to compile or an async shell.

It works when I run it straight from eval when I hard-code the cmd arguments but for some reason, sending the arguments to compile or shell doesn't seem to work. 

I'll post it once it works somewhat haha
