### ISSUE TITLE
Equivalent of :foreign-keys run

### ISSUE THREAD

**Issue by rgrinberg** [magit/transient#99]
Hydra has this useful `foreign-keys` option to allow keys to be passed from the parent map:
https://github.com/abo-abo/hydra#foreign-keys

Is there something equivalent in transient?

**Comment by tarsius** [comment]
Instead of `:exit` and `:foreign-keys` we have `:transient-suffix` and `:transient-non-suffix`. The values have to be a `transient--do-*` function (or `nil`, the default). `nil` is like `transient--do-warn`. You probably want `transient--do-stay`, `transient--do-call` or `transient--do-exit`.

There is no shorthand like `:color` but see `transient-semantic-coloring`.

Individual suffixes take a `:transient` argument, whose value should also be a `transient--do-*` function or a boolean.

**Comment by rgrinberg** [comment]
Thanks for the response. I gave these a try but I'm not getting the result I want. Let me give a concrete example so it's perhaps more obvious:

```
(defhydra rg/block-nav (:foreign-keys run)
  "Block Navigation"
  ("q" nil "quit")
  ("L" block-nav-next-indentation-level)
  ("J" block-nav-next-block)
  ("K" block-nav-previous-block)
  ("H" block-nav-prev-indentation-level))
```

I have this hydra for block based navigation. The nice thing about it is that if I press keys outside of the hydra, they will be passed to the keymap outside while the hydra persists.

I've tried replacing it with this transient:
```
(define-transient-command rg/block-nav-t ()
  "transient for block nav"
  :transient-suffix     'transient--do-stay
  :transient-non-suffix 'transient--do-warn
  [["Child/Parent"
    ("L" "Next Indent" block-nav-next-indentation-level)
    ("H" "Prev Indent" block-nav-previous-indentation-level)]
   ["Siblings"
    ("J" "Left" block-nav-next-block)
    ("K" "Right" block-nav-previous-block)]])
```

With `transient--do-stay`. But I still can't get the behavior where suffixes not defined are treated as normal keys.

**Comment by tarsius** [comment]
```diff
 (define-transient-command rg/block-nav-t ()
   "transient for block nav"
-  :transient-suffix     'transient--do-stay
-  :transient-non-suffix 'transient--do-warn
+  :transient-suffix     'transient--do-call ; "Call the command after exporting variables and stay transient."
+  :transient-non-suffix 'transient--do-stay ; "Call the command without exporting variables and stay transient."
   [["Child/Parent"
     ("L" "Next Indent" block-nav-next-indentation-level)
     ("H" "Prev Indent" block-nav-previous-indentation-level)]
    ["Siblings"
     ("J" "Left"  block-nav-next-block)
-    ("K" "Right" block-nav-previous-block)]])
+    ("K" "Right" block-nav-previous-block)]
+   [("q" "quit"  transient-quit-one)
+    ("Q" "quit"  my-do-something-and-quit :transient nil)
+    ]])
```

The quit command is not really necessary, you can just use `C-g`. `my-do-something-and-quit` has to explicitly be made non-transient. That is not necessary for `transient-quit-one` because that is defined as non-transient by default.

**Comment by rgrinberg** [comment]
It works. Magic!

I'm hoping that `transient--do-*` are stable. A bit scared off by the naming convention which implies this is a private API.

Thanks for all your hard work. Transient is 💯

**Comment by tarsius** [comment]
I don't expect the behavior to change.
